{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-adapters",
    "version": "8.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-adapters-8.13.1.aar",
          "url": "databinding-adapters-8.13.1.aar",
          "size": 70403,
          "sha512": "ce18faf01b3a9dc96c80dfeb4afa205b735cb914d34db8c8c5a0333f41d580493df6cd7330fa5bdc9a454133d2fbb72af4a2909bc2f7768e5d2c2a56ade2176e",
          "sha256": "fdfe6e2605b92dc37c9394ec5615435b1433c078c21c39c528d58475ff18ddd2",
          "sha1": "5831d0606b1717b7336808b308aae58de3f36c49",
          "md5": "76dd63d196cc78701fd8823ec2dbc2c5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-adapters-8.13.1.aar",
          "url": "databinding-adapters-8.13.1.aar",
          "size": 70403,
          "sha512": "ce18faf01b3a9dc96c80dfeb4afa205b735cb914d34db8c8c5a0333f41d580493df6cd7330fa5bdc9a454133d2fbb72af4a2909bc2f7768e5d2c2a56ade2176e",
          "sha256": "fdfe6e2605b92dc37c9394ec5615435b1433c078c21c39c528d58475ff18ddd2",
          "sha1": "5831d0606b1717b7336808b308aae58de3f36c49",
          "md5": "76dd63d196cc78701fd8823ec2dbc2c5"
        }
      ]
    }
  ]
}
