{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.8.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.8.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.8.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.8.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.8.0.jar",
          "url": "builder-8.8.0.jar",
          "size": 15222934,
          "sha512": "bfcf82dc33b92b83933336ac44aed4348f006c09e3caecda5dc63a013a7fd84b13a510212181fc166d800cb130abf20d045649d401fc9d1783de85a7fb2dbc00",
          "sha256": "02fd566a80f375faa764a89b03345d3b5e8a70d0ced199357ecb86374ed413a5",
          "sha1": "2a04e6d3911e49b7aa5a92f071febc982936deeb",
          "md5": "661cabf96b19eac1089f06a09acba238"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.8.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.8.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.8.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.8.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.8.0"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.8.0"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.8.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.8.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.8.0"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.8.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.8.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.8.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.8.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.8.0.jar",
          "url": "builder-8.8.0.jar",
          "size": 15222934,
          "sha512": "bfcf82dc33b92b83933336ac44aed4348f006c09e3caecda5dc63a013a7fd84b13a510212181fc166d800cb130abf20d045649d401fc9d1783de85a7fb2dbc00",
          "sha256": "02fd566a80f375faa764a89b03345d3b5e8a70d0ced199357ecb86374ed413a5",
          "sha1": "2a04e6d3911e49b7aa5a92f071febc982936deeb",
          "md5": "661cabf96b19eac1089f06a09acba238"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.8.0-javadoc.jar",
          "url": "builder-8.8.0-javadoc.jar",
          "size": 345928,
          "sha512": "0f92428e1e0520ff5ffb657c14d2bd9262d075ad04977c8bfef58bef8e0c2913fa330779c859cbfdcb9b26ff234b03b4369465ca7de0ae750aa2ecc8d76f7091",
          "sha256": "de1db68ecf3da3e9bb9a402b1c9862d86ceea64ae09a09a33a34e74a26408f18",
          "sha1": "963ad750e77f09b51f0570223558f55c688c84d7",
          "md5": "a7616c41245f8d536c593d4424b1ebe0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.8.0-sources.jar",
          "url": "builder-8.8.0-sources.jar",
          "size": 284440,
          "sha512": "c3c5bec453f319b1bbdb55cfc7f72a0ca2fef694e24b89168b2d060688038a84ce4fde3a73baf1278fc0a387c3d75590373dea1511d0088813b5db70ea41b4c5",
          "sha256": "34afdac7dd48437b4b29631f576d079e39da1bd80a91a6decce4e97c2eb2822b",
          "sha1": "ed90cbab1650405e59667b0b2f8ee78e6909fa6c",
          "md5": "11c280e040112f677abdabe74524f5f9"
        }
      ]
    }
  ]
}
