{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "viewbinding",
    "version": "8.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-8.12.2.aar",
          "url": "viewbinding-8.12.2.aar",
          "size": 1861,
          "sha512": "3580827553553238bd37b3c37db04db1bb5e6a8b24c0a30abc7f234753d0af3eb054f49bd8bcfe7098e48fc63367ec2c48d5585dac1e2f2aa1c1920b5a117d9e",
          "sha256": "1b7b0b8c9bdd4f0637760dbe6b3a261e4b5ae714f5c25cd9c90cee0240077f31",
          "sha1": "66ff1808d36755785f0206bde9804f16e47f1cc1",
          "md5": "25afae9f91747fb63706d3f66cef547c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-8.12.2.aar",
          "url": "viewbinding-8.12.2.aar",
          "size": 1861,
          "sha512": "3580827553553238bd37b3c37db04db1bb5e6a8b24c0a30abc7f234753d0af3eb054f49bd8bcfe7098e48fc63367ec2c48d5585dac1e2f2aa1c1920b5a117d9e",
          "sha256": "1b7b0b8c9bdd4f0637760dbe6b3a261e4b5ae714f5c25cd9c90cee0240077f31",
          "sha1": "66ff1808d36755785f0206bde9804f16e47f1cc1",
          "md5": "25afae9f91747fb63706d3f66cef547c"
        }
      ]
    }
  ]
}
