{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "viewbinding",
    "version": "8.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-8.11.0.aar",
          "url": "viewbinding-8.11.0.aar",
          "size": 1861,
          "sha512": "e46ab4d9a53fefa7c275b8e3de0553c15084d943674af2a194a7a97ae31e753ab15343e72d2825236a56e08370616d0d8c64bb6ce07d27f5069355c0260be1e4",
          "sha256": "ce93d287dccdaccf731b89371b0bade5db8679fd79b559332fdaf4454eb3371b",
          "sha1": "5fe01921cac334f5db2ba08c5ccd47b99424e7d7",
          "md5": "f2ca09c8f4137c52c219a836411dbc18"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-8.11.0.aar",
          "url": "viewbinding-8.11.0.aar",
          "size": 1861,
          "sha512": "e46ab4d9a53fefa7c275b8e3de0553c15084d943674af2a194a7a97ae31e753ab15343e72d2825236a56e08370616d0d8c64bb6ce07d27f5069355c0260be1e4",
          "sha256": "ce93d287dccdaccf731b89371b0bade5db8679fd79b559332fdaf4454eb3371b",
          "sha1": "5fe01921cac334f5db2ba08c5ccd47b99424e7d7",
          "md5": "f2ca09c8f4137c52c219a836411dbc18"
        }
      ]
    }
  ]
}
