{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.annotation",
    "module": "annotation-experimental",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-experimental-1.3.1.aar",
          "url": "annotation-experimental-1.3.1.aar",
          "size": 36833,
          "sha512": "1a69615593160ec052bea80f31487b2dd9034af9b042530ad2a0074e816e6371b2d886336d7b84901d25216377e18c36e3f380ddefa02203dc577bcf821f1f2f",
          "sha256": "e4d49dc3880b7b7437ea54ce71461e02897faa4e1ecc53e63ecadb1a14c20c9c",
          "sha1": "96a98340221569e1c2deb3da92de5ca6e3389a65",
          "md5": "0d84b9160f79f0dd37df3dae4fa2a75c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-experimental-1.3.1.aar",
          "url": "annotation-experimental-1.3.1.aar",
          "size": 36833,
          "sha512": "1a69615593160ec052bea80f31487b2dd9034af9b042530ad2a0074e816e6371b2d886336d7b84901d25216377e18c36e3f380ddefa02203dc577bcf821f1f2f",
          "sha256": "e4d49dc3880b7b7437ea54ce71461e02897faa4e1ecc53e63ecadb1a14c20c9c",
          "sha1": "96a98340221569e1c2deb3da92de5ca6e3389a65",
          "md5": "0d84b9160f79f0dd37df3dae4fa2a75c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotation-experimental-1.3.1-sources.jar",
          "url": "annotation-experimental-1.3.1-sources.jar",
          "size": 5257,
          "sha512": "2a1f6920dd9ab709f0770acb4fde26b8c012eb44f7b7894ad9c023c3bffb346748b89cd163b18b88fcf94e77806c4d99bb0071aa818451448b7b5359831ba743",
          "sha256": "d23e1a3f75f5cb1b45f900eb1a5bcc6accc2db841a4d3d9d334754e73ae60b2c",
          "sha1": "e8c866b6b200091c23ff11d6334cbcb61693fe85",
          "md5": "6fcd29af8bb4aca6031954cbcdddf8a6"
        }
      ]
    }
  ]
}