{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-core",
    "version": "1.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "aa4ctwign5bgbgnn6ch7nslzle"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.16.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-metadata-1.5.2-all.jar",
          "url": "kotlinx-coroutines-core-1.5.2-all.jar",
          "size": 78843,
          "sha512": "6fa44d2d57203af3765051117ec4f96d10ff04304e2034d9f4adf1a8583c53aadb7a3289105b7be22201ac563c11ff7c9084a8fec091d17bb6383a40ad6d6ad9",
          "sha256": "4d19a1c1c82bd973d034644f4ffa3d5355cb61bd34575aff86cc609e0e41d6e1",
          "sha1": "5389a2d00b711ff7e664b14c1c51ecf8a9a70387",
          "md5": "ac49d0f128d241fd0e6ba2e458c51788"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-1.5.2.jar",
          "url": "kotlinx-coroutines-core-1.5.2.jar",
          "size": 168804,
          "sha512": "dcdc4395e753ea4bc9bd9e15f50ae0e9aabb287de0924ef360c594bc5b687a8745df3199a0f986fad3b9f0995789c7c82d8c8083172a43eed1a4cacc342d8c90",
          "sha256": "1962ebc6cffb7645c6f5f17524690d8a728086344f1219e63c9ca0c4d8f327d7",
          "sha1": "b69812855f235ec832341b48e721a5e62e7a888c",
          "md5": "a903addd7efdd1c4f1ca34d6ee1c4d83"
        }
      ]
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosarm32/1.5.2/kotlinx-coroutines-core-iosarm32-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosarm32",
        "version": "1.5.2"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosarm32/1.5.2/kotlinx-coroutines-core-iosarm32-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosarm32",
        "version": "1.5.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosarm64/1.5.2/kotlinx-coroutines-core-iosarm64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosarm64",
        "version": "1.5.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosarm64/1.5.2/kotlinx-coroutines-core-iosarm64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosarm64",
        "version": "1.5.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iossimulatorarm64/1.5.2/kotlinx-coroutines-core-iossimulatorarm64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iossimulatorarm64",
        "version": "1.5.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iossimulatorarm64/1.5.2/kotlinx-coroutines-core-iossimulatorarm64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iossimulatorarm64",
        "version": "1.5.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosx64/1.5.2/kotlinx-coroutines-core-iosx64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosx64",
        "version": "1.5.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosx64/1.5.2/kotlinx-coroutines-core-iosx64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosx64",
        "version": "1.5.2"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-js/1.5.2/kotlinx-coroutines-core-js-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-js",
        "version": "1.5.2"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-js/1.5.2/kotlinx-coroutines-core-js-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-js",
        "version": "1.5.2"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-js/1.5.2/kotlinx-coroutines-core-js-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-js",
        "version": "1.5.2"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-js/1.5.2/kotlinx-coroutines-core-js-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-js",
        "version": "1.5.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-jvm/1.5.2/kotlinx-coroutines-core-jvm-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-jvm",
        "version": "1.5.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-jvm/1.5.2/kotlinx-coroutines-core-jvm-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-jvm",
        "version": "1.5.2"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-linuxx64/1.5.2/kotlinx-coroutines-core-linuxx64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-linuxx64",
        "version": "1.5.2"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-macosarm64/1.5.2/kotlinx-coroutines-core-macosarm64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-macosarm64",
        "version": "1.5.2"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-macosarm64/1.5.2/kotlinx-coroutines-core-macosarm64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-macosarm64",
        "version": "1.5.2"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-macosx64/1.5.2/kotlinx-coroutines-core-macosx64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-macosx64",
        "version": "1.5.2"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-macosx64/1.5.2/kotlinx-coroutines-core-macosx64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-macosx64",
        "version": "1.5.2"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-mingwx64/1.5.2/kotlinx-coroutines-core-mingwx64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-mingwx64",
        "version": "1.5.2"
      }
    },
    {
      "name": "mingwX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-mingwx64/1.5.2/kotlinx-coroutines-core-mingwx64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-mingwx64",
        "version": "1.5.2"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvosarm64/1.5.2/kotlinx-coroutines-core-tvosarm64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvosarm64",
        "version": "1.5.2"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvosarm64/1.5.2/kotlinx-coroutines-core-tvosarm64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvosarm64",
        "version": "1.5.2"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvossimulatorarm64/1.5.2/kotlinx-coroutines-core-tvossimulatorarm64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvossimulatorarm64",
        "version": "1.5.2"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvossimulatorarm64/1.5.2/kotlinx-coroutines-core-tvossimulatorarm64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvossimulatorarm64",
        "version": "1.5.2"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvosx64/1.5.2/kotlinx-coroutines-core-tvosx64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvosx64",
        "version": "1.5.2"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvosx64/1.5.2/kotlinx-coroutines-core-tvosx64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvosx64",
        "version": "1.5.2"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosarm32/1.5.2/kotlinx-coroutines-core-watchosarm32-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosarm32",
        "version": "1.5.2"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosarm32/1.5.2/kotlinx-coroutines-core-watchosarm32-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosarm32",
        "version": "1.5.2"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosarm64/1.5.2/kotlinx-coroutines-core-watchosarm64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosarm64",
        "version": "1.5.2"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosarm64/1.5.2/kotlinx-coroutines-core-watchosarm64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosarm64",
        "version": "1.5.2"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchossimulatorarm64/1.5.2/kotlinx-coroutines-core-watchossimulatorarm64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchossimulatorarm64",
        "version": "1.5.2"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchossimulatorarm64/1.5.2/kotlinx-coroutines-core-watchossimulatorarm64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchossimulatorarm64",
        "version": "1.5.2"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosx64/1.5.2/kotlinx-coroutines-core-watchosx64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosx64",
        "version": "1.5.2"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosx64/1.5.2/kotlinx-coroutines-core-watchosx64-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosx64",
        "version": "1.5.2"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosx86/1.5.2/kotlinx-coroutines-core-watchosx86-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosx86",
        "version": "1.5.2"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosx86/1.5.2/kotlinx-coroutines-core-watchosx86-1.5.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosx86",
        "version": "1.5.2"
      }
    }
  ]
}
