{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-device-info",
    "version": "31.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-device-info-31.13.0.jar",
          "url": "android-test-plugin-host-device-info-31.13.0.jar",
          "size": 10554,
          "sha512": "5d32c60da895109cf1f036121a69dec49615fd10587862ab1e98ba188883812777cc97aaca2f83528d6eff31327e5a150f26bfbea592a74d7d2a1c34024df980",
          "sha256": "bbf196a617d5f501f2696bfeabbee4b687b4e809d8d56d9c74610094f8a007cb",
          "sha1": "cb14408d4298d5e84267b95140387a2dc6a1d088",
          "md5": "1a3bfefd7af480d81e79488b84ca9ccd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "utp-common",
          "version": {
            "requires": "31.13.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-device-info-proto",
          "version": {
            "requires": "31.13.0"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-device-info-31.13.0.jar",
          "url": "android-test-plugin-host-device-info-31.13.0.jar",
          "size": 10554,
          "sha512": "5d32c60da895109cf1f036121a69dec49615fd10587862ab1e98ba188883812777cc97aaca2f83528d6eff31327e5a150f26bfbea592a74d7d2a1c34024df980",
          "sha256": "bbf196a617d5f501f2696bfeabbee4b687b4e809d8d56d9c74610094f8a007cb",
          "sha1": "cb14408d4298d5e84267b95140387a2dc6a1d088",
          "md5": "1a3bfefd7af480d81e79488b84ca9ccd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-device-info-31.13.0-javadoc.jar",
          "url": "android-test-plugin-host-device-info-31.13.0-javadoc.jar",
          "size": 261,
          "sha512": "45dada7d95416045ad218ad364f66aacc64bd07ea6ed95539dc652bf3c0977040e88a4a9b44c8653ba929ce4fbd11be1e6a21ac01dd937c8c6e797b2e824179f",
          "sha256": "cebceba5b60e48f34a1a416b857f8eaba5eaa30c3c0d69794f7f0c9356b2fea9",
          "sha1": "dcac025ba8756b080643bfa3fb7003ae0ac151dd",
          "md5": "817c65f00575dcab61f3a1e140c862b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-device-info-31.13.0-sources.jar",
          "url": "android-test-plugin-host-device-info-31.13.0-sources.jar",
          "size": 4397,
          "sha512": "0927a9714cec77f6ffd98b29b77878960cff6dbbce32aec302a39efa37535ea4ef19acf753714673ff415432eac976fe19c1887279ae8158dcdce33b317597ca",
          "sha256": "153d826b849abc3df3c039fc192395fb17698a20b75ddef24bfcf3dd4ef7fa29",
          "sha1": "aecc059ec95c8d48dbdb72801737b5c395cc7284",
          "md5": "867b01ec98f4b167753bedcfc3bc602b"
        }
      ]
    }
  ]
}
