{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aaptcompiler",
    "version": "8.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aaptcompiler-8.9.0.jar",
          "url": "aaptcompiler-8.9.0.jar",
          "size": 497144,
          "sha512": "7be5c949c125ac81304c9507bf7abe86a25437d8be60d32fdd57608d80905416b5acd9d756ece11f3ff8a89740813b456dbd39d9a11daf24753d37e3725e4f5c",
          "sha256": "599a93b5e24f5534b8b86c342c975f5a1ab3c065dbaf5e1774bb7e2b508a8b8e",
          "sha1": "0296bbe7558bb1ea637d9d99740ab228f9df7b5b",
          "md5": "97f99d94d328d9fbcc6c978f2128ce79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "8.9.0-12782657"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "aaptcompiler-8.9.0.jar",
          "url": "aaptcompiler-8.9.0.jar",
          "size": 497144,
          "sha512": "7be5c949c125ac81304c9507bf7abe86a25437d8be60d32fdd57608d80905416b5acd9d756ece11f3ff8a89740813b456dbd39d9a11daf24753d37e3725e4f5c",
          "sha256": "599a93b5e24f5534b8b86c342c975f5a1ab3c065dbaf5e1774bb7e2b508a8b8e",
          "sha1": "0296bbe7558bb1ea637d9d99740ab228f9df7b5b",
          "md5": "97f99d94d328d9fbcc6c978f2128ce79"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.9.0-javadoc.jar",
          "url": "aaptcompiler-8.9.0-javadoc.jar",
          "size": 81065,
          "sha512": "8c58c5d6545b27a430dedc5f51ce710fc44fb289207c8de3600f8f0db4945db6a1a67cdce550fb779ee6f99bfb67e22086748a845d867260e0018c7abee67dc4",
          "sha256": "3899efaed89868164e22623e99924f4ad0b021ae3464199dd0d8dacfb575a428",
          "sha1": "f46f46b983125a5fa84697371670b8949ed63f08",
          "md5": "658b93a036236335653edfe3303e4fab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.9.0-sources.jar",
          "url": "aaptcompiler-8.9.0-sources.jar",
          "size": 152981,
          "sha512": "908377b122d6fec080be5468b8fd545fd00af60c1adb57080d9099f292d3c89a76256ea2e64ca45f336c9d3a7fbb0239995ea55b4aba6c69c8ad94b201120bee",
          "sha256": "9695d1b9821dba2a91a8fe2d6181a04e88a62b6e2fba399e24ee6c7908bda56e",
          "sha1": "1467872c794af41b71e0f1aa05a7b185c67ec49d",
          "md5": "84e28c20fcf79c56b6ae36a06fbef607"
        }
      ]
    }
  ]
}
