{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-model",
    "version": "8.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "builder-model-8.9.2.jar",
          "url": "builder-model-8.9.2.jar",
          "size": 125289,
          "sha512": "aa6eb28b838a7f44fc1f2309383d93431cd7ef57e29107de27d974fa3bf44d7b28b1fa764832e146c7a9f428786e3171c8c904100cd44f8945719e3392988f10",
          "sha256": "4c9d14c92e25b5e7bf22485bfbceb30ff15d85fe31fee9b7ef6ed39a1722799d",
          "sha1": "c175f904708153ddf457fe61e9dbe6ce263f04a8",
          "md5": "8efde9a16e8df1785be17827672b2d9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "31.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-model-8.9.2.jar",
          "url": "builder-model-8.9.2.jar",
          "size": 125289,
          "sha512": "aa6eb28b838a7f44fc1f2309383d93431cd7ef57e29107de27d974fa3bf44d7b28b1fa764832e146c7a9f428786e3171c8c904100cd44f8945719e3392988f10",
          "sha256": "4c9d14c92e25b5e7bf22485bfbceb30ff15d85fe31fee9b7ef6ed39a1722799d",
          "sha1": "c175f904708153ddf457fe61e9dbe6ce263f04a8",
          "md5": "8efde9a16e8df1785be17827672b2d9c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.9.2-javadoc.jar",
          "url": "builder-model-8.9.2-javadoc.jar",
          "size": 291422,
          "sha512": "978e1213e3b89c6c0866a8790e6cf45636ed5f6dfec2972032684926499a40d5150be5968552057e1a9af281e68a5989e3f9dc93fb8dfc52c079cdd8c2f4998c",
          "sha256": "e4106414c008f97966a4d7943b6385fd2828b509ed81a4bb8b702f32aa4380ad",
          "sha1": "9cf2bd9e27087e4b2bc867b1a26a086e0b7f20f2",
          "md5": "2509c752e7205adad854768c0778b9ce"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.9.2-sources.jar",
          "url": "builder-model-8.9.2-sources.jar",
          "size": 145585,
          "sha512": "903dcf36ec96afde266f81e5d7a9fc3e0cc0f2635168606ba1552092e8c51be124a7b1ef03105bb72f32db740a63937636bb0b2cbd23ff8b4bdae4d74059cf86",
          "sha256": "7485954c93a6875277e92a1afd28a5fdae03984792bc80bbd8aa8fef7ec74da8",
          "sha1": "842f12a8b162a95a5dc4accf5799e23184bb7a13",
          "md5": "9a1cad07a32c0133411f6ddf76aeb11e"
        }
      ]
    }
  ]
}
