{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-device-provider-gradle",
    "version": "31.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-device-provider-gradle-31.8.1.jar",
          "url": "android-device-provider-gradle-31.8.1.jar",
          "size": 52783,
          "sha512": "db29be8e56a7c06f3379308b230d3d9da5990675bb8ec60d69af44d0918bd8d809cbd44ceb4534980f8922df2edc84735eb16c72bda49d63e5015a27ca01c266",
          "sha256": "f91ba01ad55b49904fc05cd3e7606eafe99a5994b07e42e2b8322824b1ffc8d9",
          "sha1": "cc63981cec8808d601107fe90ad78fc021220cb2",
          "md5": "955f9bcc306d3c6ff6b3cc7174431c40"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-device-provider-gradle-proto",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-device-provider-profile",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "core-proto",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "android-device-provider-gradle-31.8.1.jar",
          "url": "android-device-provider-gradle-31.8.1.jar",
          "size": 52783,
          "sha512": "db29be8e56a7c06f3379308b230d3d9da5990675bb8ec60d69af44d0918bd8d809cbd44ceb4534980f8922df2edc84735eb16c72bda49d63e5015a27ca01c266",
          "sha256": "f91ba01ad55b49904fc05cd3e7606eafe99a5994b07e42e2b8322824b1ffc8d9",
          "sha1": "cc63981cec8808d601107fe90ad78fc021220cb2",
          "md5": "955f9bcc306d3c6ff6b3cc7174431c40"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-device-provider-gradle-31.8.1-javadoc.jar",
          "url": "android-device-provider-gradle-31.8.1-javadoc.jar",
          "size": 261,
          "sha512": "fc6bcc7c5dfc4695005df9b56fc0171cc06db3254582edd5f3465932ff525377115bbb3ed572b6680e3d5761f78f12fd059d9281179b1f93d9c1c98ea7184e59",
          "sha256": "4f28d3c1524d65aecdb5d2517ebe79d8d5303cde619a52f08f4c091988d84da5",
          "sha1": "712fede6dc94583ff8ac8584d849da7883ff86cb",
          "md5": "fefa9d04362b00955f95d2c537aa5d06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-device-provider-gradle-31.8.1-sources.jar",
          "url": "android-device-provider-gradle-31.8.1-sources.jar",
          "size": 14296,
          "sha512": "78ad71c450e637dadeff21d87d5c50ff594c84ebc1d08d9f0042777be8f71a23a4c63543b4fb238d3bd03a3cf860c5b7f285d15c4909423a9b0b727d3de6b76d",
          "sha256": "dcc6199190733472865a2609ba20deb4792d2988af15a3ab89d769a005be50bf",
          "sha1": "573ee129b923970b7f2edd70fda6ae49cca3aedd",
          "md5": "122773737a9d4f4d03a077c614db76e7"
        }
      ]
    }
  ]
}
