{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "manifest-merger",
    "version": "31.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "manifest-merger-31.9.1.jar",
          "url": "manifest-merger-31.9.1.jar",
          "size": 258837,
          "sha512": "57169a56a89e61c6e9455892c0e07b951bfad84722480076603b3104c9e96fe043faf1e705217443b18bdacda6f5222e6d878c7aab96c9bd67defc1b6151d285",
          "sha256": "f421d232516c489f34300e2120d18c66a623a5cb7a9e3a1ee836324c6e9b6128",
          "sha1": "2bdbfcb2117fe7e47dc8eb01eb1911618c2d2e91",
          "md5": "c7e10c339ddfdc3a88ea9464c06009ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.9.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.9.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "manifest-merger-31.9.1.jar",
          "url": "manifest-merger-31.9.1.jar",
          "size": 258837,
          "sha512": "57169a56a89e61c6e9455892c0e07b951bfad84722480076603b3104c9e96fe043faf1e705217443b18bdacda6f5222e6d878c7aab96c9bd67defc1b6151d285",
          "sha256": "f421d232516c489f34300e2120d18c66a623a5cb7a9e3a1ee836324c6e9b6128",
          "sha1": "2bdbfcb2117fe7e47dc8eb01eb1911618c2d2e91",
          "md5": "c7e10c339ddfdc3a88ea9464c06009ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.9.1-javadoc.jar",
          "url": "manifest-merger-31.9.1-javadoc.jar",
          "size": 275772,
          "sha512": "6c3f7377b4b4cccbd672df02d20b5856407c2cd7a6987c611575a415db6dfdf96fb1d3aa171a74ab9857ad5b4c6335a8d2c2b06907b095d9cd103122babce4ae",
          "sha256": "93f1511507830dcf3a7bc577a2edbf79add61f9f6f85d4e4705c4f2068dd9353",
          "sha1": "4dbe9166b3292f37ca03fdf8cc5743d99243b28d",
          "md5": "9482abee3922bf181c8ec48d704a1ae3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.9.1-sources.jar",
          "url": "manifest-merger-31.9.1-sources.jar",
          "size": 236511,
          "sha512": "541c743b85c28f18c01eca53073f29261bec5bed2e565f6281ce1a6ed874022428f544de721637025ee3edbea7b4616c2b768808fbb777a4340da835af150504",
          "sha256": "c2bab07d1a39d3bd170445d6d3188a165831ab209f33f0e0bd870e864b27f566",
          "sha1": "01ef5970f229730b6a8c2fa09d4452c4f934a58f",
          "md5": "7791c78e21838de875f0f6992af08505"
        }
      ]
    }
  ]
}
