{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.13.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.13.1.jar",
          "url": "builder-8.13.1.jar",
          "size": 15811892,
          "sha512": "17e90f2c790e6d63e3ba3558542376988c01bc3e145010e925aa9ec94640095f762490d41d9f59495c42d0a8448d4179905e9c42c6b4ce17f8973367513d5922",
          "sha256": "8f139ffd353fbd57f7f532ba420afc4bc50e1e09c750ff914702abb4a47eb505",
          "sha1": "74bd2ef9a01c850add1329fbe4c118fb6706e748",
          "md5": "f39c289d65ee6bd861320a19c25e2c9f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.13.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.13.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.13.1"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.13.1"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.13.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.13.1"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.79"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.79"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.13.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.13.1.jar",
          "url": "builder-8.13.1.jar",
          "size": 15811892,
          "sha512": "17e90f2c790e6d63e3ba3558542376988c01bc3e145010e925aa9ec94640095f762490d41d9f59495c42d0a8448d4179905e9c42c6b4ce17f8973367513d5922",
          "sha256": "8f139ffd353fbd57f7f532ba420afc4bc50e1e09c750ff914702abb4a47eb505",
          "sha1": "74bd2ef9a01c850add1329fbe4c118fb6706e748",
          "md5": "f39c289d65ee6bd861320a19c25e2c9f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.13.1-javadoc.jar",
          "url": "builder-8.13.1-javadoc.jar",
          "size": 341755,
          "sha512": "b1f732c6edffa3e0596986c48678692f04cecb409974185290d50d20bd7b85ce775dad337e90ad6ee96733349c7be6df3366868295170d978658c1255976be5f",
          "sha256": "ba0c22e12b28df1f3bf78696689ab0e0f471def58454fc0953a05c39cb0ec53a",
          "sha1": "b0945346d748de656a2cdb9f338d118535c8dd7b",
          "md5": "a25929fb928cabe2869db3cc0417c74a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.13.1-sources.jar",
          "url": "builder-8.13.1-sources.jar",
          "size": 283788,
          "sha512": "9a0ed0ab7665539d6354f462be27b5fcc3f900e78ac86a27a06087122fc681ebfec2e5cba03b4b84c643b49d1a7134e3e4b01883de96046abc2a04702c243332",
          "sha256": "51b9b60105e6057d5ca8019eff5e4c84b1bfe6eead94d8fada058e000ff71f72",
          "sha1": "7ace0eb3e11509c6c5449230ca10c782daf04859",
          "md5": "73c15a234b55a7aee3629aea50b7344f"
        }
      ]
    }
  ]
}
