{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "8.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.11.0.jar",
          "url": "gradle-api-8.11.0.jar",
          "size": 370466,
          "sha512": "3fe49573bd03b100396f764ef2072564f2b427bc8dbb2a86ee01584bb2ddf9bb3b2539f8719de831437c261d7ca79a10dca637b67fe3097ea6aba85fc78ab4a3",
          "sha256": "3e819b72d73115b62a404a340c7574490a2b6d9e78a16eac7f1def4bfc1c4918",
          "sha1": "69349a5c2cb59869753bdda3ed6e205a9bd797ce",
          "md5": "643276f1ecdbccad4bc5ebc8b8ea4d44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.11.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.11.0.jar",
          "url": "gradle-api-8.11.0.jar",
          "size": 370466,
          "sha512": "3fe49573bd03b100396f764ef2072564f2b427bc8dbb2a86ee01584bb2ddf9bb3b2539f8719de831437c261d7ca79a10dca637b67fe3097ea6aba85fc78ab4a3",
          "sha256": "3e819b72d73115b62a404a340c7574490a2b6d9e78a16eac7f1def4bfc1c4918",
          "sha1": "69349a5c2cb59869753bdda3ed6e205a9bd797ce",
          "md5": "643276f1ecdbccad4bc5ebc8b8ea4d44"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.11.0-javadoc.jar",
          "url": "gradle-api-8.11.0-javadoc.jar",
          "size": 151115,
          "sha512": "b7fb23e7beb21de84bf47e06c737d97ad02115910b9b268276f234fe1a674f7df6a7eb37912f54232eeeda01bdb619b8e31ed12cbbac59e3776ae563b8c3168f",
          "sha256": "fcbb77c9320655cfd74197e0a25c7a23da5218506a501e77372d0c09eaa43d1d",
          "sha1": "3bd414c7446103ef3541618b7238525f3e0161c2",
          "md5": "c8ab953470616f734eb27fe9aeaa2a2c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.11.0-sources.jar",
          "url": "gradle-api-8.11.0-sources.jar",
          "size": 361454,
          "sha512": "3d92299159a99a7980735b77bb3a68dfdd4589c50855d7ea85a42cc16e75285761b645b6c1312bba2bee7fe996cf3fd429f9195910db0d071404ea4fd50cca55",
          "sha256": "567bdd4b87d9949af99288c48d6e6fa3f48a0b5369a4e1f3f2bf3b2d2cb3dcbe",
          "sha1": "2e0c7fef024e926d70fb6e1c021188664103df2a",
          "md5": "47b2ffea431ab3f2204d0f485463ffdf"
        }
      ]
    }
  ]
}
