{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "viewbinding",
    "version": "8.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-8.8.1.aar",
          "url": "viewbinding-8.8.1.aar",
          "size": 1860,
          "sha512": "ecf5f8f2cfbcd6ce6485af0abf7d74905d92cae17097d2abed82d37e3e32647aa063838e08a46fba43539edcde3ed500fe09a983c466d8905acf13621ecc5077",
          "sha256": "da461ac01030b572b6d26b538908bacce88284f36af4b660e17a2342706ecb63",
          "sha1": "0f1962be4317d77a3e8293983cb8f40d4dafe0d0",
          "md5": "a00758c314a3b1a586e84f745f577dcb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-8.8.1.aar",
          "url": "viewbinding-8.8.1.aar",
          "size": 1860,
          "sha512": "ecf5f8f2cfbcd6ce6485af0abf7d74905d92cae17097d2abed82d37e3e32647aa063838e08a46fba43539edcde3ed500fe09a983c466d8905acf13621ecc5077",
          "sha256": "da461ac01030b572b6d26b538908bacce88284f36af4b660e17a2342706ecb63",
          "sha1": "0f1962be4317d77a3e8293983cb8f40d4dafe0d0",
          "md5": "a00758c314a3b1a586e84f745f577dcb"
        }
      ]
    }
  ]
}
