{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-gradle-plugin",
    "version": "2.2.20-2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "symbol-processing-gradle-plugin-2.2.20-2.0.3.jar",
          "url": "symbol-processing-gradle-plugin-2.2.20-2.0.3.jar",
          "size": 254317,
          "sha512": "e83badb066897a980c7779f035c1b50c486dbb90541b008b5b744b58d478e98219a3890db6005dff74144973b93fd2a09b2296ca3d1a29b94bad7adf87bcf3de",
          "sha256": "7638e2240de03eb9075bb504bf563eedb111b1ce4390ffdffbfe4993f40d1d5f",
          "sha1": "f8dd0b279841024bc9b2ffd47b7a910ab75efef3",
          "md5": "f3ac56d02659fe7f78522e36f0e11345"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.2.20-2.0.3"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-common-deps",
          "version": {
            "requires": "2.2.20-2.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-gradle-plugin-2.2.20-2.0.3.jar",
          "url": "symbol-processing-gradle-plugin-2.2.20-2.0.3.jar",
          "size": 254317,
          "sha512": "e83badb066897a980c7779f035c1b50c486dbb90541b008b5b744b58d478e98219a3890db6005dff74144973b93fd2a09b2296ca3d1a29b94bad7adf87bcf3de",
          "sha256": "7638e2240de03eb9075bb504bf563eedb111b1ce4390ffdffbfe4993f40d1d5f",
          "sha1": "f8dd0b279841024bc9b2ffd47b7a910ab75efef3",
          "md5": "f3ac56d02659fe7f78522e36f0e11345"
        }
      ]
    }
  ]
}
