{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "atomicfu",
    "version": "0.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "atomicfu-metadata-0.22.0.jar",
          "url": "atomicfu-0.22.0.jar",
          "size": 16521,
          "sha512": "d3db2fb4b91a5e331139d7d76debc71c8f6099a0b070fc46282e2cde0f0ccdefbcf18b7c0969000f85f442691c8408e6a62a174b7204366af7ef5c95f05a0f87",
          "sha256": "ac35005e91b89e2e69ee477805ee184ddb88be5ba60b86bdb1748072045eed31",
          "sha1": "a013b6059e270ea4eb856d71da6a9dddb8ab1fc6",
          "md5": "a48c7d74e92238bba18e911104a3b55b"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "atomicfu-kotlin-0.22.0-sources.jar",
          "url": "atomicfu-0.22.0-sources.jar",
          "size": 10324,
          "sha512": "98e990a8ee43443fc3eabff5e916ab33f8a9ff0fdc7e8e8e9b448dd3b61ba666d07c51f172aa8b215452389d69a2d19192cd62459cf3a5abe8db0a11f6052fe6",
          "sha256": "c3be0cb1a5c34d2f86da683eed8591e122f2643d7d496ed7174cecd164e13b7d",
          "sha1": "87469eb272968fecac3b0b591a4cc4490dbfb100",
          "md5": "7ac6508b441b28f4fa79a9e3060e85b0"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-androidnativearm32/0.22.0/atomicfu-androidnativearm32-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-androidnativearm32",
        "version": "0.22.0"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-androidnativearm32/0.22.0/atomicfu-androidnativearm32-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-androidnativearm32",
        "version": "0.22.0"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-androidnativearm64/0.22.0/atomicfu-androidnativearm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-androidnativearm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-androidnativearm64/0.22.0/atomicfu-androidnativearm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-androidnativearm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-androidnativex64/0.22.0/atomicfu-androidnativex64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-androidnativex64",
        "version": "0.22.0"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-androidnativex64/0.22.0/atomicfu-androidnativex64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-androidnativex64",
        "version": "0.22.0"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-androidnativex86/0.22.0/atomicfu-androidnativex86-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-androidnativex86",
        "version": "0.22.0"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-androidnativex86/0.22.0/atomicfu-androidnativex86-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-androidnativex86",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosarm32/0.22.0/atomicfu-iosarm32-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosarm32",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosarm32/0.22.0/atomicfu-iosarm32-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosarm32",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosarm32/0.22.0/atomicfu-iosarm32-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosarm32",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosarm64/0.22.0/atomicfu-iosarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosarm64/0.22.0/atomicfu-iosarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosarm64/0.22.0/atomicfu-iosarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iossimulatorarm64/0.22.0/atomicfu-iossimulatorarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iossimulatorarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iossimulatorarm64/0.22.0/atomicfu-iossimulatorarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iossimulatorarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iossimulatorarm64/0.22.0/atomicfu-iossimulatorarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iossimulatorarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosx64/0.22.0/atomicfu-iosx64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosx64",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosx64/0.22.0/atomicfu-iosx64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosx64",
        "version": "0.22.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosx64/0.22.0/atomicfu-iosx64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosx64",
        "version": "0.22.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../atomicfu-js/0.22.0/atomicfu-js-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-js",
        "version": "0.22.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../atomicfu-js/0.22.0/atomicfu-js-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-js",
        "version": "0.22.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../atomicfu-js/0.22.0/atomicfu-js-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-js",
        "version": "0.22.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../atomicfu-jvm/0.22.0/atomicfu-jvm-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-jvm",
        "version": "0.22.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../atomicfu-jvm/0.22.0/atomicfu-jvm-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-jvm",
        "version": "0.22.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../atomicfu-jvm/0.22.0/atomicfu-jvm-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-jvm",
        "version": "0.22.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-linuxarm64/0.22.0/atomicfu-linuxarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-linuxarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-linuxarm64/0.22.0/atomicfu-linuxarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-linuxarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-linuxx64/0.22.0/atomicfu-linuxx64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-linuxx64",
        "version": "0.22.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-linuxx64/0.22.0/atomicfu-linuxx64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-linuxx64",
        "version": "0.22.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosarm64/0.22.0/atomicfu-macosarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosarm64/0.22.0/atomicfu-macosarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosarm64/0.22.0/atomicfu-macosarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosx64/0.22.0/atomicfu-macosx64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosx64",
        "version": "0.22.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosx64/0.22.0/atomicfu-macosx64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosx64",
        "version": "0.22.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosx64/0.22.0/atomicfu-macosx64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosx64",
        "version": "0.22.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-mingwx64/0.22.0/atomicfu-mingwx64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-mingwx64",
        "version": "0.22.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-mingwx64/0.22.0/atomicfu-mingwx64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-mingwx64",
        "version": "0.22.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosarm64/0.22.0/atomicfu-tvosarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosarm64/0.22.0/atomicfu-tvosarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosarm64/0.22.0/atomicfu-tvosarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvossimulatorarm64/0.22.0/atomicfu-tvossimulatorarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvossimulatorarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvossimulatorarm64/0.22.0/atomicfu-tvossimulatorarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvossimulatorarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvossimulatorarm64/0.22.0/atomicfu-tvossimulatorarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvossimulatorarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosx64/0.22.0/atomicfu-tvosx64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosx64",
        "version": "0.22.0"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosx64/0.22.0/atomicfu-tvosx64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosx64",
        "version": "0.22.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosx64/0.22.0/atomicfu-tvosx64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosx64",
        "version": "0.22.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm32/0.22.0/atomicfu-watchosarm32-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm32",
        "version": "0.22.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm32/0.22.0/atomicfu-watchosarm32-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm32",
        "version": "0.22.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm32/0.22.0/atomicfu-watchosarm32-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm32",
        "version": "0.22.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm64/0.22.0/atomicfu-watchosarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm64/0.22.0/atomicfu-watchosarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm64/0.22.0/atomicfu-watchosarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosdevicearm64/0.22.0/atomicfu-watchosdevicearm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosdevicearm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosdevicearm64/0.22.0/atomicfu-watchosdevicearm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosdevicearm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosdevicearm64/0.22.0/atomicfu-watchosdevicearm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosdevicearm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchossimulatorarm64/0.22.0/atomicfu-watchossimulatorarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchossimulatorarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchossimulatorarm64/0.22.0/atomicfu-watchossimulatorarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchossimulatorarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchossimulatorarm64/0.22.0/atomicfu-watchossimulatorarm64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchossimulatorarm64",
        "version": "0.22.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosx64/0.22.0/atomicfu-watchosx64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosx64",
        "version": "0.22.0"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosx64/0.22.0/atomicfu-watchosx64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosx64",
        "version": "0.22.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosx64/0.22.0/atomicfu-watchosx64-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosx64",
        "version": "0.22.0"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosx86/0.22.0/atomicfu-watchosx86-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosx86",
        "version": "0.22.0"
      }
    },
    {
      "name": "watchosX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosx86/0.22.0/atomicfu-watchosx86-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosx86",
        "version": "0.22.0"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosx86/0.22.0/atomicfu-watchosx86-0.22.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosx86",
        "version": "0.22.0"
      }
    }
  ]
}
