{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "8.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.9.1.jar",
          "url": "gradle-api-8.9.1.jar",
          "size": 369541,
          "sha512": "8e95ef9c35f394db450dbe7e239b85905813d2bc49950b6c3ad73407918ae8ba40006c03de89ef823c16d01e670572d1f34af1e83e2cb53eaaec2f84a81bb892",
          "sha256": "2befa7bb32ffc2d83a24bd8eac0edf5576f8a33cf51caf7752332b70ec1c25d1",
          "sha1": "cb1f5854bebf3b56c02cd747c7530d73c098ff99",
          "md5": "b6c08410cf1a2983788fbfbe38426f4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.9.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.9.1.jar",
          "url": "gradle-api-8.9.1.jar",
          "size": 369541,
          "sha512": "8e95ef9c35f394db450dbe7e239b85905813d2bc49950b6c3ad73407918ae8ba40006c03de89ef823c16d01e670572d1f34af1e83e2cb53eaaec2f84a81bb892",
          "sha256": "2befa7bb32ffc2d83a24bd8eac0edf5576f8a33cf51caf7752332b70ec1c25d1",
          "sha1": "cb1f5854bebf3b56c02cd747c7530d73c098ff99",
          "md5": "b6c08410cf1a2983788fbfbe38426f4c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.9.1-javadoc.jar",
          "url": "gradle-api-8.9.1-javadoc.jar",
          "size": 151115,
          "sha512": "e6b6247171d30e39fe0b55ede6cd7d53983904642e53e8e7b111bcaf651864f363bf38831e7958aa8dc42f3f057efdb7f7e7e0cacdfb6acd8a491eb8ae2ba8d6",
          "sha256": "5b80c45d8b0197c47ef7bcb133fc2610a66abb06ab3088d8693398c8bb12f379",
          "sha1": "87f4989772318fc947a6484237e9de0f76335c34",
          "md5": "b301607a181cc224fb2390d4303c280b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.9.1-sources.jar",
          "url": "gradle-api-8.9.1-sources.jar",
          "size": 359465,
          "sha512": "d74fe958f5cb01d60d40abd08c3f9be343f8358284abb743c072404bf4d9d64abe3338680b072c45a049d670cc6aac8a3f17237f4323fa863648e0058beddb3f",
          "sha256": "a8ac4f13c8b679b66d014238a5238c335f0b1a3fe88cd981c08af7dd3fe60e7a",
          "sha1": "1526c1aa5f46941b16a6888706bcca5a9f2298c3",
          "md5": "d31c044526a3708619fd6460fdc05b91"
        }
      ]
    }
  ]
}
