{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-apk-installer",
    "version": "31.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-apk-installer-31.8.1.jar",
          "url": "android-test-plugin-host-apk-installer-31.8.1.jar",
          "size": 20095,
          "sha512": "f4ef171a2bf67ff3ab4a629f9208edcd68595e119bde4e4b3601b44daa4af44a9edf359122944d179c063ff2b6301de61e1a54c642121bb9cf69ddb6b4422e2f",
          "sha256": "cedd4f2ed260e04993f12be1fd07dbfcf4263a420fbc343409d33c399eaa3edb",
          "sha1": "9e2ea47e4c3eb9850f738124de3a110146b588c1",
          "md5": "7e92e1f99bc5f3626bac71e1eb7e126a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-apk-installer-proto",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "core-proto",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-apk-installer-31.8.1.jar",
          "url": "android-test-plugin-host-apk-installer-31.8.1.jar",
          "size": 20095,
          "sha512": "f4ef171a2bf67ff3ab4a629f9208edcd68595e119bde4e4b3601b44daa4af44a9edf359122944d179c063ff2b6301de61e1a54c642121bb9cf69ddb6b4422e2f",
          "sha256": "cedd4f2ed260e04993f12be1fd07dbfcf4263a420fbc343409d33c399eaa3edb",
          "sha1": "9e2ea47e4c3eb9850f738124de3a110146b588c1",
          "md5": "7e92e1f99bc5f3626bac71e1eb7e126a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-apk-installer-31.8.1-javadoc.jar",
          "url": "android-test-plugin-host-apk-installer-31.8.1-javadoc.jar",
          "size": 261,
          "sha512": "71953db7b5d403ded60dfe04c3861670f44fd9bc5ffd8b2612bfa3a80a01daff753c4c62c87a7e3922ab3db3d0588bf51283cde2e772c7f6d5cfab10d2022c0c",
          "sha256": "562973801cd3121d3b54b0e03f99e19f52b8e8b7b89314e251a4291aa5d1abad",
          "sha1": "592cc9934bf06b6b73c595afc52684d27105073e",
          "md5": "b3e9f157a6e63de793dd8839ea3c46b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-apk-installer-31.8.1-sources.jar",
          "url": "android-test-plugin-host-apk-installer-31.8.1-sources.jar",
          "size": 5825,
          "sha512": "71a76f31723a723ad9c9e450bb0033754387ae0f5c9ca036ee2035b754a39c6436998765c1a33ee582a757a13e5ff0cf4976f10688606747c02ae986b1d7f9d6",
          "sha256": "a76cb58d1e42a06df1a1e4e77c7c59d02a0cb6ce7c558d879bd324bd7b14e2a6",
          "sha1": "4b3014895ac6d3c1600dd685aac7b9affb0f21c9",
          "md5": "016644c62de1eb32bd36b0d05ce26f03"
        }
      ]
    }
  ]
}
