{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.material",
    "module": "material",
    "version": "1.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.coordinatorlayout",
          "module": "coordinatorlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.resourceinspection",
          "module": "resourceinspection-annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.13.0.aar",
          "url": "material-1.13.0.aar",
          "size": 2500936,
          "sha512": "77ac6a176697378895942a3a5e5a3e14716bf3c93072e372dc0022988448ee6460ef004c40598407ec4544ef6b05928d2a9905d4f70af397e238312606bcdb83",
          "sha256": "6d5e1cbb67c05bcdcbbf84005787dafd354a155f59a4d3800fd45fa7eb3689f5",
          "sha1": "010c9cd2e7df7a176fc2773f9d947b67b1c8bd9b",
          "md5": "955d6664205128fda6d8091386797b92"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.coordinatorlayout",
          "module": "coordinatorlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.resourceinspection",
          "module": "resourceinspection-annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.13.0.aar",
          "url": "material-1.13.0.aar",
          "size": 2500936,
          "sha512": "77ac6a176697378895942a3a5e5a3e14716bf3c93072e372dc0022988448ee6460ef004c40598407ec4544ef6b05928d2a9905d4f70af397e238312606bcdb83",
          "sha256": "6d5e1cbb67c05bcdcbbf84005787dafd354a155f59a4d3800fd45fa7eb3689f5",
          "sha1": "010c9cd2e7df7a176fc2773f9d947b67b1c8bd9b",
          "md5": "955d6664205128fda6d8091386797b92"
        }
      ]
    }
  ]
}
