{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-common",
    "version": "2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-common-2.5.1.jar",
          "url": "lifecycle-common-2.5.1.jar",
          "size": 24230,
          "sha512": "c0de9430629e76ab63f7732a506a5f15c01b1f793f07328557f653f38085203b773350a54c7f28c4023ac23b71d44a5dd449493230d4ac365984e26d9aace5a2",
          "sha256": "20ad1520f625cf455e6afd7290988306d3a9886efa993e0860fbabf4bb3f7bda",
          "sha1": "1fdb7349701e9cf2f0a69fc10642b6fef6bb3e12",
          "md5": "381756ff38dc17098f4ac09b6ebb7aae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-common-2.5.1.jar",
          "url": "lifecycle-common-2.5.1.jar",
          "size": 24230,
          "sha512": "c0de9430629e76ab63f7732a506a5f15c01b1f793f07328557f653f38085203b773350a54c7f28c4023ac23b71d44a5dd449493230d4ac365984e26d9aace5a2",
          "sha256": "20ad1520f625cf455e6afd7290988306d3a9886efa993e0860fbabf4bb3f7bda",
          "sha1": "1fdb7349701e9cf2f0a69fc10642b6fef6bb3e12",
          "md5": "381756ff38dc17098f4ac09b6ebb7aae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-common-2.5.1-sources.jar",
          "url": "lifecycle-common-2.5.1-sources.jar",
          "size": 19603,
          "sha512": "fee124ab05116fc109962f6223a0298b5dbf580b690f771e3d22ab9964b241c075750a44e72d1597a832105522323be5482b637fe9e388f7f1265b02a8776406",
          "sha256": "0b271fb88b890846b34c4abdc645106a4155431973f19e961df498bc7f892ab4",
          "sha1": "29609e3d01eaafd06c688c5366154174cf686c12",
          "md5": "582a74cc55811d286cd767be4685892a"
        }
      ]
    }
  ]
}