{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "viewbinding",
    "version": "8.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-8.9.1.aar",
          "url": "viewbinding-8.9.1.aar",
          "size": 1860,
          "sha512": "86b9df83b972adfc604aef601c911c80b6aba909b5bc49ad731873734bdee5e6a477e81f7a39438c235720fee40587a9c0db073e38dd61a4092b682a302ad7a9",
          "sha256": "59d8874e6a17c880979418a0088ded13be58e9419c09dc97d6d7864f9e77d51e",
          "sha1": "a73da6126c51ec2cbd7686d38bae4d73782ea877",
          "md5": "acc25402d97ef1502eda7a8668fd3646"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-8.9.1.aar",
          "url": "viewbinding-8.9.1.aar",
          "size": 1860,
          "sha512": "86b9df83b972adfc604aef601c911c80b6aba909b5bc49ad731873734bdee5e6a477e81f7a39438c235720fee40587a9c0db073e38dd61a4092b682a302ad7a9",
          "sha256": "59d8874e6a17c880979418a0088ded13be58e9419c09dc97d6d7864f9e77d51e",
          "sha1": "a73da6126c51ec2cbd7686d38bae4d73782ea877",
          "md5": "acc25402d97ef1502eda7a8668fd3646"
        }
      ]
    }
  ]
}
