{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.constraintlayout",
    "module": "constraintlayout-core",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "constraintlayout-core-1.1.0.jar",
          "url": "constraintlayout-core-1.1.0.jar",
          "size": 585267,
          "sha512": "97a44ccc576093b2826f0ec7960fda5b75e83592fb3942cc2c6d4675b85f46336714deead6b20600e1a418474c2cb6ea8dc1f0156c1c1efef7f9bd6c522ec6ea",
          "sha256": "a8b90d19f7d758f7cb8962491547cf57cb7837c31fe3b00e01c4e85df7bf4851",
          "sha1": "e678372aacb0e91f0ed44854a8a413fc93283050",
          "md5": "6b1939bfb136557ccbed010ecf9315a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "constraintlayout-core-1.1.0.jar",
          "url": "constraintlayout-core-1.1.0.jar",
          "size": 585267,
          "sha512": "97a44ccc576093b2826f0ec7960fda5b75e83592fb3942cc2c6d4675b85f46336714deead6b20600e1a418474c2cb6ea8dc1f0156c1c1efef7f9bd6c522ec6ea",
          "sha256": "a8b90d19f7d758f7cb8962491547cf57cb7837c31fe3b00e01c4e85df7bf4851",
          "sha1": "e678372aacb0e91f0ed44854a8a413fc93283050",
          "md5": "6b1939bfb136557ccbed010ecf9315a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "constraintlayout-core-1.1.0-sources.jar",
          "url": "constraintlayout-core-1.1.0-sources.jar",
          "size": 361020,
          "sha512": "eb19ea99b6062d57a7489e61a3aaf90d83b11bcced88840c2d8c8e5f3206b8e509255afb8cf2d73b0e1f62d5fc1af4894a4a15dd19ca0b5ca4be1297983a4060",
          "sha256": "ff4323c0a3b884ef61d39a8b99f902ef6fd82595641698afcd3d034bbc5fc81d",
          "sha1": "ca94a12f41a3a87fc78ff58dd76ed9d699f03930",
          "md5": "a9eb1b3ce6cb0f5b0aac8a9b0901ab8f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "constraintlayout-core-1.1.0-versionMetadata.json",
          "url": "constraintlayout-core-1.1.0-versionMetadata.json",
          "size": 185069,
          "sha512": "adf1bbbb89aaa1d88def456c6258f56c2f873db6fcda6478444786dec209f5116f0201629c353a567610aca1a1eac422bc1a1029e53b5825f341956e2cb900c7",
          "sha256": "378a5ca5ffa4c8adc46653bf537662a28a2cc8764af8d119da937b3fb43a6513",
          "sha1": "415bb51f5d4938d984a16910fb7d65a43bdee2e7",
          "md5": "ec9cf7e33f40650ff637466c191b8735"
        }
      ]
    }
  ]
}