{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-migration",
    "version": "2.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "14169401"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-okio",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-migration-metadata-2.8.2.jar",
          "url": "room-migration-2.8.2.jar",
          "size": 22701,
          "sha512": "b47f0cbd39c03d8001a028ba9397bdf6945ad7bdfd2647c0142a16d41a6c260822579b3928b63997b9e588abe6f3152aa7ff2bacdc5809b178f5fbb57a371f89",
          "sha256": "8e52e9263dfb13104fb1e26add519f81f4074436c901c8b6cc7d0d457e02ef93",
          "sha1": "8ffe07fd2fc2c76a1b6c56ed9cd32640aa14aa34",
          "md5": "7c7c5157f9adcd706adfc0e90e896ed9"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-migration-kotlin-2.8.2-sources.jar",
          "url": "room-migration-2.8.2-sources.jar",
          "size": 21955,
          "sha512": "333bcb49b00cc1aa8b43dab8f9f48349b3b2108116c5e22c174dfbb917abf759da461dc91aaaaa3a1129d5d58f64b83928d0f1793e1c927416a51844236bf5e7",
          "sha256": "3fc12eeb008e9fa4124ef11bc010919fd48571fa80193b773bfe634108470780",
          "sha1": "ba5e7a77288774d47a1d739ddb1f9ce10c48c9be",
          "md5": "fbb4d3487cc44d3f743775684fe02c31"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-migration-2.8.2-multiplatform-sources.jar",
          "url": "room-migration-2.8.2-multiplatform-sources.jar",
          "size": 24139,
          "sha512": "bb886a64cfd0059ab1dc3b471536782cd7a00eab69cb4c697ea6e654211f584a911c1d1819c9cda4c70d05b534c71908ef02e122c12ce1381e546bcf3d73a483",
          "sha256": "1b0edce6defad8ea1f6d98f3608f1c0f6a1b8d47dce4bf1b1405140466e00dac",
          "sha1": "cc21fd95c23e5e7e97fe061279198d06bbfe79ba",
          "md5": "b81b2a5d87ae4e60698508c0064c11d5"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-migration is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "room-migration-2.8.2-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-iosarm64/2.8.2/room-migration-iosarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-iosarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-iosarm64/2.8.2/room-migration-iosarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-iosarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-iosarm64/2.8.2/room-migration-iosarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-iosarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-iossimulatorarm64/2.8.2/room-migration-iossimulatorarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-iossimulatorarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-iossimulatorarm64/2.8.2/room-migration-iossimulatorarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-iossimulatorarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-iossimulatorarm64/2.8.2/room-migration-iossimulatorarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-iossimulatorarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-iosx64/2.8.2/room-migration-iosx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-iosx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-iosx64/2.8.2/room-migration-iosx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-iosx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-iosx64/2.8.2/room-migration-iosx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-iosx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../room-migration-jvm/2.8.2/room-migration-jvm-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-jvm",
        "version": "2.8.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../room-migration-jvm/2.8.2/room-migration-jvm-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-jvm",
        "version": "2.8.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../room-migration-jvm/2.8.2/room-migration-jvm-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-jvm",
        "version": "2.8.2"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-linuxarm64/2.8.2/room-migration-linuxarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-linuxarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-linuxarm64/2.8.2/room-migration-linuxarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-linuxarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-linuxx64/2.8.2/room-migration-linuxx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-linuxx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-linuxx64/2.8.2/room-migration-linuxx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-linuxx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-macosarm64/2.8.2/room-migration-macosarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-macosarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-macosarm64/2.8.2/room-migration-macosarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-macosarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-macosarm64/2.8.2/room-migration-macosarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-macosarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-macosx64/2.8.2/room-migration-macosx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-macosx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-macosx64/2.8.2/room-migration-macosx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-macosx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-macosx64/2.8.2/room-migration-macosx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-macosx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-tvosarm64/2.8.2/room-migration-tvosarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-tvosarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-tvosarm64/2.8.2/room-migration-tvosarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-tvosarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-tvosarm64/2.8.2/room-migration-tvosarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-tvosarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-tvossimulatorarm64/2.8.2/room-migration-tvossimulatorarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-tvossimulatorarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-tvossimulatorarm64/2.8.2/room-migration-tvossimulatorarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-tvossimulatorarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-tvossimulatorarm64/2.8.2/room-migration-tvossimulatorarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-tvossimulatorarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-tvosx64/2.8.2/room-migration-tvosx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-tvosx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-tvosx64/2.8.2/room-migration-tvosx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-tvosx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-tvosx64/2.8.2/room-migration-tvosx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-tvosx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-watchosarm32/2.8.2/room-migration-watchosarm32-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-watchosarm32",
        "version": "2.8.2"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-watchosarm32/2.8.2/room-migration-watchosarm32-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-watchosarm32",
        "version": "2.8.2"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-watchosarm32/2.8.2/room-migration-watchosarm32-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-watchosarm32",
        "version": "2.8.2"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-watchosarm64/2.8.2/room-migration-watchosarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-watchosarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-watchosarm64/2.8.2/room-migration-watchosarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-watchosarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-watchosarm64/2.8.2/room-migration-watchosarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-watchosarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-watchosdevicearm64/2.8.2/room-migration-watchosdevicearm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-watchosdevicearm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-watchosdevicearm64/2.8.2/room-migration-watchosdevicearm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-watchosdevicearm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-watchosdevicearm64/2.8.2/room-migration-watchosdevicearm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-watchosdevicearm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-watchossimulatorarm64/2.8.2/room-migration-watchossimulatorarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-watchossimulatorarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-watchossimulatorarm64/2.8.2/room-migration-watchossimulatorarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-watchossimulatorarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-watchossimulatorarm64/2.8.2/room-migration-watchossimulatorarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-watchossimulatorarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-watchosx64/2.8.2/room-migration-watchosx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-watchosx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-watchosx64/2.8.2/room-migration-watchosx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-watchosx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-migration-watchosx64/2.8.2/room-migration-watchosx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-migration-watchosx64",
        "version": "2.8.2"
      }
    }
  ]
}