{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-common-deps",
    "version": "2.0.21-1.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-common-deps-2.0.21-1.0.27.jar",
          "url": "symbol-processing-common-deps-2.0.21-1.0.27.jar",
          "size": 109757,
          "sha512": "e5451da3e01679be621aad83a00b66786b8ef7195c2f15ee697c25b716ca97dc02c858a7d9bb22f8625517953167c75524155540c7f3e1d6e961fe8a9abcded1",
          "sha256": "82304e1d07da39bf68ad7a191e955b439edd47a41aae09986a2b74cd0a5eb732",
          "sha1": "9b746d0e1052f4feb7e1b8bbae192070eaec70d1",
          "md5": "a4ab6df8e0c305bbb410fa18ced2e85e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-common-deps-2.0.21-1.0.27.jar",
          "url": "symbol-processing-common-deps-2.0.21-1.0.27.jar",
          "size": 109757,
          "sha512": "e5451da3e01679be621aad83a00b66786b8ef7195c2f15ee697c25b716ca97dc02c858a7d9bb22f8625517953167c75524155540c7f3e1d6e961fe8a9abcded1",
          "sha256": "82304e1d07da39bf68ad7a191e955b439edd47a41aae09986a2b74cd0a5eb732",
          "sha1": "9b746d0e1052f4feb7e1b8bbae192070eaec70d1",
          "md5": "a4ab6df8e0c305bbb410fa18ced2e85e"
        }
      ]
    }
  ]
}
