{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aaptcompiler",
    "version": "8.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aaptcompiler-8.8.2.jar",
          "url": "aaptcompiler-8.8.2.jar",
          "size": 497060,
          "sha512": "38f7b123e4309ece980a74e118269cb7fc1b9c41b1ed5906f61eef026810f5197ab4112fa7a0186b050e944ea94b1e4ed35a6f6696c639e88d6cbb20c3022bee",
          "sha256": "e76bf37f2ee34f125ba95ebc316569d39b6a8227b56e568cfb117755ca4818a6",
          "sha1": "bd8fbb91d4e95a7add69c3ef96a80cfc49f5a7ff",
          "md5": "e238763aa13fc9b325d0e38fa4e9da49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "8.8.2-12006047"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.8.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.8.2"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "aaptcompiler-8.8.2.jar",
          "url": "aaptcompiler-8.8.2.jar",
          "size": 497060,
          "sha512": "38f7b123e4309ece980a74e118269cb7fc1b9c41b1ed5906f61eef026810f5197ab4112fa7a0186b050e944ea94b1e4ed35a6f6696c639e88d6cbb20c3022bee",
          "sha256": "e76bf37f2ee34f125ba95ebc316569d39b6a8227b56e568cfb117755ca4818a6",
          "sha1": "bd8fbb91d4e95a7add69c3ef96a80cfc49f5a7ff",
          "md5": "e238763aa13fc9b325d0e38fa4e9da49"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.8.2-javadoc.jar",
          "url": "aaptcompiler-8.8.2-javadoc.jar",
          "size": 81065,
          "sha512": "63f754387469a055b1780f9abea4f5bf5bbf45eeebad0ad24490d2b0d88bc69e7a867c3bae097bb0477ea34276d041a00612fc4242a142f088375d0185519ce2",
          "sha256": "bf4959abf05aa3a421240adaeb6b9321350651526eea69a0487ea1ad90a290f3",
          "sha1": "e09edbe9dcbef14ce113ecc18b67b4bbbf41f8ea",
          "md5": "8e73aaf0ba0e3c52ef9597b67bb52487"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.8.2-sources.jar",
          "url": "aaptcompiler-8.8.2-sources.jar",
          "size": 152981,
          "sha512": "e6c6f01576bcbb9aa0970a24abaf5550e2e616935384780ebfc8f829db0e4808cf76d4fbe6b174545311914f04b8f84710302ac0b302cc9ba41063f09807efed",
          "sha256": "0827a56e0e4093c77854952d646ed63d1af7f2b9626e35559148db2fb64d34a5",
          "sha1": "eea9a5213e01f2843d36ee9ecef5899bc1fbeac2",
          "md5": "3bf06d718e504d8b0ff8d77ccf3df383"
        }
      ]
    }
  ]
}
