{
  "formatVersion": "1.1",
  "component": {
    "url": "../../graphics-shapes/1.0.1/graphics-shapes-1.0.1.module",
    "group": "androidx.graphics",
    "module": "graphics-shapes",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "graphics-shapes-release.aar",
          "url": "graphics-shapes-android-1.0.1.aar",
          "size": 88037,
          "sha512": "ef1e421ec80927425b70f4dcca2beb0e77a8ffa22900e77f0d19798be7d2d4bb0a3e9e14ed46d71dd8d35329d760a64cf3f1282704576bc2b9092aa58932102a",
          "sha256": "7171269a4122feabb071768df46d10b362e47ac75fd0aa8dbcafa1f44f61b40c",
          "sha1": "ded3e866d7abfae45cf454b31522b374b838ef11",
          "md5": "4ad326be7628a16914e31db1bf3b6fec"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "graphics-shapes-release.aar",
          "url": "graphics-shapes-android-1.0.1.aar",
          "size": 88037,
          "sha512": "ef1e421ec80927425b70f4dcca2beb0e77a8ffa22900e77f0d19798be7d2d4bb0a3e9e14ed46d71dd8d35329d760a64cf3f1282704576bc2b9092aa58932102a",
          "sha256": "7171269a4122feabb071768df46d10b362e47ac75fd0aa8dbcafa1f44f61b40c",
          "sha1": "ded3e866d7abfae45cf454b31522b374b838ef11",
          "md5": "4ad326be7628a16914e31db1bf3b6fec"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "graphics-shapes-android-1.0.1-sources.jar",
          "url": "graphics-shapes-android-1.0.1-sources.jar",
          "size": 48524,
          "sha512": "02d36f4f2f39090aa07da62b8acb42be497283104b28849da589b9f185c439c8bf6cb1148ece8ce3ff78e9259719667f446a18f46f6b585cac78ceba0c82639f",
          "sha256": "ae746c3a68f8631d2b8b2ac74a8a1e59352112e86380bd966d741c6d4efa61c6",
          "sha1": "25e452c0a6209dcec9c5f4b7bfcc873aeada1c30",
          "md5": "bb471c44b59cad5ae9ce8e77b3d5a354"
        }
      ]
    }
  ]
}