{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat-resources",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          },
          "reason": "appcompat-resources is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.7.1-sources.jar",
          "url": "appcompat-resources-1.7.1-sources.jar",
          "size": 40127,
          "sha512": "fd1797c47a419ecf9f4fc5cf0c9cbd45dca31ff009086a1757c736072ffd3b1f20a0cd6769950a65ebe78f920ce96b935700d73350ec6f2cd92dfcc2b4eef341",
          "sha256": "cacf441fbbec0ebf12b4308bbeeb9a7389387c35a66f13bd2551dc328cf33ead",
          "sha1": "cb084bf039d2b49e02cb58e0da0044fed264a4fb",
          "md5": "697807af3a432a71b615d676f8980b53"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          },
          "reason": "appcompat-resources is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.7.1.aar",
          "url": "appcompat-resources-1.7.1.aar",
          "size": 63997,
          "sha512": "9f3f8334ccb2bc0aa3507881009104446d0c1aece093fb62e5366df8c816cdf9b3292ae24a0c8f315580d7617b47d6d2d6e6cd16cf8cc5cd1520f12a79e0452d",
          "sha256": "8e2db31224ca53b108c784da2b361959062716d416b210cfef3d5a3828306df0",
          "sha1": "a0696fa573503263c7d5570ecd5e6032d397a287",
          "md5": "c958c7fb99e287a845ce663bd693b0ec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          },
          "reason": "appcompat-resources is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.7.1.aar",
          "url": "appcompat-resources-1.7.1.aar",
          "size": 63997,
          "sha512": "9f3f8334ccb2bc0aa3507881009104446d0c1aece093fb62e5366df8c816cdf9b3292ae24a0c8f315580d7617b47d6d2d6e6cd16cf8cc5cd1520f12a79e0452d",
          "sha256": "8e2db31224ca53b108c784da2b361959062716d416b210cfef3d5a3828306df0",
          "sha1": "a0696fa573503263c7d5570ecd5e6032d397a287",
          "md5": "c958c7fb99e287a845ce663bd693b0ec"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          },
          "reason": "appcompat-resources is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.7.1-versionMetadata.json",
          "url": "appcompat-resources-1.7.1-versionMetadata.json",
          "size": 4232,
          "sha512": "0b9d6b088cb3f14f3bcdff504d67004a682ffa28fee566ebe8b621fc850249914e344e7682e90202fa787dfb4bde6e6514dbd136cabf86645cb13025fbc4689c",
          "sha256": "a11db908ffcf1bd0275f2da342a3a539b7ce15faaaad5baa6b9fcf5505bd7440",
          "sha1": "54676f6f7bfb29f84dff1c1d7ce7c7b313af6fc2",
          "md5": "43bad3fd4f83703f93dbd92a0e222fd9"
        }
      ]
    }
  ]
}