{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "manifest-merger",
    "version": "31.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "manifest-merger-31.8.0.jar",
          "url": "manifest-merger-31.8.0.jar",
          "size": 256815,
          "sha512": "a79247d99a9fb14bbf6dcdc76767829b233cad3d1c855a61cbdbe2ad35be0f63cd4f1b55c5ec1c8884167c178d51eb153eaeb6b212264eaa1e3788ddf672b5ec",
          "sha256": "bbee1472702040404d9e800ebf9aa884c671fde925e4e2ef3bde45acf5b79abd",
          "sha1": "d2afb8c2b56963a8cf34fd8513952aa8b4650d97",
          "md5": "e0337c7a39d65f5e570a4709f3b06610"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.8.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.8.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.8.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "manifest-merger-31.8.0.jar",
          "url": "manifest-merger-31.8.0.jar",
          "size": 256815,
          "sha512": "a79247d99a9fb14bbf6dcdc76767829b233cad3d1c855a61cbdbe2ad35be0f63cd4f1b55c5ec1c8884167c178d51eb153eaeb6b212264eaa1e3788ddf672b5ec",
          "sha256": "bbee1472702040404d9e800ebf9aa884c671fde925e4e2ef3bde45acf5b79abd",
          "sha1": "d2afb8c2b56963a8cf34fd8513952aa8b4650d97",
          "md5": "e0337c7a39d65f5e570a4709f3b06610"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.8.0-javadoc.jar",
          "url": "manifest-merger-31.8.0-javadoc.jar",
          "size": 275781,
          "sha512": "feb1dfd8e17874ca0474a3c736a1200a559d1cdca14e00e3bec6f6572cb8c939df41b18da7604eae98abed6e6814b28f31c161b5723d9bd641ff3bc9a514e9d3",
          "sha256": "805e9477de5e815319c17e8e17210050b9b1892cd829694d24a6e580aedf893e",
          "sha1": "0a3e07cb65df36a60221b36bfd73abd240ea27a8",
          "md5": "4b13f19d00d3ed8dbfdbc1ef7aabf07e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.8.0-sources.jar",
          "url": "manifest-merger-31.8.0-sources.jar",
          "size": 235313,
          "sha512": "506a40972c19666223fedad8868e7f8db338d8e2f575bb8b1cc2408e7e65eae37b45b2713f41bc3aad37c8cac6aab1783651f7f784793bb3f6b08b87f2a5cc54",
          "sha256": "319332f88930b402594aecf43b398c787f3c4a3b116fd251593ac0b8c3ba4dff",
          "sha1": "9018fe1b9674651283812a8c4a2f9567f042fea9",
          "md5": "653cdff48ea08da60d2dd7c470463c2c"
        }
      ]
    }
  ]
}
