{
  "formatVersion": "1.1",
  "component": {
    "group": "io.objectbox",
    "module": "objectbox-generator",
    "version": "5.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "objectbox-generator-5.0.1.jar",
          "url": "objectbox-generator-5.0.1.jar",
          "size": 131064,
          "sha512": "4e18bc4a635ff6cfe216c6f78fd1739dcd463e93587118337958eea197147c2d067dc10d9b115c6e05c74e98f477c4d34c1f28e40fe61f815e7a4d65807d4f02",
          "sha256": "e835a2a7641ab5e5ff3938a17f834e22051f3ba3e4067eb777a434136797c67b",
          "sha1": "1615a8728027345b151e0da5aa41d4f31265059a",
          "md5": "cf5b3e42ef824859e1392e688f6f4320"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.objectbox",
          "module": "objectbox-java",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.32"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "essentials",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "objectbox-generator-5.0.1.jar",
          "url": "objectbox-generator-5.0.1.jar",
          "size": 131064,
          "sha512": "4e18bc4a635ff6cfe216c6f78fd1739dcd463e93587118337958eea197147c2d067dc10d9b115c6e05c74e98f477c4d34c1f28e40fe61f815e7a4d65807d4f02",
          "sha256": "e835a2a7641ab5e5ff3938a17f834e22051f3ba3e4067eb777a434136797c67b",
          "sha1": "1615a8728027345b151e0da5aa41d4f31265059a",
          "md5": "cf5b3e42ef824859e1392e688f6f4320"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "objectbox-generator-5.0.1-javadoc.jar",
          "url": "objectbox-generator-5.0.1-javadoc.jar",
          "size": 72506,
          "sha512": "bb8def86e5f2e3ebd17250ce94b514b5ae4f3fe3b437027d8289adad2db58a13c0fb69dd139bfcaa07f5361bf23f4fc0d533763ffcf6d87ecc420a48e1ef8057",
          "sha256": "4ebb33a402a7b8d7fac9147f6540e4ecb03f57272b3163e35502eec52b93ebb0",
          "sha1": "fb363645bedbc591d5d22edc1ed3b1e52fd4a973",
          "md5": "e7119b8fdb02278c2d2553dadd330426"
        }
      ]
    }
  ]
}
