{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-settings-api",
    "version": "8.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.8.2.jar",
          "url": "gradle-settings-api-8.8.2.jar",
          "size": 9941,
          "sha512": "16cddb43312eb26fa49f3bc1a295d1448d01e3491be59cd85edbe8d85ad290ae85b0bb88115ace96e54bc6f106c6ca7097cfbe0c0630bf9c038144ebe7232af5",
          "sha256": "6b1a665f90cf02f5fcf214a0dda4da072e0195a6c64a90b98321512906c3258a",
          "sha1": "ddd83dc8631419c046296c370cd512ca58fe6a87",
          "md5": "16351f96bd2dfbae127910a51d56d350"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-settings-api-8.8.2.jar",
          "url": "gradle-settings-api-8.8.2.jar",
          "size": 9941,
          "sha512": "16cddb43312eb26fa49f3bc1a295d1448d01e3491be59cd85edbe8d85ad290ae85b0bb88115ace96e54bc6f106c6ca7097cfbe0c0630bf9c038144ebe7232af5",
          "sha256": "6b1a665f90cf02f5fcf214a0dda4da072e0195a6c64a90b98321512906c3258a",
          "sha1": "ddd83dc8631419c046296c370cd512ca58fe6a87",
          "md5": "16351f96bd2dfbae127910a51d56d350"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.8.2-javadoc.jar",
          "url": "gradle-settings-api-8.8.2-javadoc.jar",
          "size": 261,
          "sha512": "4587aa9a6bd1fbed5ea2244d87b716e4b84b46c904323355ba69509ab692937ef9b743dee66dc05446dcb8616d253f306f271ac6ac4dff08b92a8f7b0f606ade",
          "sha256": "aa228870511d2561da244d76ffa81df0a1c72b02bcf1b70bf3a613fc2b6b8ef6",
          "sha1": "aed40d3b2326653eb6f3b25a3574edb805dd9bac",
          "md5": "87d529e3102b42e521357557b092e5ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.8.2-sources.jar",
          "url": "gradle-settings-api-8.8.2-sources.jar",
          "size": 9470,
          "sha512": "08a42afb2135a1db128ab6431aa644979d0dfa166439bc7127e9581573a2b5e519226ca3d2484e94df154e6bda3bf04a31a5fd03f2500d432e1d83803f33fa7b",
          "sha256": "4a975d135f2e20e03e6f03ad77b29ca0fb2116138e562a8934979624dec77e6c",
          "sha1": "4a9f4dd2737e6cc3cd958ecc53a5f9b42441a782",
          "md5": "690652c58069fc85b634c1496053ef1a"
        }
      ]
    }
  ]
}
