{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-paging",
    "version": "2.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "14169401"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-paging-metadata-2.8.2.jar",
          "url": "room-paging-2.8.2.jar",
          "size": 10309,
          "sha512": "7e19fdac162fdfc086d940fe5d1d60e5c2bb8cc29373bb43ed197c90945d4b0f738b9ba92159f8ec386bdd7002d012e125b341b06b77c953c363e8bf69768630",
          "sha256": "759c42b74baf7295466dc29f0bacdb0ea707448b2113483e202dc0a37343a18c",
          "sha1": "9f352dd494518c924dd78628a5ada829083e7983",
          "md5": "ce98cce37d9bfdf0454fa3ce113ad39d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-paging-kotlin-2.8.2-sources.jar",
          "url": "room-paging-2.8.2-sources.jar",
          "size": 12209,
          "sha512": "8bd5dc88a2924654292c2ede6b3c3728c0578d03f9226c30f4d161412190cd398cae110a377175b0810194d98f2be6c538039d1920b1b01661865618eb4320eb",
          "sha256": "542e42c3d99c0cabf6f1e20caa126a2e8aab3d93b4310f76f713ad3fdb4806c0",
          "sha1": "f3b21f51cf6a22e272f06949c9b9c6327bb8d49e",
          "md5": "21e0994a0281d4c38cb7baf65b2b167c"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-paging-2.8.2-multiplatform-sources.jar",
          "url": "room-paging-2.8.2-multiplatform-sources.jar",
          "size": 18648,
          "sha512": "546f5cecebd55837ce5cfb046c7c24cfcc8c7bdd4a995bebd8b59d5c745d8994753b33c5e00510f76ad149e3e79388c7ec0dc6c9ebfb8fde31af85c0d316ef12",
          "sha256": "ed00401f8dd2ae67c6371dcf67dcce0d4fea223e9dac0ac4230f04649c886121",
          "sha1": "17cc4877d4f2c769323b9a678f3c4b5f408f065a",
          "md5": "8e7452c1fa87a1651646cbe140cb5dbc"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "room-paging-2.8.2-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../room-paging-android/2.8.2/room-paging-android-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-android",
        "version": "2.8.2"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../room-paging-android/2.8.2/room-paging-android-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-android",
        "version": "2.8.2"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../room-paging-android/2.8.2/room-paging-android-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-android",
        "version": "2.8.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-iosarm64/2.8.2/room-paging-iosarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-iosarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-iosarm64/2.8.2/room-paging-iosarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-iosarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-iosarm64/2.8.2/room-paging-iosarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-iosarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-iossimulatorarm64/2.8.2/room-paging-iossimulatorarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-iossimulatorarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-iossimulatorarm64/2.8.2/room-paging-iossimulatorarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-iossimulatorarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-iossimulatorarm64/2.8.2/room-paging-iossimulatorarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-iossimulatorarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-iosx64/2.8.2/room-paging-iosx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-iosx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-iosx64/2.8.2/room-paging-iosx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-iosx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-iosx64/2.8.2/room-paging-iosx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-iosx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../room-paging-jvm/2.8.2/room-paging-jvm-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-jvm",
        "version": "2.8.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../room-paging-jvm/2.8.2/room-paging-jvm-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-jvm",
        "version": "2.8.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../room-paging-jvm/2.8.2/room-paging-jvm-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-jvm",
        "version": "2.8.2"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-linuxarm64/2.8.2/room-paging-linuxarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-linuxarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-linuxarm64/2.8.2/room-paging-linuxarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-linuxarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-linuxx64/2.8.2/room-paging-linuxx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-linuxx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-linuxx64/2.8.2/room-paging-linuxx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-linuxx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-macosarm64/2.8.2/room-paging-macosarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-macosarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-macosarm64/2.8.2/room-paging-macosarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-macosarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-macosarm64/2.8.2/room-paging-macosarm64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-macosarm64",
        "version": "2.8.2"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-macosx64/2.8.2/room-paging-macosx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-macosx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-macosx64/2.8.2/room-paging-macosx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-macosx64",
        "version": "2.8.2"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-macosx64/2.8.2/room-paging-macosx64-2.8.2.module",
        "group": "androidx.room",
        "module": "room-paging-macosx64",
        "version": "2.8.2"
      }
    }
  ]
}