{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-adapters",
    "version": "8.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-adapters-8.11.0.aar",
          "url": "databinding-adapters-8.11.0.aar",
          "size": 70402,
          "sha512": "ff2277c549745fd19607c802843f703ab5ed4fd82042b807452e56768aadb76b986ab19a75537296c3488b0ea9b45eac0a5c7ad306bea4a40711b9da1f10064f",
          "sha256": "81ea91c38b86081e706d8bc2ab213f456e043c58f8d11751f120be1ba918bc8d",
          "sha1": "62a63d3a254459ffd5ecab5dd0bcde9bf0670944",
          "md5": "eb31e2663532df37a8b460788bf1c738"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.11.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-adapters-8.11.0.aar",
          "url": "databinding-adapters-8.11.0.aar",
          "size": 70402,
          "sha512": "ff2277c549745fd19607c802843f703ab5ed4fd82042b807452e56768aadb76b986ab19a75537296c3488b0ea9b45eac0a5c7ad306bea4a40711b9da1f10064f",
          "sha256": "81ea91c38b86081e706d8bc2ab213f456e043c58f8d11751f120be1ba918bc8d",
          "sha1": "62a63d3a254459ffd5ecab5dd0bcde9bf0670944",
          "md5": "eb31e2663532df37a8b460788bf1c738"
        }
      ]
    }
  ]
}
