{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-stdlib",
    "version": "2.1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-stdlib-2.1.21.jar",
          "url": "kotlin-stdlib-2.1.21.jar",
          "size": 1724058,
          "sha512": "6f7962827c16cb87223a7fe3b2a8498619c501bd2f64e09377a0e8ba8d59b9adcfe11f6eaa429d91c7bfb8c96435de159f75d22156d0b234a2ddad33558aa209",
          "sha256": "263bdc679e1f62012db7b091796279b6d71cf36f4797a98ff1ace05835f201c8",
          "sha1": "97a0975aa19d925e109537af60eb46902920015c",
          "md5": "01269975f32698511a6062a4db034d00"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-stdlib-2.1.21.jar",
          "url": "kotlin-stdlib-2.1.21.jar",
          "size": 1724058,
          "sha512": "6f7962827c16cb87223a7fe3b2a8498619c501bd2f64e09377a0e8ba8d59b9adcfe11f6eaa429d91c7bfb8c96435de159f75d22156d0b234a2ddad33558aa209",
          "sha256": "263bdc679e1f62012db7b091796279b6d71cf36f4797a98ff1ace05835f201c8",
          "sha1": "97a0975aa19d925e109537af60eb46902920015c",
          "md5": "01269975f32698511a6062a4db034d00"
        }
      ]
    },
    {
      "name": "jvmSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-stdlib-2.1.21-sources.jar",
          "url": "kotlin-stdlib-2.1.21-sources.jar",
          "size": 688171,
          "sha512": "d99d2f22385fa5fda389aa0b32a7fc08d0ce16703e3ea303dff10937a17471bbadcd43fb9887063d7e0dd20221b41800e77e70c3b355c31ed4d54948341c2ff1",
          "sha256": "c05e6ead31a9bc17a6fbd5029c4824307992a012546aafb3800f27d1c7ee42be",
          "sha1": "5922d504d55f1f6172e7cea51b02fad38e65b094",
          "md5": "6991e18fa3c9ab8e4c713488d7a9c39e"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-stdlib-2.1.21-all.jar",
          "url": "kotlin-stdlib-2.1.21-all.jar",
          "size": 192867,
          "sha512": "32085f2a5167dee55d365c40eb7b6a426c8cb9101cc8cdfb058068bfea922880828b187ac86e633b34a9b01af3d32aa034dd423409b6b06a8ff68c460f76d2b9",
          "sha256": "81e07de34e84b29e14f3fdef902f4bc4cf1d5da959b867df683fbe1cc54ce1e1",
          "sha1": "919751264e79f13e6ec79f4eef1d5222e6520d31",
          "md5": "7c55f9d468c84fe1919db529bf3a41e5"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlin-stdlib-2.1.21-common-sources.jar",
          "url": "kotlin-stdlib-2.1.21-common-sources.jar",
          "size": 414470,
          "sha512": "c3e70d4737441a030938427210dc8a029f9ef0cd7eb91602d5a8e18e9f56f65bdc3089cab9d5a3947e7af189948c39090c441392edf967068d310b47bde459e8",
          "sha256": "e96554e4adf02f01a41cd1800ec6a6d0a62358fa4175d2ea0df47d1baa07d5b7",
          "sha1": "b317c7ad3f67cb3aae97f2eff17207fc6c88d4b0",
          "md5": "32f35d15bb75fa10c0c1fceef988ba46"
        }
      ]
    },
    {
      "name": "nativeApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.1.21"
          }
        }
      ]
    },
    {
      "name": "jsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-js/2.1.21/kotlin-stdlib-js-2.1.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-js",
        "version": "2.1.21"
      }
    },
    {
      "name": "jsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-js/2.1.21/kotlin-stdlib-js-2.1.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-js",
        "version": "2.1.21"
      }
    },
    {
      "name": "jsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-js/2.1.21/kotlin-stdlib-js-2.1.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-js",
        "version": "2.1.21"
      }
    },
    {
      "name": "wasmJsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-js/2.1.21/kotlin-stdlib-wasm-js-2.1.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-js",
        "version": "2.1.21"
      }
    },
    {
      "name": "wasmJsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-js/2.1.21/kotlin-stdlib-wasm-js-2.1.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-js",
        "version": "2.1.21"
      }
    },
    {
      "name": "wasmJsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-js/2.1.21/kotlin-stdlib-wasm-js-2.1.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-js",
        "version": "2.1.21"
      }
    },
    {
      "name": "wasmWasiApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-wasi/2.1.21/kotlin-stdlib-wasm-wasi-2.1.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-wasi",
        "version": "2.1.21"
      }
    },
    {
      "name": "wasmWasiRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-wasi/2.1.21/kotlin-stdlib-wasm-wasi-2.1.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-wasi",
        "version": "2.1.21"
      }
    },
    {
      "name": "wasmWasiSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-wasi/2.1.21/kotlin-stdlib-wasm-wasi-2.1.21.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-wasi",
        "version": "2.1.21"
      }
    }
  ]
}
