{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-ktx",
    "version": "8.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-ktx-8.11.0.aar",
          "url": "databinding-ktx-8.11.0.aar",
          "size": 8929,
          "sha512": "73065b2b7e7859a3b7e1659b912d4394b095b89f74db69d144d627276f667c096a42e4e493460cc4c17b4e04a1701a1a4399229f5c4a78c32f4fceaf2eb4766f",
          "sha256": "edae3007cf349012772a6baec45dd3af6e8b3779e1a4ccca55ce0452ea4fec67",
          "sha1": "e8b1285d4bc5e96d5f5e1e966c6d92de51a178c2",
          "md5": "15d2c3ad5ea3480301d8488a8f87c707"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-ktx-8.11.0.aar",
          "url": "databinding-ktx-8.11.0.aar",
          "size": 8929,
          "sha512": "73065b2b7e7859a3b7e1659b912d4394b095b89f74db69d144d627276f667c096a42e4e493460cc4c17b4e04a1701a1a4399229f5c4a78c32f4fceaf2eb4766f",
          "sha256": "edae3007cf349012772a6baec45dd3af6e8b3779e1a4ccca55ce0452ea4fec67",
          "sha1": "e8b1285d4bc5e96d5f5e1e966c6d92de51a178c2",
          "md5": "15d2c3ad5ea3480301d8488a8f87c707"
        }
      ]
    }
  ]
}
