{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-device-provider-ddmlib",
    "version": "31.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-device-provider-ddmlib-31.9.0.jar",
          "url": "android-device-provider-ddmlib-31.9.0.jar",
          "size": 62372,
          "sha512": "ef5bfd6d942ab6790398f358334ce3a06422f7e049cb3b1078ecba2bc60de5838557e0002f471b1a525de2debb82297cdb2944410171b9b44404579efe49c535",
          "sha256": "82a7efd700808d9536ce728ab9711ee06d42772cdcf74f36dce3b84d6a1e61d0",
          "sha1": "71531471680cb982c7047812cf673b41633ce1e9",
          "md5": "7f33ed878d1bbcbc6bae6b9687f415a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-device-provider-ddmlib-proto",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-device-provider-profile",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "core-proto",
          "version": {
            "requires": "0.0.9-alpha03"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "android-device-provider-ddmlib-31.9.0.jar",
          "url": "android-device-provider-ddmlib-31.9.0.jar",
          "size": 62372,
          "sha512": "ef5bfd6d942ab6790398f358334ce3a06422f7e049cb3b1078ecba2bc60de5838557e0002f471b1a525de2debb82297cdb2944410171b9b44404579efe49c535",
          "sha256": "82a7efd700808d9536ce728ab9711ee06d42772cdcf74f36dce3b84d6a1e61d0",
          "sha1": "71531471680cb982c7047812cf673b41633ce1e9",
          "md5": "7f33ed878d1bbcbc6bae6b9687f415a9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-device-provider-ddmlib-31.9.0-javadoc.jar",
          "url": "android-device-provider-ddmlib-31.9.0-javadoc.jar",
          "size": 261,
          "sha512": "16af9950e3717e009854e32e0593fe11714086d5ebe3564e2f096ae8cbd5af589871e85379c39adb37837c8bf9fa5a31c6062fb22c4c47a50e4d8e51175ea864",
          "sha256": "3b73f343323451b6beddb6d401f85e599b3b36738026e87915e649c2f3af096f",
          "sha1": "b0a4f30b5d02b47d934deab5c2eef8d852a8fbb1",
          "md5": "0858e49157e8e1d9ac5d04b36b26b225"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-device-provider-ddmlib-31.9.0-sources.jar",
          "url": "android-device-provider-ddmlib-31.9.0-sources.jar",
          "size": 11127,
          "sha512": "6db61a371c05a2786d45f5cc7506e9a608f33f89fd6fb0e72ca7de6970f5952c4078e05ed63de5138e5a43e9a23a48ea70e7c1d8bf1c60cf549060ddaccbc495",
          "sha256": "ee270eb0e6b6cb7773f65b5fe880dd6247caab76ebded74d6640ea886b959c66",
          "sha1": "6e43c8d3b60613fd99b8898a2da0226f29c7133e",
          "md5": "b777880a298fb1c8ab0477c868c3a315"
        }
      ]
    }
  ]
}
