{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.sqlite",
    "module": "sqlite-framework",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13287481"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-2.5.0-multiplatform-sources.jar",
          "url": "sqlite-framework-2.5.0-multiplatform-sources.jar",
          "size": 27948,
          "sha512": "88af601ac3f3377a7438ee7887c06715bee2ad604f58f3ae7f3852057bd857c1708d004f9252f2962cabb396a1f7accf04632e68d090d0cdd21d96516424b580",
          "sha256": "4edf8e5105217cef9428d32b817d4b6a8006c5167c668de9135451029a5d60fd",
          "sha1": "635a4a1134a1f4926d3c0a9599520ece4fe4ca6e",
          "md5": "75168a617a59c47f183076a8849c0e62"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "sqlite-framework-2.5.0-versionMetadata.json",
          "size": 483,
          "sha512": "809fad816517bd7af6bc8048acefa2e765ca905d159d0cccf3ceff973d17831a292bdbeb9c80fbf585ffe35e6f9b010b0528a132c1ab5f78683da6ad7aa24436",
          "sha256": "5fcca8e611c12ee946ae52c423d84dd13f7935b45904e0ae1b029e8989b66b38",
          "sha1": "347d907e17dab09339b3b4cd68cdf1c6e3a6d675",
          "md5": "1e8a3823bb41cb6b25ee8be19901bd61"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-metadata-2.5.0.jar",
          "url": "sqlite-framework-2.5.0.jar",
          "size": 36234,
          "sha512": "e409723da6f664d4c28340366fb759d77dd1ee13a04bdb2fdd3a7324c533984dcf0662a95ae12663716db12d9fe1a32e7fca76b47ec278cdc5a31de4ec79ce9f",
          "sha256": "69859dc22be411215e587a6f84593c2488c522ecbbb700ed9df39c2b63f7700b",
          "sha1": "204af1b7f92f34c8c5bc800c6dcb091458f78f92",
          "md5": "87d1d6b8a31030aa2a15c4ee85a9c43a"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-kotlin-2.5.0-sources.jar",
          "url": "sqlite-framework-2.5.0-sources.jar",
          "size": 10563,
          "sha512": "85c7c053fc686de9ada01a3d8338a8f63185dfa2fe383f58628709415f5b8769dad3466f389d7cf0bca41da1645a7a90b654a313d553a032f93f4d628095a705",
          "sha256": "74cbdd2258d07815021a0f7097801a773ba5cc058dc28d8f2b430de877e6688c",
          "sha1": "f025ae3e65ab2e827bc57759c4cdb4bd346c73ca",
          "md5": "83d0dbc35716120af0b1b35f5227507f"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sqlite-framework-android/2.5.0/sqlite-framework-android-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-android",
        "version": "2.5.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sqlite-framework-android/2.5.0/sqlite-framework-android-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-android",
        "version": "2.5.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sqlite-framework-android/2.5.0/sqlite-framework-android-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-android",
        "version": "2.5.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-iosarm64/2.5.0/sqlite-framework-iosarm64-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-iosarm64",
        "version": "2.5.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-iosarm64/2.5.0/sqlite-framework-iosarm64-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-iosarm64",
        "version": "2.5.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-iosarm64/2.5.0/sqlite-framework-iosarm64-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-iosarm64",
        "version": "2.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-iossimulatorarm64/2.5.0/sqlite-framework-iossimulatorarm64-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-iossimulatorarm64",
        "version": "2.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-iossimulatorarm64/2.5.0/sqlite-framework-iossimulatorarm64-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-iossimulatorarm64",
        "version": "2.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-iossimulatorarm64/2.5.0/sqlite-framework-iossimulatorarm64-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-iossimulatorarm64",
        "version": "2.5.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-iosx64/2.5.0/sqlite-framework-iosx64-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-iosx64",
        "version": "2.5.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-iosx64/2.5.0/sqlite-framework-iosx64-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-iosx64",
        "version": "2.5.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-iosx64/2.5.0/sqlite-framework-iosx64-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-iosx64",
        "version": "2.5.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-linuxarm64/2.5.0/sqlite-framework-linuxarm64-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-linuxarm64",
        "version": "2.5.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-linuxarm64/2.5.0/sqlite-framework-linuxarm64-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-linuxarm64",
        "version": "2.5.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-linuxx64/2.5.0/sqlite-framework-linuxx64-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-linuxx64",
        "version": "2.5.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-linuxx64/2.5.0/sqlite-framework-linuxx64-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-linuxx64",
        "version": "2.5.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-macosarm64/2.5.0/sqlite-framework-macosarm64-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-macosarm64",
        "version": "2.5.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-macosarm64/2.5.0/sqlite-framework-macosarm64-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-macosarm64",
        "version": "2.5.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-macosarm64/2.5.0/sqlite-framework-macosarm64-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-macosarm64",
        "version": "2.5.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-macosx64/2.5.0/sqlite-framework-macosx64-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-macosx64",
        "version": "2.5.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-macosx64/2.5.0/sqlite-framework-macosx64-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-macosx64",
        "version": "2.5.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sqlite-framework-macosx64/2.5.0/sqlite-framework-macosx64-2.5.0.module",
        "group": "androidx.sqlite",
        "module": "sqlite-framework-macosx64",
        "version": "2.5.0"
      }
    }
  ]
}