{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.constraintlayout",
    "module": "constraintlayout",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "constraintlayout-2.2.1-sources.jar",
          "url": "constraintlayout-2.2.1-sources.jar",
          "size": 296036,
          "sha512": "088ade51f172ff493a2a024eb41c2222f5c38b6a9e63035a5a30f3700afa5895ad87237b7a295392d618b7f73133f67be600e7aae179a97721cd3d45b6043683",
          "sha256": "1ef812ab292bc78799dea3fff38ea139ecc1cbb9fec5598d445788aea5922904",
          "sha1": "d6422fade643fbe1d813f0ab5eec74b6cddc59de",
          "md5": "52d0d7247b1c76974f3fd2c4948ef879"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "constraintlayout-2.2.1.aar",
          "url": "constraintlayout-2.2.1.aar",
          "size": 507993,
          "sha512": "bed49c7ee20425f26bed4b84afb248506938ccded87401410fe42fd7d9475274828e394f87511a7e1337ba199938de43091d83d2cf29790ad10b3c4c0da4d251",
          "sha256": "30f8d79b782d283a90f0b6f7369169d9cf560091537fdd6056d1daa9f3033763",
          "sha1": "63546b93c403153de9a59991a28445baf41376db",
          "md5": "5aff743ac9c77df6603ffb07209557c4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-core",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "constraintlayout-2.2.1.aar",
          "url": "constraintlayout-2.2.1.aar",
          "size": 507993,
          "sha512": "bed49c7ee20425f26bed4b84afb248506938ccded87401410fe42fd7d9475274828e394f87511a7e1337ba199938de43091d83d2cf29790ad10b3c4c0da4d251",
          "sha256": "30f8d79b782d283a90f0b6f7369169d9cf560091537fdd6056d1daa9f3033763",
          "sha1": "63546b93c403153de9a59991a28445baf41376db",
          "md5": "5aff743ac9c77df6603ffb07209557c4"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "constraintlayout-2.2.1-versionMetadata.json",
          "url": "constraintlayout-2.2.1-versionMetadata.json",
          "size": 96484,
          "sha512": "7d52f7d02829c53fa90aa03a2673c6189cd1e29047916d31070a59d5ee6ac0594b1cef988fc98d975e7e6c6c633276e4b526722e4c4b85335a95bbbf27f0acf5",
          "sha256": "c61e94dc6810bbf2420f531852a1d143ccf83767ba5c7c172b44521c51e54ec0",
          "sha1": "3bb7fe0a7644db58c84831b8c93b513e7e0c8b1d",
          "md5": "b0b32b74ab0dccc640abcb2f07fa3e49"
        }
      ]
    }
  ]
}