{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigationevent",
    "module": "navigationevent",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14389689"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigationevent-metadata-1.0.0.jar",
          "url": "navigationevent-1.0.0.jar",
          "size": 24295,
          "sha512": "fa82bdda901c65098f6bf21f3de9b3d4fab2686b92fb8f309f955dfa2ade7cdd5ad1cc550e7bd0339c6c9d831a3e5eb876f268ee8ec0b6fbaeec631bde6582e5",
          "sha256": "3d706844dc49606cb1aa3cd7d6b27f47f180dfc4c6d4b7b80ea478ff88dcbd93",
          "sha1": "3959ba7e22ee2823c8dc1b04a709c01a32e0bff5",
          "md5": "04b28c11d30e7528510af127ebc41b2e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent-kotlin-1.0.0-sources.jar",
          "url": "navigationevent-1.0.0-sources.jar",
          "size": 42622,
          "sha512": "84281a3a727a93816832aae3bd9ec7210287074ed314b65fdf39c651adef896c49d0159d6a1648e59567b7fc7df26ecb1a6252fe4ee0033f6f8159815e403abc",
          "sha256": "1f6049776a270ed61c2556d3f88a83e7f54200b708a3dc03622bbe52b63e4c55",
          "sha1": "3f9c09593568ae451b86967d93b1ff506043b3a2",
          "md5": "53e2e4a415f5a2aeafe1e6ea4f288ab8"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent-1.0.0-multiplatform-sources.jar",
          "url": "navigationevent-1.0.0-multiplatform-sources.jar",
          "size": 49704,
          "sha512": "1947bb86a9aa68c58b109bfc27487a96763524904b3b729cab5888a4d06aa908ee8fed8cc243f777c6be9eb863b9b0c8c99029512e46d3576a3abb14815c4bc5",
          "sha256": "51fdf38a276b2f1ee51d34f26585339131497080e1914259a1071f1ad4b5e8b8",
          "sha1": "3a2a10849ac7260b77ef80d9121f3688b9c4a547",
          "md5": "96e7223b323500a47a2650d0e55a2e7e"
        },
        {
          "name": "navigationevent-1.0.0-samples-sources.jar",
          "url": "navigationevent-1.0.0-samples-sources.jar",
          "size": 5859,
          "sha512": "ade557bee51aab3e41cde6381162fb98e8053ab0a9349fad48367d34bd5cebab5a76cb5081ad0f933e4a3f27ffb56f4ada3f1c5b2563acde1cad98d44d2fc1ac",
          "sha256": "df63ae9684f469f4538795438481b802b394d365566b5af25487e0eef2f4ac6f",
          "sha1": "b7d83bf2bf811c87eec0c4133cf342e08043060e",
          "md5": "3dc3a37e0a809197bcd92e7bf8e9c888"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "navigationevent-1.0.0-versionMetadata.json",
          "size": 8208,
          "sha512": "e6a00ed2e50b6d2a125d79c689ff2f794ba3fd0699ec6d3c4959688769bee3094baf5d9d67e2e2361c371e55561adeb86df949b77dfc4c672ace2cfaefd42c59",
          "sha256": "6e824aeeb0dbfd8f1238e785c03750d35949c620f41a20f3b347d87bf92e9f50",
          "sha1": "3ee78c5dbb62dc748ba96248a359bb22ad9e5241",
          "md5": "e8c54eee13f08f695aa871b29c2ef03a"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigationevent-android/1.0.0/navigationevent-android-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigationevent-android/1.0.0/navigationevent-android-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigationevent-android/1.0.0/navigationevent-android-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigationevent-desktop/1.0.0/navigationevent-desktop-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-desktop",
        "version": "1.0.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigationevent-desktop/1.0.0/navigationevent-desktop-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-desktop",
        "version": "1.0.0"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigationevent-desktop/1.0.0/navigationevent-desktop-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-desktop",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-iosarm64/1.0.0/navigationevent-iosarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-iosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-iosarm64/1.0.0/navigationevent-iosarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-iosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-iosarm64/1.0.0/navigationevent-iosarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-iosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-iossimulatorarm64/1.0.0/navigationevent-iossimulatorarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-iossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-iossimulatorarm64/1.0.0/navigationevent-iossimulatorarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-iossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-iossimulatorarm64/1.0.0/navigationevent-iossimulatorarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-iossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-iosx64/1.0.0/navigationevent-iosx64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-iosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-iosx64/1.0.0/navigationevent-iosx64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-iosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-iosx64/1.0.0/navigationevent-iosx64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-iosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../navigationevent-js/1.0.0/navigationevent-js-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-js",
        "version": "1.0.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../navigationevent-js/1.0.0/navigationevent-js-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-js",
        "version": "1.0.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../navigationevent-js/1.0.0/navigationevent-js-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-js",
        "version": "1.0.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-linuxarm64/1.0.0/navigationevent-linuxarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-linuxarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-linuxarm64/1.0.0/navigationevent-linuxarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-linuxarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-linuxx64/1.0.0/navigationevent-linuxx64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-linuxx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-linuxx64/1.0.0/navigationevent-linuxx64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-linuxx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-macosarm64/1.0.0/navigationevent-macosarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-macosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-macosarm64/1.0.0/navigationevent-macosarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-macosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-macosarm64/1.0.0/navigationevent-macosarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-macosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-macosx64/1.0.0/navigationevent-macosx64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-macosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-macosx64/1.0.0/navigationevent-macosx64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-macosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-macosx64/1.0.0/navigationevent-macosx64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-macosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-mingwx64/1.0.0/navigationevent-mingwx64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-mingwx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-mingwx64/1.0.0/navigationevent-mingwx64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-mingwx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-tvosarm64/1.0.0/navigationevent-tvosarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-tvosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-tvosarm64/1.0.0/navigationevent-tvosarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-tvosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-tvosarm64/1.0.0/navigationevent-tvosarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-tvosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-tvossimulatorarm64/1.0.0/navigationevent-tvossimulatorarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-tvossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-tvossimulatorarm64/1.0.0/navigationevent-tvossimulatorarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-tvossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-tvossimulatorarm64/1.0.0/navigationevent-tvossimulatorarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-tvossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-tvosx64/1.0.0/navigationevent-tvosx64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-tvosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-tvosx64/1.0.0/navigationevent-tvosx64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-tvosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-tvosx64/1.0.0/navigationevent-tvosx64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-tvosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../navigationevent-wasm-js/1.0.0/navigationevent-wasm-js-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-wasm-js",
        "version": "1.0.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../navigationevent-wasm-js/1.0.0/navigationevent-wasm-js-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-wasm-js",
        "version": "1.0.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../navigationevent-wasm-js/1.0.0/navigationevent-wasm-js-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-wasm-js",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-watchosarm32/1.0.0/navigationevent-watchosarm32-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-watchosarm32",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-watchosarm32/1.0.0/navigationevent-watchosarm32-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-watchosarm32",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-watchosarm32/1.0.0/navigationevent-watchosarm32-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-watchosarm32",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-watchosarm64/1.0.0/navigationevent-watchosarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-watchosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-watchosarm64/1.0.0/navigationevent-watchosarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-watchosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-watchosarm64/1.0.0/navigationevent-watchosarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-watchosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-watchosdevicearm64/1.0.0/navigationevent-watchosdevicearm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-watchosdevicearm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-watchosdevicearm64/1.0.0/navigationevent-watchosdevicearm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-watchosdevicearm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-watchosdevicearm64/1.0.0/navigationevent-watchosdevicearm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-watchosdevicearm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-watchossimulatorarm64/1.0.0/navigationevent-watchossimulatorarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-watchossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-watchossimulatorarm64/1.0.0/navigationevent-watchossimulatorarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-watchossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-watchossimulatorarm64/1.0.0/navigationevent-watchossimulatorarm64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-watchossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-watchosx64/1.0.0/navigationevent-watchosx64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-watchosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-watchosx64/1.0.0/navigationevent-watchosx64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-watchosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigationevent-watchosx64/1.0.0/navigationevent-watchosx64-1.0.0.module",
        "group": "androidx.navigationevent",
        "module": "navigationevent-watchosx64",
        "version": "1.0.0"
      }
    }
  ]
}