{
  "formatVersion": "1.1",
  "component": {
    "group": "io.objectbox",
    "module": "objectbox-processor",
    "version": "5.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "objectbox-processor-5.0.1.jar",
          "url": "objectbox-processor-5.0.1.jar",
          "size": 54929,
          "sha512": "6a5275c0217ea9b1bd8d83a28210543a0027a2c1e35f6288c0a262034a52022c4e2b1f62c1b2808de9c1f37b163ae27562741a34a76e76faa985b038f36dc706",
          "sha256": "0ed78a69e4df588777f6989c6531f1129c479d5d83bf05961ccc99d3f817ad19",
          "sha1": "069bff82ec763f43656331f18b18821553784380",
          "md5": "ee0f43717ffed9b42efc3172fda76b27"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.objectbox",
          "module": "objectbox-code-modifier",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.objectbox",
          "module": "objectbox-generator",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.objectbox",
          "module": "objectbox-java-api",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.objectbox",
          "module": "objectbox-java",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "net.ltgt.gradle.incap",
          "module": "incap",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "objectbox-processor-5.0.1.jar",
          "url": "objectbox-processor-5.0.1.jar",
          "size": 54929,
          "sha512": "6a5275c0217ea9b1bd8d83a28210543a0027a2c1e35f6288c0a262034a52022c4e2b1f62c1b2808de9c1f37b163ae27562741a34a76e76faa985b038f36dc706",
          "sha256": "0ed78a69e4df588777f6989c6531f1129c479d5d83bf05961ccc99d3f817ad19",
          "sha1": "069bff82ec763f43656331f18b18821553784380",
          "md5": "ee0f43717ffed9b42efc3172fda76b27"
        }
      ]
    }
  ]
}
