{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.constraintlayout",
    "module": "constraintlayout",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "constraintlayout-2.2.0-sources.jar",
          "url": "constraintlayout-2.2.0-sources.jar",
          "size": 296036,
          "sha512": "088ade51f172ff493a2a024eb41c2222f5c38b6a9e63035a5a30f3700afa5895ad87237b7a295392d618b7f73133f67be600e7aae179a97721cd3d45b6043683",
          "sha256": "1ef812ab292bc78799dea3fff38ea139ecc1cbb9fec5598d445788aea5922904",
          "sha1": "d6422fade643fbe1d813f0ab5eec74b6cddc59de",
          "md5": "52d0d7247b1c76974f3fd2c4948ef879"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "constraintlayout-2.2.0.aar",
          "url": "constraintlayout-2.2.0.aar",
          "size": 507991,
          "sha512": "99c73327a0a6c304a03339003fbf9d5e956090747866429f528d34f51b16eaccbd7114dfa780bef209d6ba1d4fc3af4fd54e577c2d4fff97929aaabbcd7d793f",
          "sha256": "c7c244100e68af49c99a6ad17694893c1be4fc55a6f539c8d78261dbbd2ce34a",
          "sha1": "646c9a918e3151b0d361c954fc2e8bfd13cb0bc3",
          "md5": "412320999a34ddd61efbfc3dd0c6e2a7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "constraintlayout-2.2.0.aar",
          "url": "constraintlayout-2.2.0.aar",
          "size": 507991,
          "sha512": "99c73327a0a6c304a03339003fbf9d5e956090747866429f528d34f51b16eaccbd7114dfa780bef209d6ba1d4fc3af4fd54e577c2d4fff97929aaabbcd7d793f",
          "sha256": "c7c244100e68af49c99a6ad17694893c1be4fc55a6f539c8d78261dbbd2ce34a",
          "sha1": "646c9a918e3151b0d361c954fc2e8bfd13cb0bc3",
          "md5": "412320999a34ddd61efbfc3dd0c6e2a7"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "constraintlayout-2.2.0-versionMetadata.json",
          "url": "constraintlayout-2.2.0-versionMetadata.json",
          "size": 96484,
          "sha512": "5e7d98a8fdc1c223691cf9ba1080e6d2bc89f16b4ae35224cbc97b8a18dddc1d6a954781f943fd250568eed8d5f868d047fce1b19d60777da6ab6371f293e8ff",
          "sha256": "449e16b4c329cf6e3c62dc7bbae8adbe9f3fbbea90795448192e2d698c02c988",
          "sha1": "47e190e74b16f5de092a24fd0921e80c7d16dabd",
          "md5": "33780f371dbc04c2e9518f301ebcbbdb"
        }
      ]
    }
  ]
}