{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-runtime",
    "version": "8.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-runtime-8.9.2.aar",
          "url": "databinding-runtime-8.9.2.aar",
          "size": 61006,
          "sha512": "4605d8a4123b4ad04b00cb85c5ca6ab8769478db5240f892e1de2e6c4265540fc23e45d8724f14c4cc78a30102cb0fe8e0aa1aea74738efb87b032adc537f429",
          "sha256": "47d6c71eb444f11ba59b1c260aa30868069be287ec2d8a9a1488767d15790e32",
          "sha1": "2cf756ecfd98bf984b555029681aacafb933a403",
          "md5": "b6cea4736042aa67e9361b267763ebb6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-runtime-8.9.2.aar",
          "url": "databinding-runtime-8.9.2.aar",
          "size": 61006,
          "sha512": "4605d8a4123b4ad04b00cb85c5ca6ab8769478db5240f892e1de2e6c4265540fc23e45d8724f14c4cc78a30102cb0fe8e0aa1aea74738efb87b032adc537f429",
          "sha256": "47d6c71eb444f11ba59b1c260aa30868069be287ec2d8a9a1488767d15790e32",
          "sha1": "2cf756ecfd98bf984b555029681aacafb933a403",
          "md5": "b6cea4736042aa67e9361b267763ebb6"
        }
      ]
    }
  ]
}
