{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.12.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.12.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.12.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.12.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.12.0.jar",
          "url": "builder-8.12.0.jar",
          "size": 15798444,
          "sha512": "6a650dad0661fd42dd1d1d48edba315adbd2a399f63117c3c2fbbe944105cf44f7d561f9209706d8fcb9b0984f44148d383975c44d782af0cf06ded8e8ee4181",
          "sha256": "2763db5ef7236c7109412b125610bc9120ac1a59e2ea4c04746f0299284ed663",
          "sha1": "0e9309f368b4153b13bfcfe4da1036141f4db8cd",
          "md5": "d95b79bf71bac3078a77813d39881023"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.12.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.12.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.12.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.12.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.12.0"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.12.0"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.12.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.12.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.12.0"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.79"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.79"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.12.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.12.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.12.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.12.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.12.0.jar",
          "url": "builder-8.12.0.jar",
          "size": 15798444,
          "sha512": "6a650dad0661fd42dd1d1d48edba315adbd2a399f63117c3c2fbbe944105cf44f7d561f9209706d8fcb9b0984f44148d383975c44d782af0cf06ded8e8ee4181",
          "sha256": "2763db5ef7236c7109412b125610bc9120ac1a59e2ea4c04746f0299284ed663",
          "sha1": "0e9309f368b4153b13bfcfe4da1036141f4db8cd",
          "md5": "d95b79bf71bac3078a77813d39881023"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.12.0-javadoc.jar",
          "url": "builder-8.12.0-javadoc.jar",
          "size": 341755,
          "sha512": "7252b8aa7bc6366930dac99684b8030c176dfbe5e52715c3edd3d63a5d16ea0f322af35211fa26689c6ef05387a8d262fae658594a0a7b6338e0f90e87dcca64",
          "sha256": "e5eea903662faa9bfc95b5dc8278ebe9fd074fc29ccbe9365b7fbe63f02eb5cb",
          "sha1": "0ee794640c34ec30cd1c7e58de20b7d39603baf7",
          "md5": "e9fef1c7cc8e1cd5ea18fbbc2a06e3fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.12.0-sources.jar",
          "url": "builder-8.12.0-sources.jar",
          "size": 283760,
          "sha512": "51352a32243b624cb3039420989c2db5d41052fbab682e04ac15f0e752e49149de8b146fa6b3d4c74ccceec06fa9303234c045bb6362f4a38a137e47c451e8c9",
          "sha256": "e4956604821b7999880c49516e540a003de8508bc0a91261cf6c241abf276240",
          "sha1": "49bbda6c6c5fae5feda67d675292c5495175b58b",
          "md5": "09b60653df6ff0ade62cfa1599d926c6"
        }
      ]
    }
  ]
}
