{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "8.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.9.0.jar",
          "url": "gradle-api-8.9.0.jar",
          "size": 369538,
          "sha512": "e75afe3d0fab9b2fdbb526b0f438080100090daed836f904f77ecb7ed4b039a0df10c298712b8d712012d41c0e48179791114ae601025f6ced7bf4db9b37d073",
          "sha256": "def07a7589acd9a40c65e289d0788c0eaee29fe48968307ed7020959641fe547",
          "sha1": "25011ddb9f1839d567554984bb19ecb81b287fe0",
          "md5": "144cee7906af01c0f2d745ec5c4562cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.9.0.jar",
          "url": "gradle-api-8.9.0.jar",
          "size": 369538,
          "sha512": "e75afe3d0fab9b2fdbb526b0f438080100090daed836f904f77ecb7ed4b039a0df10c298712b8d712012d41c0e48179791114ae601025f6ced7bf4db9b37d073",
          "sha256": "def07a7589acd9a40c65e289d0788c0eaee29fe48968307ed7020959641fe547",
          "sha1": "25011ddb9f1839d567554984bb19ecb81b287fe0",
          "md5": "144cee7906af01c0f2d745ec5c4562cd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.9.0-javadoc.jar",
          "url": "gradle-api-8.9.0-javadoc.jar",
          "size": 151115,
          "sha512": "da16dfa08169b3c87b7efa3e79de4db58ad7938db27b937a33f0e3a767dad09442ad1d2f49e0a9d59693120b224a2b631f14b222657d3c3513879d35d6ef92ce",
          "sha256": "18fa70658fa3105f8da12e3aab9548e834d3d10da6061d6b8e3b9686227607c7",
          "sha1": "9de75a43373311b2c64663c535eb6ca85e9410a3",
          "md5": "f42b438f8bcf031759e750bcc2b25ec4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.9.0-sources.jar",
          "url": "gradle-api-8.9.0-sources.jar",
          "size": 359465,
          "sha512": "48a08cd80c064818ee257150857703ef87ffbb8e7765734f74543cdb33de0cc87a6d44fdd0dbd089939ccba80869b2bb27a4e225a69511d75cbff7c85e13c861",
          "sha256": "ff4a57f70206b80f9f468d396767346278ed4559b02f30c95ae1f0cc1d4f6651",
          "sha1": "df7587badf2bb36c08cc34b6a531223d8bd8a928",
          "md5": "20779833fbb55acdd29bce86eef3ebc0"
        }
      ]
    }
  ]
}
