{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-settings-api",
    "version": "8.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.12.0.jar",
          "url": "gradle-settings-api-8.12.0.jar",
          "size": 9953,
          "sha512": "b843078c3b65d25c423a48d078626634b6d3996821a8d9154a9a5fd0f4ac7f86ad0b0e14d1458d03e7247784727b294023cfb6fefa7f70078eeb2a3fc8be9973",
          "sha256": "0b1f3b04ebd7b17d87e893bcda1e579acf3837215eecc28c91da331c6cc6189d",
          "sha1": "573036710167ab5a01769f1310e931de26394286",
          "md5": "2d7be2e203a5bf2aea2fa7567936cd2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-settings-api-8.12.0.jar",
          "url": "gradle-settings-api-8.12.0.jar",
          "size": 9953,
          "sha512": "b843078c3b65d25c423a48d078626634b6d3996821a8d9154a9a5fd0f4ac7f86ad0b0e14d1458d03e7247784727b294023cfb6fefa7f70078eeb2a3fc8be9973",
          "sha256": "0b1f3b04ebd7b17d87e893bcda1e579acf3837215eecc28c91da331c6cc6189d",
          "sha1": "573036710167ab5a01769f1310e931de26394286",
          "md5": "2d7be2e203a5bf2aea2fa7567936cd2b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.12.0-javadoc.jar",
          "url": "gradle-settings-api-8.12.0-javadoc.jar",
          "size": 261,
          "sha512": "f83ab470e0fa389963b01fb07f273d8e2a9fbcfb2b7e32b64ac23a13b5517d6d689430013c8d4620cc390310a0dcf8a30ce48a73f3451568979a5fb2c425146b",
          "sha256": "84568a20f19d803680450604add23549f78c77f79eff1b29798942439818f697",
          "sha1": "7aa3c525f6881cd4f5a9738ccb43ec19aedbc9e5",
          "md5": "84c82503800cd6de37770c9bcc78e8ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.12.0-sources.jar",
          "url": "gradle-settings-api-8.12.0-sources.jar",
          "size": 9470,
          "sha512": "8124e3b79053e567a8550be6df9e632964207085539737d00ffa1070d7b2d78b63f23700828d9dd9f7a19f1d7e0edf3437e9e2d4a03ce96cd818407c57a7e039",
          "sha256": "de302f3c50a35eeb262bcc3a7a4d655762ff1f294d5b9395647d15f39927891e",
          "sha1": "b94f67a7b63b469a9d17fd9e5c7d1074e04a5e31",
          "md5": "607e8e1ab7bb8a9783901bce37f8a702"
        }
      ]
    }
  ]
}
