{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "atomicfu",
    "version": "0.17.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "5iukykv3u5beroqu6mvxxbrffm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "atomicfu-metadata-0.17.3-all.jar",
          "url": "atomicfu-0.17.3-all.jar",
          "size": 16048,
          "sha512": "a3e69e3b8416e71842921d439a45bce30bd00043e17923b5071a298c79f4914b1cb1faa8daa779cbc234b576aa54a3de4d816c2bd7e4c2712a119c357027c2b9",
          "sha256": "52fa54a8e4dee808c8fecf51b3924788e8b5576caaf27d6d60afa6580fad4af0",
          "sha1": "badc7fb54d8595ed814c866f67a695d69a672ba4",
          "md5": "4bff5ab8411d2ecb7de80f5e0f0aeac4"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "atomicfu-0.17.3.jar",
          "url": "atomicfu-0.17.3.jar",
          "size": 9299,
          "sha512": "34ea92f1655dad2190e7ed3ae4ca23118f951e94a76c9f4a0a4a670520125b015d8f95dcadd65940002812e6e6db1598ca1a0db6a9074ca243adb25dd13d2e89",
          "sha256": "7808fcf71febac85ff6e65ef145d338bc9044cc7841b22216a39c3cea881098c",
          "sha1": "a3146ed7217e7a94bb44354efb45931d624da065",
          "md5": "95bd3f10992ba8c7ec19d66d65b2ca98"
        }
      ]
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosarm32/0.17.3/atomicfu-iosarm32-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosarm32",
        "version": "0.17.3"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosarm32/0.17.3/atomicfu-iosarm32-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosarm32",
        "version": "0.17.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosarm64/0.17.3/atomicfu-iosarm64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosarm64",
        "version": "0.17.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosarm64/0.17.3/atomicfu-iosarm64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosarm64",
        "version": "0.17.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iossimulatorarm64/0.17.3/atomicfu-iossimulatorarm64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iossimulatorarm64",
        "version": "0.17.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iossimulatorarm64/0.17.3/atomicfu-iossimulatorarm64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iossimulatorarm64",
        "version": "0.17.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosx64/0.17.3/atomicfu-iosx64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosx64",
        "version": "0.17.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-iosx64/0.17.3/atomicfu-iosx64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-iosx64",
        "version": "0.17.3"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../atomicfu-js/0.17.3/atomicfu-js-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-js",
        "version": "0.17.3"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../atomicfu-js/0.17.3/atomicfu-js-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-js",
        "version": "0.17.3"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../atomicfu-js/0.17.3/atomicfu-js-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-js",
        "version": "0.17.3"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../atomicfu-js/0.17.3/atomicfu-js-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-js",
        "version": "0.17.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../atomicfu-jvm/0.17.3/atomicfu-jvm-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-jvm",
        "version": "0.17.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../atomicfu-jvm/0.17.3/atomicfu-jvm-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-jvm",
        "version": "0.17.3"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-linuxx64/0.17.3/atomicfu-linuxx64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-linuxx64",
        "version": "0.17.3"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosarm64/0.17.3/atomicfu-macosarm64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosarm64",
        "version": "0.17.3"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosarm64/0.17.3/atomicfu-macosarm64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosarm64",
        "version": "0.17.3"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosx64/0.17.3/atomicfu-macosx64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosx64",
        "version": "0.17.3"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-macosx64/0.17.3/atomicfu-macosx64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-macosx64",
        "version": "0.17.3"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-mingwx64/0.17.3/atomicfu-mingwx64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-mingwx64",
        "version": "0.17.3"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosarm64/0.17.3/atomicfu-tvosarm64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosarm64",
        "version": "0.17.3"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosarm64/0.17.3/atomicfu-tvosarm64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosarm64",
        "version": "0.17.3"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvossimulatorarm64/0.17.3/atomicfu-tvossimulatorarm64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvossimulatorarm64",
        "version": "0.17.3"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvossimulatorarm64/0.17.3/atomicfu-tvossimulatorarm64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvossimulatorarm64",
        "version": "0.17.3"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosx64/0.17.3/atomicfu-tvosx64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosx64",
        "version": "0.17.3"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-tvosx64/0.17.3/atomicfu-tvosx64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-tvosx64",
        "version": "0.17.3"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm32/0.17.3/atomicfu-watchosarm32-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm32",
        "version": "0.17.3"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm32/0.17.3/atomicfu-watchosarm32-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm32",
        "version": "0.17.3"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm64/0.17.3/atomicfu-watchosarm64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm64",
        "version": "0.17.3"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosarm64/0.17.3/atomicfu-watchosarm64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosarm64",
        "version": "0.17.3"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchossimulatorarm64/0.17.3/atomicfu-watchossimulatorarm64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchossimulatorarm64",
        "version": "0.17.3"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchossimulatorarm64/0.17.3/atomicfu-watchossimulatorarm64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchossimulatorarm64",
        "version": "0.17.3"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosx64/0.17.3/atomicfu-watchosx64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosx64",
        "version": "0.17.3"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosx64/0.17.3/atomicfu-watchosx64-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosx64",
        "version": "0.17.3"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosx86/0.17.3/atomicfu-watchosx86-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosx86",
        "version": "0.17.3"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../atomicfu-watchosx86/0.17.3/atomicfu-watchosx86-0.17.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "atomicfu-watchosx86",
        "version": "0.17.3"
      }
    }
  ]
}
