{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-gradle-plugin",
    "version": "2.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "14127284"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-gradle-plugin-2.8.1.jar",
          "url": "room-gradle-plugin-2.8.1.jar",
          "size": 79770,
          "sha512": "44d219f383e862c2f052a7f076d41a3ca6fd87274d6866dc5ae59cbb805cc43b048a978723d263ef7bd48b55f72235d96e3a19ebd52b58bb800c2e8e751df43c",
          "sha256": "d336461a5fea9fc6c2ab6aab991bfd8918c39f248286d7ca2ff69700b8e4851f",
          "sha1": "3f28d654bf30e354803b2d89f15fc227a799b325",
          "md5": "0d8c438cecf024008ded1eb41734d21c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-gradle-plugin-2.8.1.jar",
          "url": "room-gradle-plugin-2.8.1.jar",
          "size": 79770,
          "sha512": "44d219f383e862c2f052a7f076d41a3ca6fd87274d6866dc5ae59cbb805cc43b048a978723d263ef7bd48b55f72235d96e3a19ebd52b58bb800c2e8e751df43c",
          "sha256": "d336461a5fea9fc6c2ab6aab991bfd8918c39f248286d7ca2ff69700b8e4851f",
          "sha1": "3f28d654bf30e354803b2d89f15fc227a799b325",
          "md5": "0d8c438cecf024008ded1eb41734d21c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-gradle-plugin-2.8.1-sources.jar",
          "url": "room-gradle-plugin-2.8.1-sources.jar",
          "size": 20713,
          "sha512": "75b74e47e21c2e426c76fd1f9c95412663b49e69a81f601ea462e07ec8232bf97e662073913f4cac1dde099eed2a7ca0a8b1ed16b924c664ad99987e7bd120fd",
          "sha256": "891981788bef8d1ccb9dc4428afb68c862b84b86ae0260e4df0c5d50428cb3d3",
          "sha1": "7b164463a87ec431bd8f585b36cd8f0b482b1125",
          "md5": "1e266d4cbf7e92f755d84366599d31b2"
        }
      ]
    }
  ]
}