{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-gradle-plugin",
    "version": "2.1.10-1.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "symbol-processing-gradle-plugin-2.1.10-1.0.29.jar",
          "url": "symbol-processing-gradle-plugin-2.1.10-1.0.29.jar",
          "size": 198016,
          "sha512": "99c5e212eb83a47ac8ee164b80ebc1466108596bb79d301aff881ed76b2c9a57528f9c321404de51d08a7c42c5935309cedd54785ced30dc565b6584e9dd7165",
          "sha256": "773757b4dcbb900035953661cbfbab6ad04ba5f87b3b5367dc81182bd24dd0ad",
          "sha1": "f2ce22fc5a84687666a4bed87dafca5dd9769b8f",
          "md5": "4b6347a45829a9a26114becce9ac9bd0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.1.10-1.0.29"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-common-deps",
          "version": {
            "requires": "2.1.10-1.0.29"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-gradle-plugin-2.1.10-1.0.29.jar",
          "url": "symbol-processing-gradle-plugin-2.1.10-1.0.29.jar",
          "size": 198016,
          "sha512": "99c5e212eb83a47ac8ee164b80ebc1466108596bb79d301aff881ed76b2c9a57528f9c321404de51d08a7c42c5935309cedd54785ced30dc565b6584e9dd7165",
          "sha256": "773757b4dcbb900035953661cbfbab6ad04ba5f87b3b5367dc81182bd24dd0ad",
          "sha1": "f2ce22fc5a84687666a4bed87dafca5dd9769b8f",
          "md5": "4b6347a45829a9a26114becce9ac9bd0"
        }
      ]
    }
  ]
}
