{
  "formatVersion": "1.1",
  "component": {
    "group": "org.checkerframework",
    "module": "checker-qual",
    "version": "3.33.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "checker-qual-3.33.0.jar",
          "url": "checker-qual-3.33.0.jar",
          "size": 223979,
          "sha512": "049c446677b7b386f3fb501bf65e032bdf2b1b29a3f545848035fff2b683cd275380cf302e30eea641af7f0801f779bcda3d82a71d928e4176f564f796640a64",
          "sha256": "e316255bbfcd9fe50d165314b85abb2b33cb2a66a93c491db648e498a82c2de1",
          "sha1": "de2b60b62da487644fc11f734e73c8b0b431238f",
          "md5": "fc9418b779d9d57dcd52197006cbdb9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.33.0.jar",
          "url": "checker-qual-3.33.0.jar",
          "size": 223979,
          "sha512": "049c446677b7b386f3fb501bf65e032bdf2b1b29a3f545848035fff2b683cd275380cf302e30eea641af7f0801f779bcda3d82a71d928e4176f564f796640a64",
          "sha256": "e316255bbfcd9fe50d165314b85abb2b33cb2a66a93c491db648e498a82c2de1",
          "sha1": "de2b60b62da487644fc11f734e73c8b0b431238f",
          "md5": "fc9418b779d9d57dcd52197006cbdb9b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.33.0-javadoc.jar",
          "url": "checker-qual-3.33.0-javadoc.jar",
          "size": 987917,
          "sha512": "6716654f0017a2deb9d964bc5067e5a2b53d710f281aa71700dbc95f4effb8be7396de82b591fa2ac7d94bdb463053594de6686c5472aeaad424b1ff9b05dc05",
          "sha256": "c17b3d3a8c3963948fc98aef682c5406b91c87e8f164c22787f69c2f97b488f5",
          "sha1": "ae55718d8fcecd10b3693eff2137cd51e414273c",
          "md5": "e0a6c206e6131a1ae34f335afa328194"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.33.0-sources.jar",
          "url": "checker-qual-3.33.0-sources.jar",
          "size": 254531,
          "sha512": "5fa2dc0ab85460fa069306cd811496b4090e1fb563ed18758f0228b29bc103bf3475cf96c82d42963261729bf58938bfb18a16f07a9ee238aa7d924a0fd42e91",
          "sha256": "443fa6151982bb4c6ce62e2938f53660085b13a7dceb517202777b87d0dea2c7",
          "sha1": "ee4ecf6c55e3f2b05b839aa05c70f1298437ebe9",
          "md5": "8b3b07ec1a1e757f370c30d917d0a587"
        }
      ]
    }
  ]
}
