{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-emulator-control",
    "version": "31.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-emulator-control-31.8.1.jar",
          "url": "android-test-plugin-host-emulator-control-31.8.1.jar",
          "size": 22466,
          "sha512": "1a580b0587981b90ce0736fd35c62e25172c4b483607c10f0e1a91c55f7a4070aefdd4a4fc704fbd0d5d8f517350cc1e448c25fd9b55472de95a26f37514b6d1",
          "sha256": "78d6baf520e804dde6e1d07e528d14810c889ce60f058512e24d15bb3bfdcae1",
          "sha1": "e8393d6b2acf1781cafeb39e289ccb3f1c76cd5b",
          "md5": "ac1ae3dbedb2f70996901f6c1616ddd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-emulator-control-proto",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "com.android.tools.emulator",
          "module": "proto",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-driver-instrumentation",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-emulator-control-31.8.1.jar",
          "url": "android-test-plugin-host-emulator-control-31.8.1.jar",
          "size": 22466,
          "sha512": "1a580b0587981b90ce0736fd35c62e25172c4b483607c10f0e1a91c55f7a4070aefdd4a4fc704fbd0d5d8f517350cc1e448c25fd9b55472de95a26f37514b6d1",
          "sha256": "78d6baf520e804dde6e1d07e528d14810c889ce60f058512e24d15bb3bfdcae1",
          "sha1": "e8393d6b2acf1781cafeb39e289ccb3f1c76cd5b",
          "md5": "ac1ae3dbedb2f70996901f6c1616ddd7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-emulator-control-31.8.1-javadoc.jar",
          "url": "android-test-plugin-host-emulator-control-31.8.1-javadoc.jar",
          "size": 261,
          "sha512": "32f671aa2d5aa0f0e82ffb23e27cc02fed1053e9161b64eded61e65b63922e57d59256b6f87d0e4189bc51d840e0ff61aa283d953f3d2d384fe14edd9d06c70d",
          "sha256": "88de84a4054d799738ca140a0b53bcca7555644a3390e181ee8a41b4ecdaaaf6",
          "sha1": "87beea6e7ae4b85d8ee214e63bd7ae902febf5a1",
          "md5": "c8dea333e0b059e413788ffb229ab864"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-emulator-control-31.8.1-sources.jar",
          "url": "android-test-plugin-host-emulator-control-31.8.1-sources.jar",
          "size": 8383,
          "sha512": "9c39abfe0bb3292dffe8b7e421e2db82966dd95d2c1ea5ba71226b60a1b1029902a334d33d4a1783bb2636a38d7d876dbf95c0f06ec2a9228824dc305be19dc8",
          "sha256": "fd702fd69588acd4d04c48ee0345643fff8c65b99432f08e730fb5b625f0f0f6",
          "sha1": "898a98f47938e6e44cba707da0b4a7196a0c83b0",
          "md5": "a47fca2da44b9aed3b490bf6d5ae7f30"
        }
      ]
    }
  ]
}
