{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.8.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.8.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.8.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.8.1.jar",
          "url": "builder-8.8.1.jar",
          "size": 15228746,
          "sha512": "ec13dae20e611aa8521a7c8c926bb8f1b0c38d50eae15f70db4334c6a9508fcff71631473423fbcc9b8e59db6a5f8b6ba092f4d000edf7df4053434e4d23b343",
          "sha256": "c702d45209e754936a3d5fa482519e8e811e01b359e624d207218a2043cd4bb6",
          "sha1": "bfb7a4dc4eb2d0d8bbbf0ed03c75c4662f7eb612",
          "md5": "8d55bcfcb124ee614f246e94dc1119ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.8.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.8.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.8.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.8.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.8.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.8.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.8.1.jar",
          "url": "builder-8.8.1.jar",
          "size": 15228746,
          "sha512": "ec13dae20e611aa8521a7c8c926bb8f1b0c38d50eae15f70db4334c6a9508fcff71631473423fbcc9b8e59db6a5f8b6ba092f4d000edf7df4053434e4d23b343",
          "sha256": "c702d45209e754936a3d5fa482519e8e811e01b359e624d207218a2043cd4bb6",
          "sha1": "bfb7a4dc4eb2d0d8bbbf0ed03c75c4662f7eb612",
          "md5": "8d55bcfcb124ee614f246e94dc1119ff"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.8.1-javadoc.jar",
          "url": "builder-8.8.1-javadoc.jar",
          "size": 345928,
          "sha512": "54702cca358a21510c1e648b3da430ee70fad8903a9aa0c033808160c92a7374e8d775197d12e3ff01e8970e7b05ae7ee6d925986f3121cd7925f10d1bb609d2",
          "sha256": "c9cd98c282856e8c008416571d2ec8e50f485fb4857b8555b85957c66ed28c95",
          "sha1": "1838a635c827ed8d755998de73869f11a589f6dd",
          "md5": "2845a98d63606bdf046ef73205daed55"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.8.1-sources.jar",
          "url": "builder-8.8.1-sources.jar",
          "size": 284440,
          "sha512": "491596554ec100942d5d9db05b70d76091148d875f11cbda8b8b99c0fed853fd0d39dd5c1934dc5ab00ac963d3fa42e51351dfb0df3516349d141ddc7d6f5ae2",
          "sha256": "fef1595374a9f9aa1901c0bc81321d4a19c0ee925347737f007022040600ccfe",
          "sha1": "2e3cd91086e5434218c0f56f66acf4f7a9e3e030",
          "md5": "73531747bff76036f160e6a5bc273488"
        }
      ]
    }
  ]
}
