{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-migration",
    "version": "2.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-migration-2.6.1.jar",
          "url": "room-migration-2.6.1.jar",
          "size": 44029,
          "sha512": "9dafe6b3dc89abb5875d5fe65cd2cd0e23c18e9365e6394c5d6fe3576589eac73c28c6219aea2d7485354e2cb3163923656ea4222dc40faef6c96a35bd2669f3",
          "sha256": "0dd380522b6d55ab23902de873effc356e9a8e4fb8bd94dde963222d420a89b9",
          "sha1": "8d8218e4ccfe9b34485619a8ca68f8760840301d",
          "md5": "8cdffa270cbf342958e7ae542e73ad0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-migration-2.6.1.jar",
          "url": "room-migration-2.6.1.jar",
          "size": 44029,
          "sha512": "9dafe6b3dc89abb5875d5fe65cd2cd0e23c18e9365e6394c5d6fe3576589eac73c28c6219aea2d7485354e2cb3163923656ea4222dc40faef6c96a35bd2669f3",
          "sha256": "0dd380522b6d55ab23902de873effc356e9a8e4fb8bd94dde963222d420a89b9",
          "sha1": "8d8218e4ccfe9b34485619a8ca68f8760840301d",
          "md5": "8cdffa270cbf342958e7ae542e73ad0a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-migration-2.6.1-sources.jar",
          "url": "room-migration-2.6.1-sources.jar",
          "size": 16556,
          "sha512": "acf366265e23303ffa6555d0d33c382105bb70345eb1fa7b75cad1fc8207fd652f66e087797e24bd114a1f32e05f41533e1e8ffd1d27396ecf93c5bea0d10760",
          "sha256": "541623f23c79b96cae3efee7d28974bc5f1e9b441e49c0a3495112189bd7001e",
          "sha1": "af5f6b81b738cb220c1bc5aff4d439b83aa8760f",
          "md5": "6d99cf715db1b2b4e3b6212a2630ea3e"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-migration-2.6.1-versionMetadata.json",
          "url": "room-migration-2.6.1-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}