{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aaptcompiler",
    "version": "8.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aaptcompiler-8.12.0.jar",
          "url": "aaptcompiler-8.12.0.jar",
          "size": 496115,
          "sha512": "8f3c8bb0ea69126a5b89f7007f18799d7e6f3733414df3e020622b41ebcfca8df33a96877e67c1eba73f66abb2fadf611aca7bcf35a8b1e605e1f9a77ff7c98c",
          "sha256": "92fc469e1e5afed1ec0f93d40148dfe37cf0c0f801c83799715881a9f0e1b270",
          "sha1": "461de28e32bf64e46224c29598c69547ec1208c1",
          "md5": "a534c6b5542050c7cd8f0e2a269c7c89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "8.12.0-13700139"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.12.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.12.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "aaptcompiler-8.12.0.jar",
          "url": "aaptcompiler-8.12.0.jar",
          "size": 496115,
          "sha512": "8f3c8bb0ea69126a5b89f7007f18799d7e6f3733414df3e020622b41ebcfca8df33a96877e67c1eba73f66abb2fadf611aca7bcf35a8b1e605e1f9a77ff7c98c",
          "sha256": "92fc469e1e5afed1ec0f93d40148dfe37cf0c0f801c83799715881a9f0e1b270",
          "sha1": "461de28e32bf64e46224c29598c69547ec1208c1",
          "md5": "a534c6b5542050c7cd8f0e2a269c7c89"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.12.0-javadoc.jar",
          "url": "aaptcompiler-8.12.0-javadoc.jar",
          "size": 81065,
          "sha512": "2175961bfc098eb769d0c302047e50e93b740ed04236dd49d8ef5a530e46309ad40aec0dd016022dbee9a44a16789575b7605eead854ea707f2413afeaf063dd",
          "sha256": "ed2752a02392651809613f657df1ae7ff81e952efd392b370cc2b42de305c1a2",
          "sha1": "aedae1846ed5097bff7d743ab2fb1eabad29c88e",
          "md5": "8a800b97173cef966b7dec25a23f5f87"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.12.0-sources.jar",
          "url": "aaptcompiler-8.12.0-sources.jar",
          "size": 152981,
          "sha512": "90dc00ef13255217e2923d40c77fe6cd35f0b8561538673a6a16fb0d12182fb3a7f072b7a07c631e11eebd26be59a783675439e2d2bef6b5d8022bbdbee4dd48",
          "sha256": "b050a0fc6d1ef623eb0f9acbb84fd9cee55d6831be6b7fb5fcb4c2c168cb91eb",
          "sha1": "3f0ba2353277ee67b92ed090b55a7731bbaa817b",
          "md5": "2c72b73c489faa09418b4633b4b8dbc0"
        }
      ]
    }
  ]
}
