{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle",
    "version": "8.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "8.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-8.9.0.jar",
          "url": "gradle-8.9.0.jar",
          "size": 13022046,
          "sha512": "97b0bc99c96d383745962c61fcfff314b9f1331c50434e0e3216a3628cd03f2ce27233e996ce035fae6dc1bdf54eff677c998cfd67000bfd99d99e62217cc9c0",
          "sha256": "5622311d167577317429ec057a626b191e721460a6aea5e2260812721052c81b",
          "sha1": "d998b94d7f98b902a4ce05031d19dd078ca88656",
          "md5": "f89b1ec8337bcc929cc561945b84a3bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-settings-api",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "repository",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "8.9.0-12782657"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "aaptcompiler",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "crash",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-model",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-typedef-remover",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-compiler-common",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-device-provider-ddmlib-proto",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-device-provider-gradle-proto",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-device-provider-profile-proto",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-additional-test-output-proto",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-coverage-proto",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-emulator-control-proto",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-logcat-proto",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-apk-installer-proto",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-retention-proto",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-result-listener-gradle-proto",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "transform-api",
          "version": {
            "requires": "2.0.0-deprecated-use-gradle-api"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.79"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "bundletool",
          "version": {
            "requires": "1.17.2"
          }
        },
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-core",
          "version": {
            "requires": "1.0.0-beta10"
          }
        },
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-processor",
          "version": {
            "requires": "1.0.0-beta10"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-core",
          "version": {
            "requires": "1.57.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty",
          "version": {
            "requires": "1.57.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.57.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.57.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "core-proto",
          "version": {
            "requires": "0.0.9-alpha03"
          }
        },
        {
          "group": "com.google.flatbuffers",
          "module": "flatbuffers-java",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite-metadata",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "8.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-8.9.0.jar",
          "url": "gradle-8.9.0.jar",
          "size": 13022046,
          "sha512": "97b0bc99c96d383745962c61fcfff314b9f1331c50434e0e3216a3628cd03f2ce27233e996ce035fae6dc1bdf54eff677c998cfd67000bfd99d99e62217cc9c0",
          "sha256": "5622311d167577317429ec057a626b191e721460a6aea5e2260812721052c81b",
          "sha1": "d998b94d7f98b902a4ce05031d19dd078ca88656",
          "md5": "f89b1ec8337bcc929cc561945b84a3bb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-8.9.0-javadoc.jar",
          "url": "gradle-8.9.0-javadoc.jar",
          "size": 633111,
          "sha512": "6989351c779da8d1366b7412f11ba8f719091f2a5d819414912f6a3bdb111e04784470e5bf8e94d2d2aabe2a300f67fcda1a4bcde806c351648442981c36f4dd",
          "sha256": "5dbe5a1c40e3af2fcffa35be71f87f5268637c3e8c7731141f872379d6706ef1",
          "sha1": "d3a5d42099a761d944a2caae8cafc93cfc258664",
          "md5": "88f107e7bf998e8b2f97a6eb472f315a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-8.9.0-sources.jar",
          "url": "gradle-8.9.0-sources.jar",
          "size": 3832477,
          "sha512": "afa648109e3392e0529b2b1b00be5485a7c73b110b098814aed59537e54b4bb6a055e4f905826656abeda2ecf06120498b49f49b3b11f50bfeecb96f43498728",
          "sha256": "9bf8484264b7ad8faf28050d4acd0285d22367780fc2af815339d3ef5d8048ae",
          "sha1": "49ef4d0ba4b9390aedef509fb636e43cfa1abe81",
          "md5": "4ab3da31981ec624081883db7e11d37c"
        }
      ]
    }
  ]
}
