{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "manifest-merger",
    "version": "31.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "manifest-merger-31.9.0.jar",
          "url": "manifest-merger-31.9.0.jar",
          "size": 258837,
          "sha512": "a1fe866cb494af201ef0eb49e1ad6514dd16576aa9d52f32a80e771a8b470ba2cefeca3a1ffb32c80f389ff298c21c64dd30d0c0617b40531ca75aac6560dfc7",
          "sha256": "fb6a049e4ee425a4f558ecebd94d71e1225946cb92888377b56b852d046e263a",
          "sha1": "e714dce09b04f56f6378de0999a12c3a689d043b",
          "md5": "c39bb11a733c4134a828c7b29cf1eef7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "manifest-merger-31.9.0.jar",
          "url": "manifest-merger-31.9.0.jar",
          "size": 258837,
          "sha512": "a1fe866cb494af201ef0eb49e1ad6514dd16576aa9d52f32a80e771a8b470ba2cefeca3a1ffb32c80f389ff298c21c64dd30d0c0617b40531ca75aac6560dfc7",
          "sha256": "fb6a049e4ee425a4f558ecebd94d71e1225946cb92888377b56b852d046e263a",
          "sha1": "e714dce09b04f56f6378de0999a12c3a689d043b",
          "md5": "c39bb11a733c4134a828c7b29cf1eef7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.9.0-javadoc.jar",
          "url": "manifest-merger-31.9.0-javadoc.jar",
          "size": 275772,
          "sha512": "48495ac8d3d99b6e14f61e241a47578b43f54942ffe5c589702269ee87c5f96c2f415b5e20beadaddd35c0933f2079395f69615c9aaf759c17b64f140db6662c",
          "sha256": "9c388787b3bd251759f917da033cc50c4badac84b250b6b0994ccf521f15ae62",
          "sha1": "948635e17e1bbe7df2e161befeb304ee77d4a074",
          "md5": "351af26cc96fb131ed3bb11800236d44"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.9.0-sources.jar",
          "url": "manifest-merger-31.9.0-sources.jar",
          "size": 236511,
          "sha512": "d1cfabb0cc9c736ec7ae636fcb938a42772ee1b2a94dc9f5bb335d3f710735a2f9497837eafaf170e7b6dcd72687eb62a62f98d82b223f449f1bb7a3437e1a1c",
          "sha256": "776d05d8c31a0781f2440e12721a20535380198f95811bb0d9d738bc6acbaf4f",
          "sha1": "4b325a3adf5f62aaab4fd3ac9f9f5d784705b442",
          "md5": "97187ff0184f40082ae374a46b385323"
        }
      ]
    }
  ]
}
