{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-model",
    "version": "8.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "builder-model-8.9.1.jar",
          "url": "builder-model-8.9.1.jar",
          "size": 125289,
          "sha512": "eb59df3d6a6fc3cd04ae4834643820f431a27332294b0f782b177797e113916f9adafe209179675caf2188a754c4385bd9a0ee0d323eb597399ad53ea632dbbe",
          "sha256": "928eb46387b05d3ee00e2a4d87339c0657059947af249dfd71f73fd8b82453ef",
          "sha1": "0a749b3ff28c2bf555e7168f0f2ded564ac07dd4",
          "md5": "0ee0ad76d25e194db1eb361d5d91279f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "31.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-model-8.9.1.jar",
          "url": "builder-model-8.9.1.jar",
          "size": 125289,
          "sha512": "eb59df3d6a6fc3cd04ae4834643820f431a27332294b0f782b177797e113916f9adafe209179675caf2188a754c4385bd9a0ee0d323eb597399ad53ea632dbbe",
          "sha256": "928eb46387b05d3ee00e2a4d87339c0657059947af249dfd71f73fd8b82453ef",
          "sha1": "0a749b3ff28c2bf555e7168f0f2ded564ac07dd4",
          "md5": "0ee0ad76d25e194db1eb361d5d91279f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.9.1-javadoc.jar",
          "url": "builder-model-8.9.1-javadoc.jar",
          "size": 291422,
          "sha512": "79b9312c95cd92633711cc22e9782ed053b1afb481ff1632a9b668dc1e7747a01896eeaf28df07030380f4197480889269cd637a5e20e63a37e9a447e8b52d33",
          "sha256": "15dcd96b8349b1d002214b32c800edfa91a680d4c5d6ce0ab31dc20cfbd469e2",
          "sha1": "1055ae25736badd947dd811e66a6eef3c1cda99e",
          "md5": "3814cdf642451546a505ccf4f0b8417c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.9.1-sources.jar",
          "url": "builder-model-8.9.1-sources.jar",
          "size": 145585,
          "sha512": "b3a23b8a5bd4c6758c26f8ac669c1439b14cc4bc91e8975dd23543b5ef7e549018e0b3b44bbd340b2180cafb8aae113e5a2b111195461d2dbb57e2f7922f1393",
          "sha256": "6af204437270aad91dbc08c9274d0bdf6cea3a273ed38d92cce9e687e1fbf67b",
          "sha1": "92c23d3889ea7284ce8b348a2e79cfe6ccc61e1a",
          "md5": "e3b11c12c20cefd9c6d119c156812ba8"
        }
      ]
    }
  ]
}
