{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-settings-api",
    "version": "8.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.11.0.jar",
          "url": "gradle-settings-api-8.11.0.jar",
          "size": 9953,
          "sha512": "397727363d7960b4acba53f3c57546558ba1b65a063fc239d2684e1a1b0e4cbbc30b813bffe3a0af3fe59778460e986c41f18bd17833bb9cced269ded3d1d2fa",
          "sha256": "e4baee41e1ff6717567bbe604234c7d768811f4da07f2eb99b8e9ae8c134f823",
          "sha1": "b549c6c2b60cfc44e6251c2df2821dc912b7cb13",
          "md5": "6b083d47ca43d36acade7dbdb69195ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-settings-api-8.11.0.jar",
          "url": "gradle-settings-api-8.11.0.jar",
          "size": 9953,
          "sha512": "397727363d7960b4acba53f3c57546558ba1b65a063fc239d2684e1a1b0e4cbbc30b813bffe3a0af3fe59778460e986c41f18bd17833bb9cced269ded3d1d2fa",
          "sha256": "e4baee41e1ff6717567bbe604234c7d768811f4da07f2eb99b8e9ae8c134f823",
          "sha1": "b549c6c2b60cfc44e6251c2df2821dc912b7cb13",
          "md5": "6b083d47ca43d36acade7dbdb69195ad"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.11.0-javadoc.jar",
          "url": "gradle-settings-api-8.11.0-javadoc.jar",
          "size": 261,
          "sha512": "7a1f18aff955e225523a59d814cc5110a99fa6b477041033c3c7b60549590259708852a3840b947ecbe2c1d47eb70640fd7a34b98e9cfeabc37af5efa9a33cf5",
          "sha256": "9bd4c0b2f3862e0a3070dd2fdf00560ca8ad09e2f96a0ec6c04a40be59170d9a",
          "sha1": "3d27046346279d80f304b2e4e5eac5ee90a749c3",
          "md5": "ebe11900ee38b1e2b1374f206b89df48"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.11.0-sources.jar",
          "url": "gradle-settings-api-8.11.0-sources.jar",
          "size": 9470,
          "sha512": "6ad49e2d070c74477bbb96dda2d1185f0da58e9b520f791cc4a6beaed913c5f3f8f259527d31c823901201f8e9b544b388d88d4ba1230e3c7ad8ae76c76cee9e",
          "sha256": "2569abafdb309f2c1df30ec75314d38290cd5c1b6f7fdcaa0a4ae993cce6d235",
          "sha1": "4745db390beb809e1ef58213803b276f70193ab0",
          "md5": "5888520484713c51d0cd98d8c1749955"
        }
      ]
    }
  ]
}
