{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aaptcompiler",
    "version": "8.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aaptcompiler-8.11.0.jar",
          "url": "aaptcompiler-8.11.0.jar",
          "size": 496115,
          "sha512": "2cf990ec8b3651bfec35012835e9d4cc18225ac8e64355b8d61bf4947f69a879bb7516777c10467265922366d32dcdc0e14cbf46c2acd64430e7cda3c17d0a1e",
          "sha256": "5d767de58f887075c1101622bcdcdec1ea015d25c84011c3f6f89f210282fa69",
          "sha1": "97de99babdec6cc3f84442691a3a68b315a7f174",
          "md5": "e0d2f38d184323a08257283f07a9c594"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "8.11.0-12782657"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.11.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.11.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "aaptcompiler-8.11.0.jar",
          "url": "aaptcompiler-8.11.0.jar",
          "size": 496115,
          "sha512": "2cf990ec8b3651bfec35012835e9d4cc18225ac8e64355b8d61bf4947f69a879bb7516777c10467265922366d32dcdc0e14cbf46c2acd64430e7cda3c17d0a1e",
          "sha256": "5d767de58f887075c1101622bcdcdec1ea015d25c84011c3f6f89f210282fa69",
          "sha1": "97de99babdec6cc3f84442691a3a68b315a7f174",
          "md5": "e0d2f38d184323a08257283f07a9c594"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.11.0-javadoc.jar",
          "url": "aaptcompiler-8.11.0-javadoc.jar",
          "size": 81065,
          "sha512": "c935c7e41bc1e5beefc3f44e566af2ba4207ab47f68ab21ebc77f42cdd9d8fc1699b2a7d51695be90fd749da2ca7c0d85b9e232799a0acb8078b519fb4c93645",
          "sha256": "c6b7c2578fae0a83196ef22fa0e0b2e99fcd3a92ec66d5a9dcc8a4b2d9a2c5a3",
          "sha1": "bd21e52921cebae365c22f6dbbe7598d1cd06444",
          "md5": "e4a897782c1842de1b19c147ddbd86fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.11.0-sources.jar",
          "url": "aaptcompiler-8.11.0-sources.jar",
          "size": 152981,
          "sha512": "984852cd53427197710bee8382ab58ca148de0a458d857a8b03d4edd0d3539e5ed537075ff502cda6c9a82452047ee9881491232b75ad16146c05186bdc54750",
          "sha256": "9aec88126a546c8870c1831bf25fe5c428e9fddd0bf1ec8b6b0b9c5b051e569b",
          "sha1": "90da447d014ee6dcb9e62d4a1c222c35321683d8",
          "md5": "d3dc9af17fca4995cb49555c5e5371c7"
        }
      ]
    }
  ]
}
