{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aapt2-proto",
    "version": "8.8.2-12006047",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aapt2-proto-8.8.2-12006047.jar",
          "url": "aapt2-proto-8.8.2-12006047.jar",
          "size": 711278,
          "sha512": "3d69e797ed9d4467744f7f6b5976ab3cc1d424872b5eb6162df9bd313633277a632654ed53f274657d443974b97eba63b31c529e932f7f2b3b970a6d31dd99dd",
          "sha256": "d71f3a999203e6c97d37f810197e107c7237253f8429a007ec4d4438ffad6f00",
          "sha1": "9faa69264bf08e246c2ae7566bd07a1e7ea4e606",
          "md5": "9931cac1d45105f2bdf7befbf68d677a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        }
      ],
      "files": [
        {
          "name": "aapt2-proto-8.8.2-12006047.jar",
          "url": "aapt2-proto-8.8.2-12006047.jar",
          "size": 711278,
          "sha512": "3d69e797ed9d4467744f7f6b5976ab3cc1d424872b5eb6162df9bd313633277a632654ed53f274657d443974b97eba63b31c529e932f7f2b3b970a6d31dd99dd",
          "sha256": "d71f3a999203e6c97d37f810197e107c7237253f8429a007ec4d4438ffad6f00",
          "sha1": "9faa69264bf08e246c2ae7566bd07a1e7ea4e606",
          "md5": "9931cac1d45105f2bdf7befbf68d677a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aapt2-proto-8.8.2-12006047-javadoc.jar",
          "url": "aapt2-proto-8.8.2-12006047-javadoc.jar",
          "size": 1063738,
          "sha512": "0ef1d3468441766656690b618de85f37b7382ffc7835d681d305c8e1c65cbaeb12e668f0d1aa6361abd3e9bd50b37d05bfab6a3a67ae94579ba28ec4356cf42a",
          "sha256": "2a64a7d56b9ebef8a58a16f4c0fed279f3cead76f8ab8aa661b4b623c33475ad",
          "sha1": "a8dc2e84fab1d41fa0e09dd5753bc3b5c74d2d9b",
          "md5": "d1485d29653c9c7ca97a3ae3dea5825c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aapt2-proto-8.8.2-12006047-sources.jar",
          "url": "aapt2-proto-8.8.2-12006047-sources.jar",
          "size": 394856,
          "sha512": "c1dffabe84926d1c9148651876bc370b8228ce14866eaa4fa94cc98f8919a6f9b295312c513b602b0f8a00a0b39f5837378027f624acd7115bce4e5126db025f",
          "sha256": "40f6996629e55c3522e257152b14b982e1c0ff7fdedadc5e204e5b6ae0a538f7",
          "sha1": "322a03db79d0ea8f0cd9d4002b3096d12b65d559",
          "md5": "da8d2228f0d5ff7f613faae5dbfe14e5"
        }
      ]
    }
  ]
}
