{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup",
    "module": "kotlinpoet",
    "version": "1.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinpoet-metadata-1.17.0.jar",
          "url": "kotlinpoet-1.17.0.jar",
          "size": 717,
          "sha512": "52e96a7c09c44f3e9a36f80bc0f8868ec6262b8f60f1a155fcf9e8269363644db727559c000b38caefdbeeb48d21dff856ee64a68617aed2cdd3f334434d34f4",
          "sha256": "78c3aff14ff7d24991b9fd8b21a8e4a142d290b52ab61102c1bf6d48badc6765",
          "sha1": "77a0163089a1c1c99c7022cfe6b41eac9f4f8c5b",
          "md5": "55bb2a806a3fe3a3b0ff64ae317f18ec"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlinpoet-kotlin-1.17.0-sources.jar",
          "url": "kotlinpoet-1.17.0-sources.jar",
          "size": 308,
          "sha512": "4631a4ec0efaccdf04ad54c3ab1cb34d7d187e56a7da82c30adcd9a9d9b39fbb036238b00283efb6d39c93b31e304a20065c184677277fe22f7ff25d260b185c",
          "sha256": "7c321d53dbff96f00d747464020e29b9caa2a46b291875eea36cc14e5de51324",
          "sha1": "0da7ade0d754e68bbae81bf94d62bdc1a6110967",
          "md5": "0dd5316b2b56e12cf7b736e9307f45ac"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinpoet-jvm/1.17.0/kotlinpoet-jvm-1.17.0.module",
        "group": "com.squareup",
        "module": "kotlinpoet-jvm",
        "version": "1.17.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinpoet-jvm/1.17.0/kotlinpoet-jvm-1.17.0.module",
        "group": "com.squareup",
        "module": "kotlinpoet-jvm",
        "version": "1.17.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinpoet-jvm/1.17.0/kotlinpoet-jvm-1.17.0.module",
        "group": "com.squareup",
        "module": "kotlinpoet-jvm",
        "version": "1.17.0"
      }
    }
  ]
}
