{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "8.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.12.2.jar",
          "url": "gradle-api-8.12.2.jar",
          "size": 390690,
          "sha512": "a021d4872e0f11196b74c2bddc95a8a5d1b3f6c9431f317247153b4785cd6bcc1eff8e47fdd4ff16219fa1fc7f7ad3854149ad897e220fee1bd791e421f04605",
          "sha256": "2b930ce6e9fd45167bbe81f83b10c75f7fea63b86a634cd1c56c38d64bf30406",
          "sha1": "ea254f1fe4d13434c35b0064eb67ef4f82b10c52",
          "md5": "c17d19e59d9b45a43eb88731cb5530da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.12.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.12.2.jar",
          "url": "gradle-api-8.12.2.jar",
          "size": 390690,
          "sha512": "a021d4872e0f11196b74c2bddc95a8a5d1b3f6c9431f317247153b4785cd6bcc1eff8e47fdd4ff16219fa1fc7f7ad3854149ad897e220fee1bd791e421f04605",
          "sha256": "2b930ce6e9fd45167bbe81f83b10c75f7fea63b86a634cd1c56c38d64bf30406",
          "sha1": "ea254f1fe4d13434c35b0064eb67ef4f82b10c52",
          "md5": "c17d19e59d9b45a43eb88731cb5530da"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.12.2-javadoc.jar",
          "url": "gradle-api-8.12.2-javadoc.jar",
          "size": 151115,
          "sha512": "1ded51c3284db2af5d1735591b6af72b4bd552cb0949d8ceca1f405ca4bdcb5a81941d054934921cbc77e74ffdacab00bcc102214b227b787911ed486bf1628b",
          "sha256": "c97a3e6e01883d74498b4c89ddba78a1983f73a9d040651143765d0bc2374779",
          "sha1": "9ef96bdb60c797cdb730f13562f9c7858d518ad0",
          "md5": "44d814fad153d854161f015f7c60ae84"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.12.2-sources.jar",
          "url": "gradle-api-8.12.2-sources.jar",
          "size": 381050,
          "sha512": "b43b60f4bb514ce4d07a4fded722e82ee543be61bca630acb5459560936230a53e93c3d3e8453da1e51969179172d2053bbdee7264b31a1db9fd24851358d784",
          "sha256": "55634c7cf67fc582fc6d5058a5f044a69e11400c4af8abc968397f60c34d821f",
          "sha1": "be9c8e98f57353c4bca9cf76977148ba05eeb5d4",
          "md5": "c0a822930a3c96db09ae38cd46990be7"
        }
      ]
    }
  ]
}
