{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-gradle-plugin",
    "version": "2.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13652230"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-gradle-plugin-2.7.2.jar",
          "url": "room-gradle-plugin-2.7.2.jar",
          "size": 105633,
          "sha512": "0b6f6872e777a4a319a12e96d331b84d7ef9c852fab596811dfb38c0180ff57ccd7faeb7b3a4446579d1d74daa60acfe794cfed3371281ab982a3ea798e4f5cf",
          "sha256": "870b02f5090df4ae3edc05cfb8163b929ce7a7693d7c44a9d58ed5d03d2728ac",
          "sha1": "6ae761051f62df5e868cd629eba7d14bc009472f",
          "md5": "184740476aa5d685e1bb62e187a86722"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-gradle-plugin-2.7.2.jar",
          "url": "room-gradle-plugin-2.7.2.jar",
          "size": 105633,
          "sha512": "0b6f6872e777a4a319a12e96d331b84d7ef9c852fab596811dfb38c0180ff57ccd7faeb7b3a4446579d1d74daa60acfe794cfed3371281ab982a3ea798e4f5cf",
          "sha256": "870b02f5090df4ae3edc05cfb8163b929ce7a7693d7c44a9d58ed5d03d2728ac",
          "sha1": "6ae761051f62df5e868cd629eba7d14bc009472f",
          "md5": "184740476aa5d685e1bb62e187a86722"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-gradle-plugin is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-gradle-plugin-2.7.2-sources.jar",
          "url": "room-gradle-plugin-2.7.2-sources.jar",
          "size": 20583,
          "sha512": "aef06bcad5caf8c14ee89d39199ddad8a85e251851aa0e109f297291cd3e61168aa1bb3805186cd9e2c7db864713171239da8f7b1a5063ab0c58d09cef280e4a",
          "sha256": "4321e0854ac4f0ad65550e61af1cdd9fb48cd2c172fbdf6af82bd830671faa5c",
          "sha1": "1534096858972844688e7077bfc046408322207d",
          "md5": "911cdd1e0671d26b5acf8ff73c09b075"
        }
      ]
    }
  ]
}