{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-additional-test-output",
    "version": "31.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-additional-test-output-31.13.0.jar",
          "url": "android-test-plugin-host-additional-test-output-31.13.0.jar",
          "size": 29982,
          "sha512": "8a4a1b158f2aa07f81b2a410d470d1d7e251333b8b428751be2835d6caaae5284c2c393b83e61df3c0aafa2f95938f42ef842a3e2d639f4419da1e5085f04a86",
          "sha256": "fc5f224db1b1d21642339dff08e3bcc9bb3b6753c4e6a7d5e750769a7cbbbeb4",
          "sha1": "33fbcd2edb9244324b5a5d8cf90968d6674ea1c8",
          "md5": "8288e6b3af5723c77757ed644134a9b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.13.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "utp-common",
          "version": {
            "requires": "31.13.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-additional-test-output-proto",
          "version": {
            "requires": "31.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-additional-test-output-31.13.0.jar",
          "url": "android-test-plugin-host-additional-test-output-31.13.0.jar",
          "size": 29982,
          "sha512": "8a4a1b158f2aa07f81b2a410d470d1d7e251333b8b428751be2835d6caaae5284c2c393b83e61df3c0aafa2f95938f42ef842a3e2d639f4419da1e5085f04a86",
          "sha256": "fc5f224db1b1d21642339dff08e3bcc9bb3b6753c4e6a7d5e750769a7cbbbeb4",
          "sha1": "33fbcd2edb9244324b5a5d8cf90968d6674ea1c8",
          "md5": "8288e6b3af5723c77757ed644134a9b8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-additional-test-output-31.13.0-javadoc.jar",
          "url": "android-test-plugin-host-additional-test-output-31.13.0-javadoc.jar",
          "size": 261,
          "sha512": "45dada7d95416045ad218ad364f66aacc64bd07ea6ed95539dc652bf3c0977040e88a4a9b44c8653ba929ce4fbd11be1e6a21ac01dd937c8c6e797b2e824179f",
          "sha256": "cebceba5b60e48f34a1a416b857f8eaba5eaa30c3c0d69794f7f0c9356b2fea9",
          "sha1": "dcac025ba8756b080643bfa3fb7003ae0ac151dd",
          "md5": "817c65f00575dcab61f3a1e140c862b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-additional-test-output-31.13.0-sources.jar",
          "url": "android-test-plugin-host-additional-test-output-31.13.0-sources.jar",
          "size": 6676,
          "sha512": "81f809bcdcfcf028b3edc73f25fe7e58fc122ab2fcb866c361fdfa12be706bace42ca427f272c95186a50d2aa94d4be1b1049853511e50685ce0f3f471aa9d7f",
          "sha256": "91cf60cde409b4550b53e2a685d19ec1b9a66fe273d8b015f17c98992fc560ae",
          "sha1": "39e57863a2154d7ca020ede15eb2d7b0753c7251",
          "md5": "e602f133e9ab88544b01f339d6060baf"
        }
      ]
    }
  ]
}
