{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-runtime",
    "version": "8.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.12.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.12.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-runtime-8.12.2.aar",
          "url": "databinding-runtime-8.12.2.aar",
          "size": 61017,
          "sha512": "ec4c93517b75d4463a3692643e746ba5a840bdc0cb7a1c1d1cf75320263a640720f99fc3e7a95f94c71ba5e826c8bb6ec527cc0ec16983b764b37660d02438fb",
          "sha256": "a3f48e1caa7a1b5706432c55cfb1e9f7179048e4f4e28449ab0280bf63f19214",
          "sha1": "e22a6f2a3ffc3b258c2127584982ba7de5e05f68",
          "md5": "8c0600f3f8c7532ef63787b31d07af9c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.12.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.12.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-runtime-8.12.2.aar",
          "url": "databinding-runtime-8.12.2.aar",
          "size": 61017,
          "sha512": "ec4c93517b75d4463a3692643e746ba5a840bdc0cb7a1c1d1cf75320263a640720f99fc3e7a95f94c71ba5e826c8bb6ec527cc0ec16983b764b37660d02438fb",
          "sha256": "a3f48e1caa7a1b5706432c55cfb1e9f7179048e4f4e28449ab0280bf63f19214",
          "sha1": "e22a6f2a3ffc3b258c2127584982ba7de5e05f68",
          "md5": "8c0600f3f8c7532ef63787b31d07af9c"
        }
      ]
    }
  ]
}
