{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "manifest-merger",
    "version": "31.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "manifest-merger-31.12.0.jar",
          "url": "manifest-merger-31.12.0.jar",
          "size": 266204,
          "sha512": "1530ab1336ab1ac1ba759e72f19c19714f9542a244d65a9b22f1a67a05bf61a33398e21c51253715b72272309e23c991a921b8f8a2f5df2194d2cc75c8a09643",
          "sha256": "6b74646138f4ba373faf458a93e0000c2f5389059d1abb13d0be959531ea0579",
          "sha1": "cd6b3a9db88c5f84a888b634ab174baff4b6fb90",
          "md5": "efd2f9f54cef9a746fa2e9ae69fff28b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.12.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.12.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "manifest-merger-31.12.0.jar",
          "url": "manifest-merger-31.12.0.jar",
          "size": 266204,
          "sha512": "1530ab1336ab1ac1ba759e72f19c19714f9542a244d65a9b22f1a67a05bf61a33398e21c51253715b72272309e23c991a921b8f8a2f5df2194d2cc75c8a09643",
          "sha256": "6b74646138f4ba373faf458a93e0000c2f5389059d1abb13d0be959531ea0579",
          "sha1": "cd6b3a9db88c5f84a888b634ab174baff4b6fb90",
          "md5": "efd2f9f54cef9a746fa2e9ae69fff28b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.12.0-javadoc.jar",
          "url": "manifest-merger-31.12.0-javadoc.jar",
          "size": 275875,
          "sha512": "3e6a0eda3ca4a1687543740c51eaae9c04d26418ed2b7166311f0d7f53bfa6d188f7490ce31e9d679a60942d0763ac738855620db38dc15899c125e2e6bec130",
          "sha256": "49bcd8b6cccebbda7c0b9591f50fc36d25b76895b4652b06fbc2c7cb1e0daf14",
          "sha1": "431e239e3c77a4f25ae6e9ee95110388e1c00c4f",
          "md5": "472f40fc5078f3494063eaf92521ebae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.12.0-sources.jar",
          "url": "manifest-merger-31.12.0-sources.jar",
          "size": 238897,
          "sha512": "cb32bfa635f63b63e45c3eede28a03efff3d255507f22ea6005a788d3b0002a139baddb3a5c32fdcf3427f43b4c9a86ab5102fb2455a6411871cf1e5f3a48e17",
          "sha256": "bcbcedb128af621a4d74a0887435422ed9d60d02caf76abc184882f0b594787a",
          "sha1": "e2baa64a5412455fef29eaa0763bcdf896625e6c",
          "md5": "5bc64ce959e8c8e231d3ee9e8a88d6e4"
        }
      ]
    }
  ]
}
