{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "8.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.8.2.jar",
          "url": "gradle-api-8.8.2.jar",
          "size": 364505,
          "sha512": "24db10330d0655e9d90c88140b9f9c1948542c9b3be08c017a076191e18537dfbd36eb3cc83a0531abdea227b74ccc095014c45a4c59e76f51d0e288589840b4",
          "sha256": "0c931caddbeb567afbbe3a3489915a90618b4e5dbc6f43adbdd81f174c28c69a",
          "sha1": "ef5c7a6c103060dbfc43432bf1ac161ba92a0e84",
          "md5": "edd3218403c9b010e17bb25d0036887a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.8.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.8.2.jar",
          "url": "gradle-api-8.8.2.jar",
          "size": 364505,
          "sha512": "24db10330d0655e9d90c88140b9f9c1948542c9b3be08c017a076191e18537dfbd36eb3cc83a0531abdea227b74ccc095014c45a4c59e76f51d0e288589840b4",
          "sha256": "0c931caddbeb567afbbe3a3489915a90618b4e5dbc6f43adbdd81f174c28c69a",
          "sha1": "ef5c7a6c103060dbfc43432bf1ac161ba92a0e84",
          "md5": "edd3218403c9b010e17bb25d0036887a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.8.2-javadoc.jar",
          "url": "gradle-api-8.8.2-javadoc.jar",
          "size": 151115,
          "sha512": "2c3932110bdcba1fce602b94c51c322623c9851f77a97be1959b46a655f91080f23c36906f86d5f9c8a14d91483084cb0077a8ab9f6fc300a993a0495712c9c1",
          "sha256": "545bacb04c3d24e78b519cba40e45130fd71a46d02de7f90ea86e10a39d44e0a",
          "sha1": "7809df1311a29a39a922b652fa249986cfb0404c",
          "md5": "710c5cfd4b49cab3bfcd10e58aa478df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.8.2-sources.jar",
          "url": "gradle-api-8.8.2-sources.jar",
          "size": 357732,
          "sha512": "c173d8292b12315a60cf371d945ae54c4484cbcab27cbfea646d44ab068b5b45e0974e69ecef978268ca29c9ff272c7675337156c7174292195f2b569e829543",
          "sha256": "8a44f42eb4273fe95539e6a23b5d4b886a83c00dfc25e93d980f9d21f046b83e",
          "sha1": "9059aefecdc0a8449eb41df5196bfabfc0587dac",
          "md5": "2c13e99475572ecd56729c1b7d538584"
        }
      ]
    }
  ]
}
