{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-settings-api",
    "version": "8.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.9.0.jar",
          "url": "gradle-settings-api-8.9.0.jar",
          "size": 9953,
          "sha512": "04d843d463ae705722be0826aafb839a0ad83cf69fe8a8646355cf6a68b0775ef431d3da45579fd3bccd87619540523d5ff371e99e16d470d7f9fb5c0535b0f4",
          "sha256": "8243da80bce5a3c55a2960a4598cba8c45a4c5b43a5d3d19954c047920c36c67",
          "sha1": "bfe7ea960276acf94a716f61636937b1f59db6b0",
          "md5": "e4f2b6544e6e9be0e2fa522ce87e76ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-settings-api-8.9.0.jar",
          "url": "gradle-settings-api-8.9.0.jar",
          "size": 9953,
          "sha512": "04d843d463ae705722be0826aafb839a0ad83cf69fe8a8646355cf6a68b0775ef431d3da45579fd3bccd87619540523d5ff371e99e16d470d7f9fb5c0535b0f4",
          "sha256": "8243da80bce5a3c55a2960a4598cba8c45a4c5b43a5d3d19954c047920c36c67",
          "sha1": "bfe7ea960276acf94a716f61636937b1f59db6b0",
          "md5": "e4f2b6544e6e9be0e2fa522ce87e76ea"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.9.0-javadoc.jar",
          "url": "gradle-settings-api-8.9.0-javadoc.jar",
          "size": 261,
          "sha512": "de3e0e64d51f4d3fbde909249af3d4306b02377cdc1762588ea7475dc5be64dbc867560a20aa27677815e953601ae55016cecca160329a6f13405e151497c01f",
          "sha256": "d2c282661e00746a9febf31c4ec26f83d9c3c40a0134d82640b09167c8cde0d8",
          "sha1": "ee09f3f213747ec8df025d18c7f2112cfe0b4baf",
          "md5": "1848e93351483c83e74a473dd1a410c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.9.0-sources.jar",
          "url": "gradle-settings-api-8.9.0-sources.jar",
          "size": 9470,
          "sha512": "e2d4b9e392558d49e0f820a2a6db190edd459d293752ce46386f3f75466fb4035fbcae1ab90aff64dd84ddf051f5c66a9a4ac4280ade4ad9c3cf425f2a3350ae",
          "sha256": "6d1621caeac6920f8eba6d9587d201eb86f8b7d83cca55aa46930311aebc3df2",
          "sha1": "d8a0315ea5b602a81059c2ed31c532d722e6696f",
          "md5": "2b96c4f2da483ece6edf6529793aaffe"
        }
      ]
    }
  ]
}
