{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-model",
    "version": "8.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "builder-model-8.8.1.jar",
          "url": "builder-model-8.8.1.jar",
          "size": 125143,
          "sha512": "9cc08fec723b2a41ac039085fb778be6f45d3a95cf412b7d43d810aa082b43c3513b83fe00f0f7ad4040e931f1c446619b2bb40ed11f5208162c56924a5c2ebe",
          "sha256": "c313c28cf7ad1cdaafb2e314b9a4ec12e3d9826caac862756a90611b24f701d1",
          "sha1": "15300e65b0106a74f55c017dc8bbb30e9c0aba96",
          "md5": "48b2647b9d3b824ee85422ec30bd1b69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "builder-model-8.8.1.jar",
          "url": "builder-model-8.8.1.jar",
          "size": 125143,
          "sha512": "9cc08fec723b2a41ac039085fb778be6f45d3a95cf412b7d43d810aa082b43c3513b83fe00f0f7ad4040e931f1c446619b2bb40ed11f5208162c56924a5c2ebe",
          "sha256": "c313c28cf7ad1cdaafb2e314b9a4ec12e3d9826caac862756a90611b24f701d1",
          "sha1": "15300e65b0106a74f55c017dc8bbb30e9c0aba96",
          "md5": "48b2647b9d3b824ee85422ec30bd1b69"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.8.1-javadoc.jar",
          "url": "builder-model-8.8.1-javadoc.jar",
          "size": 291422,
          "sha512": "9364de0fe7fa8ea90cedb101238831a796e8fed01ed2b6fa903c964dbc58a2424d2b5ba35880e9cb6bf611d0f28d6ba083c41824ca61fb0f932abd0136c468c8",
          "sha256": "bc8b0571a668bff42a76bf2a45e8dd3c152907c7753faf8a7b55cfff12aa4ff0",
          "sha1": "1c792d11919436dc2702542062674d140682cf75",
          "md5": "7582a3163bbc54cca0ce77c9c90f3815"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.8.1-sources.jar",
          "url": "builder-model-8.8.1-sources.jar",
          "size": 145555,
          "sha512": "5d9ac2a541612288a2fb220ea25b9d5c46086bcf917df6c444b016570396a70463754559bfae8c61243f29efe596cc41169225e6f2deabb6f1c517e26cc66611",
          "sha256": "c402ad0d9420bf39cc4a562bb5f85e66595d66408ab1af3d8cf5a3919572d151",
          "sha1": "a95fcda401ebe77ee30b7ea16d82e60d5c859f96",
          "md5": "389e019762e5fb0ef881f2071ba04344"
        }
      ]
    }
  ]
}
