{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-test-api",
    "version": "8.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "builder-test-api-8.12.0.jar",
          "url": "builder-test-api-8.12.0.jar",
          "size": 15329,
          "sha512": "d67f7e537d7266651f8cdc9cb19a4c8135f63681756112e9fa533900d2442b86d45fa9e220d5e6c6044483d1480173a90b556b11a7fc67c947e03640943c9c4e",
          "sha256": "764987a36f487abde16e6e7f52c09a89556451e25ff7ac6877ec07710648b9cb",
          "sha1": "ffacdec614645b4069df3973dd4c5b49b61fe82d",
          "md5": "c7cb2c8a3160a0893cf0b8f47fa414a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.12.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "31.12.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.12.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "builder-test-api-8.12.0.jar",
          "url": "builder-test-api-8.12.0.jar",
          "size": 15329,
          "sha512": "d67f7e537d7266651f8cdc9cb19a4c8135f63681756112e9fa533900d2442b86d45fa9e220d5e6c6044483d1480173a90b556b11a7fc67c947e03640943c9c4e",
          "sha256": "764987a36f487abde16e6e7f52c09a89556451e25ff7ac6877ec07710648b9cb",
          "sha1": "ffacdec614645b4069df3973dd4c5b49b61fe82d",
          "md5": "c7cb2c8a3160a0893cf0b8f47fa414a4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-8.12.0-javadoc.jar",
          "url": "builder-test-api-8.12.0-javadoc.jar",
          "size": 117194,
          "sha512": "f482c63bd6a4be5db863d3592caa11cf73a58abf7f36163cb6de87665bc4dac2d0392111632385b8148758ed0888633cbae911179676c41f5904f1d313fb970f",
          "sha256": "03088dc9fe065a6d2487426df5457606275d191143ae4cab5ab31b9aab718c88",
          "sha1": "eea5856e21d3020af8aac605b6dbcdb3b44231be",
          "md5": "351adef075f0d32dba5ae6757fb03959"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-8.12.0-sources.jar",
          "url": "builder-test-api-8.12.0-sources.jar",
          "size": 13848,
          "sha512": "b99a6fe676a507342dda15d2404f234ef22d941951c561a976fa9b30f0580d16a18e783d1537b6df97b24dc7d4f5ec5a1aec7dc1a9f230f70a1d6538c0edacd8",
          "sha256": "9d16bbe755d91696a7c78a8962bd248b663fc72a367ab441b947a36fe6e06eca",
          "sha1": "f807a45c4ac2ab5ff4e482d90d6584a3b4b5453a",
          "md5": "6f1f328985218a53219f8d592dd18e2a"
        }
      ]
    }
  ]
}
