{
  "formatVersion": "1.1",
  "component": {
    "group": "io.perfmark",
    "module": "perfmark-api",
    "version": "0.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "perfmark-api-0.26.0.jar",
          "url": "perfmark-api-0.26.0.jar",
          "size": 6816,
          "sha512": "2cb8c2aff303f4c310b6742ea1a99a2d8e7654756f391ad0d8642a6c19410335e1855aca5bdf7487a4ace74e55fb94e7b21c839e08cf33c63f36803d0fbe79ff",
          "sha256": "b7d23e93a34537ce332708269a0d1404788a5b5e1949e82f5535fce51b3ea95b",
          "sha1": "ef65452adaf20bf7d12ef55913aba24037b82738",
          "md5": "e80301eb310a53b2047e30db7964bce1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "perfmark-api-0.26.0.jar",
          "url": "perfmark-api-0.26.0.jar",
          "size": 6816,
          "sha512": "2cb8c2aff303f4c310b6742ea1a99a2d8e7654756f391ad0d8642a6c19410335e1855aca5bdf7487a4ace74e55fb94e7b21c839e08cf33c63f36803d0fbe79ff",
          "sha256": "b7d23e93a34537ce332708269a0d1404788a5b5e1949e82f5535fce51b3ea95b",
          "sha1": "ef65452adaf20bf7d12ef55913aba24037b82738",
          "md5": "e80301eb310a53b2047e30db7964bce1"
        }
      ]
    }
  ]
}
