{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-metadata-1.6.3.jar",
          "url": "kotlinx-serialization-core-1.6.3.jar",
          "size": 37039,
          "sha512": "c105c5d10548dab7da2d652bfbf606cc931e55f7dd66b6ab561d2b2c2adba2ddab6e19cf4ef9e2542b02e1f31a70e9b9172847b6718e09d124ed16b8a036e162",
          "sha256": "2fa05aff0f33a70da873c09a0ff66b5d54ccdc15e39e7ca4b82633e70c792f34",
          "sha1": "287c0ec44836bf44472585ee81d67b9b7d6c45c3",
          "md5": "def946751bc2d402ab1ddd61982c87c4"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-kotlin-1.6.3-sources.jar",
          "url": "kotlinx-serialization-core-1.6.3-sources.jar",
          "size": 99210,
          "sha512": "7e1b999af7f82ca94dfc47c9e4e00b35e8de6101f114176294ec2ad9b9657d58dbd8e0d2dd9a2c9d669edbd01a171a9f99be6ee43bedf0cefa5681387b4a367b",
          "sha256": "90e7b0150cb33cbd0e7b575d9da80ea1d8cb82ae8878f602a3f5eb1f38dd9e63",
          "sha1": "e6d336a41126f4fb5d561070b8df6657078a0538",
          "md5": "8f02689b284fb6e61112eaec7bbe217c"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-androidnativearm32/1.6.3/kotlinx-serialization-core-androidnativearm32-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-androidnativearm32",
        "version": "1.6.3"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-androidnativearm32/1.6.3/kotlinx-serialization-core-androidnativearm32-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-androidnativearm32",
        "version": "1.6.3"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-androidnativearm64/1.6.3/kotlinx-serialization-core-androidnativearm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-androidnativearm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-androidnativearm64/1.6.3/kotlinx-serialization-core-androidnativearm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-androidnativearm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-androidnativex64/1.6.3/kotlinx-serialization-core-androidnativex64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-androidnativex64",
        "version": "1.6.3"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-androidnativex64/1.6.3/kotlinx-serialization-core-androidnativex64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-androidnativex64",
        "version": "1.6.3"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-androidnativex86/1.6.3/kotlinx-serialization-core-androidnativex86-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-androidnativex86",
        "version": "1.6.3"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-androidnativex86/1.6.3/kotlinx-serialization-core-androidnativex86-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-androidnativex86",
        "version": "1.6.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosarm64/1.6.3/kotlinx-serialization-core-iosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosarm64/1.6.3/kotlinx-serialization-core-iosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosarm64/1.6.3/kotlinx-serialization-core-iosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iossimulatorarm64/1.6.3/kotlinx-serialization-core-iossimulatorarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iossimulatorarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iossimulatorarm64/1.6.3/kotlinx-serialization-core-iossimulatorarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iossimulatorarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iossimulatorarm64/1.6.3/kotlinx-serialization-core-iossimulatorarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iossimulatorarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosx64/1.6.3/kotlinx-serialization-core-iosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosx64/1.6.3/kotlinx-serialization-core-iosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosx64/1.6.3/kotlinx-serialization-core-iosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-js/1.6.3/kotlinx-serialization-core-js-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-js",
        "version": "1.6.3"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-js/1.6.3/kotlinx-serialization-core-js-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-js",
        "version": "1.6.3"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-js/1.6.3/kotlinx-serialization-core-js-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-js",
        "version": "1.6.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-jvm/1.6.3/kotlinx-serialization-core-jvm-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-jvm",
        "version": "1.6.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-jvm/1.6.3/kotlinx-serialization-core-jvm-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-jvm",
        "version": "1.6.3"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-jvm/1.6.3/kotlinx-serialization-core-jvm-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-jvm",
        "version": "1.6.3"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-linuxarm32hfp/1.6.3/kotlinx-serialization-core-linuxarm32hfp-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-linuxarm32hfp",
        "version": "1.6.3"
      }
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-linuxarm32hfp/1.6.3/kotlinx-serialization-core-linuxarm32hfp-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-linuxarm32hfp",
        "version": "1.6.3"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-linuxarm64/1.6.3/kotlinx-serialization-core-linuxarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-linuxarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-linuxarm64/1.6.3/kotlinx-serialization-core-linuxarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-linuxarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-linuxx64/1.6.3/kotlinx-serialization-core-linuxx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-linuxx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-linuxx64/1.6.3/kotlinx-serialization-core-linuxx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-linuxx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-macosarm64/1.6.3/kotlinx-serialization-core-macosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-macosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-macosarm64/1.6.3/kotlinx-serialization-core-macosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-macosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-macosarm64/1.6.3/kotlinx-serialization-core-macosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-macosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-macosx64/1.6.3/kotlinx-serialization-core-macosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-macosx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-macosx64/1.6.3/kotlinx-serialization-core-macosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-macosx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-macosx64/1.6.3/kotlinx-serialization-core-macosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-macosx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-mingwx64/1.6.3/kotlinx-serialization-core-mingwx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-mingwx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-mingwx64/1.6.3/kotlinx-serialization-core-mingwx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-mingwx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvosarm64/1.6.3/kotlinx-serialization-core-tvosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvosarm64/1.6.3/kotlinx-serialization-core-tvosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvosarm64/1.6.3/kotlinx-serialization-core-tvosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvossimulatorarm64/1.6.3/kotlinx-serialization-core-tvossimulatorarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvossimulatorarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvossimulatorarm64/1.6.3/kotlinx-serialization-core-tvossimulatorarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvossimulatorarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvossimulatorarm64/1.6.3/kotlinx-serialization-core-tvossimulatorarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvossimulatorarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvosx64/1.6.3/kotlinx-serialization-core-tvosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvosx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvosx64/1.6.3/kotlinx-serialization-core-tvosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvosx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvosx64/1.6.3/kotlinx-serialization-core-tvosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvosx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-wasm-js/1.6.3/kotlinx-serialization-core-wasm-js-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-wasm-js",
        "version": "1.6.3"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-wasm-js/1.6.3/kotlinx-serialization-core-wasm-js-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-wasm-js",
        "version": "1.6.3"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-wasm-js/1.6.3/kotlinx-serialization-core-wasm-js-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-wasm-js",
        "version": "1.6.3"
      }
    },
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-wasm-wasi/1.6.3/kotlinx-serialization-core-wasm-wasi-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-wasm-wasi",
        "version": "1.6.3"
      }
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-wasm-wasi/1.6.3/kotlinx-serialization-core-wasm-wasi-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-wasm-wasi",
        "version": "1.6.3"
      }
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-wasm-wasi/1.6.3/kotlinx-serialization-core-wasm-wasi-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-wasm-wasi",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosarm32/1.6.3/kotlinx-serialization-core-watchosarm32-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosarm32",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosarm32/1.6.3/kotlinx-serialization-core-watchosarm32-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosarm32",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosarm32/1.6.3/kotlinx-serialization-core-watchosarm32-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosarm32",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosarm64/1.6.3/kotlinx-serialization-core-watchosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosarm64/1.6.3/kotlinx-serialization-core-watchosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosarm64/1.6.3/kotlinx-serialization-core-watchosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosdevicearm64/1.6.3/kotlinx-serialization-core-watchosdevicearm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosdevicearm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosdevicearm64/1.6.3/kotlinx-serialization-core-watchosdevicearm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosdevicearm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosdevicearm64/1.6.3/kotlinx-serialization-core-watchosdevicearm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosdevicearm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchossimulatorarm64/1.6.3/kotlinx-serialization-core-watchossimulatorarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchossimulatorarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchossimulatorarm64/1.6.3/kotlinx-serialization-core-watchossimulatorarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchossimulatorarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchossimulatorarm64/1.6.3/kotlinx-serialization-core-watchossimulatorarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchossimulatorarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosx64/1.6.3/kotlinx-serialization-core-watchosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosx64/1.6.3/kotlinx-serialization-core-watchosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosx64/1.6.3/kotlinx-serialization-core-watchosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosx64",
        "version": "1.6.3"
      }
    }
  ]
}
