{
  "formatVersion": "1.1",
  "component": {
    "group": "io.objectbox",
    "module": "objectbox-gradle-plugin",
    "version": "5.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "objectbox-gradle-plugin-5.0.1.jar",
          "url": "objectbox-gradle-plugin-5.0.1.jar",
          "size": 43580,
          "sha512": "d2478d0341f1b39b101434424d876e6dd440aad5f0165879e1b6e071657d228640e00f83ecd5344c355e89f87c2885db13df213613553a36cd4069db8931aa98",
          "sha256": "849d91f7c08d234b3215445ce48432566fa6aae27dd36d6f7ad4ca8793150fca",
          "sha1": "4ea226675f4e5dc55d109f3fb87f7831b4f47e9d",
          "md5": "9cbff0468f423f459596df4683350d4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.objectbox",
          "module": "objectbox-code-modifier",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.objectbox",
          "module": "agp-wrapper-3-4",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.objectbox",
          "module": "agp-wrapper-7-2",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "objectbox-gradle-plugin-5.0.1.jar",
          "url": "objectbox-gradle-plugin-5.0.1.jar",
          "size": 43580,
          "sha512": "d2478d0341f1b39b101434424d876e6dd440aad5f0165879e1b6e071657d228640e00f83ecd5344c355e89f87c2885db13df213613553a36cd4069db8931aa98",
          "sha256": "849d91f7c08d234b3215445ce48432566fa6aae27dd36d6f7ad4ca8793150fca",
          "sha1": "4ea226675f4e5dc55d109f3fb87f7831b4f47e9d",
          "md5": "9cbff0468f423f459596df4683350d4b"
        }
      ]
    }
  ]
}
