{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-adapters",
    "version": "8.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-adapters-8.12.2.aar",
          "url": "databinding-adapters-8.12.2.aar",
          "size": 70403,
          "sha512": "74b7ce3f0ffadc87e9c53beb1ea814c91db7cf0d57c8c75f2933a5870a1ae051634ea9ff5a0767a78e002ebb7c7f32ab60e205797780bc8821432384cdd84822",
          "sha256": "f0d34359a4153060794c377977a0f215acbd1882ef96d3e13985a1b68d8ff5d5",
          "sha1": "d2233a4add2c550f550de68a0e701659352e0d32",
          "md5": "fe0c258cf5efa31e27cbad272582285a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.12.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-adapters-8.12.2.aar",
          "url": "databinding-adapters-8.12.2.aar",
          "size": 70403,
          "sha512": "74b7ce3f0ffadc87e9c53beb1ea814c91db7cf0d57c8c75f2933a5870a1ae051634ea9ff5a0767a78e002ebb7c7f32ab60e205797780bc8821432384cdd84822",
          "sha256": "f0d34359a4153060794c377977a0f215acbd1882ef96d3e13985a1b68d8ff5d5",
          "sha1": "d2233a4add2c550f550de68a0e701659352e0d32",
          "md5": "fe0c258cf5efa31e27cbad272582285a"
        }
      ]
    }
  ]
}
