{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-api",
    "version": "2.0.10-1.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-api-2.0.10-1.0.24.jar",
          "url": "symbol-processing-api-2.0.10-1.0.24.jar",
          "size": 123041,
          "sha512": "cefcbd5c434a2a41abbe8dcb977133ac2e66b1516727d212dc5557efea40a45ac03afc63a3cf746f451c0894ff36a6bbed3d10a46ddcaa4c15f0850df80df206",
          "sha256": "dd7dde070be54de66c7bdd4de04c43fb429e0c62bb132a6448cfa33653afb229",
          "sha1": "9ef792dbf29a1fd2c9bc969ea45c8c08c9c0a7ff",
          "md5": "8a11cb73d1cbc03a30d0c484ebe51eca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-api-2.0.10-1.0.24.jar",
          "url": "symbol-processing-api-2.0.10-1.0.24.jar",
          "size": 123041,
          "sha512": "cefcbd5c434a2a41abbe8dcb977133ac2e66b1516727d212dc5557efea40a45ac03afc63a3cf746f451c0894ff36a6bbed3d10a46ddcaa4c15f0850df80df206",
          "sha256": "dd7dde070be54de66c7bdd4de04c43fb429e0c62bb132a6448cfa33653afb229",
          "sha1": "9ef792dbf29a1fd2c9bc969ea45c8c08c9c0a7ff",
          "md5": "8a11cb73d1cbc03a30d0c484ebe51eca"
        }
      ]
    }
  ]
}
