{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aaptcompiler",
    "version": "8.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aaptcompiler-8.8.1.jar",
          "url": "aaptcompiler-8.8.1.jar",
          "size": 497060,
          "sha512": "f903662fd094b7dd03237753807c73947c29a28ae2116ad234583d8b73f53b9ea287b148558a30772f18e95666837fb0b2e97fab6eacd8a76e809f68b36323cd",
          "sha256": "beca54cf5f21f007dc3293de633b84d215a5f11230eec1b2d57c4202342fec2b",
          "sha1": "7ce72c803670f0972c09d5398db0db2660322de5",
          "md5": "30f4387434c51431f2ce62d11e0d190d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "8.8.1-12006047"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "aaptcompiler-8.8.1.jar",
          "url": "aaptcompiler-8.8.1.jar",
          "size": 497060,
          "sha512": "f903662fd094b7dd03237753807c73947c29a28ae2116ad234583d8b73f53b9ea287b148558a30772f18e95666837fb0b2e97fab6eacd8a76e809f68b36323cd",
          "sha256": "beca54cf5f21f007dc3293de633b84d215a5f11230eec1b2d57c4202342fec2b",
          "sha1": "7ce72c803670f0972c09d5398db0db2660322de5",
          "md5": "30f4387434c51431f2ce62d11e0d190d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.8.1-javadoc.jar",
          "url": "aaptcompiler-8.8.1-javadoc.jar",
          "size": 81065,
          "sha512": "cd71c7cd934e947bdee969852b6e3a601185481e96b918921ecd2962963462cfae3c54c315c4a0a8e4ce4acf7f478a135ea68a5c94a41ce00b44b500c237139e",
          "sha256": "30e842edd5e5d8215fcd4efff8bb22698d0f7a869d85774590a9ab0b8241130d",
          "sha1": "c7e39dd692db43192cbc9a0fcc88efffb2e0dbed",
          "md5": "94b167f31a8a227d03ab6fd829bc70ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.8.1-sources.jar",
          "url": "aaptcompiler-8.8.1-sources.jar",
          "size": 152981,
          "sha512": "afa5dc89c694f26b4dbc68b327242876800d04fe8471d319565a77a760439e406a3bc01da6f8c3c2dffae345978de4af34fa08c4d5cf9e975c39525f940e586e",
          "sha256": "65b26c108381fa17cf6673ca272654576619aca46ca7c1335186ed501172ef93",
          "sha1": "fdfbc7d5823224dbfcb6a9bf45376777a66b0487",
          "md5": "7355bff0609229df3b71ccba81a1d70a"
        }
      ]
    }
  ]
}
