{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-gradle-plugin",
    "version": "1.9.20-1.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-gradle-plugin-1.9.20-1.0.14.jar",
          "url": "symbol-processing-gradle-plugin-1.9.20-1.0.14.jar",
          "size": 155404,
          "sha512": "31c6a5ff1f0b2ff274d3413b89e59a025afbde87ef338744a0578c719262d3fd18a0577d76ab70690d26855ed8f03a2a1ee3735f1b7e10fea3e7cff0cc9e064c",
          "sha256": "9fdb5412a517d9e3ab0b7413ad7165e402592d986bd8f1b5f5e9ff3f91cd82d2",
          "sha1": "9ab713597853ff3c2a89862fd2119d382879244e",
          "md5": "0ef22a5d64e793606b86b06a9f7a3b39"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.9.20-1.0.14"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-common-deps",
          "version": {
            "requires": "1.9.20-1.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-gradle-plugin-1.9.20-1.0.14.jar",
          "url": "symbol-processing-gradle-plugin-1.9.20-1.0.14.jar",
          "size": 155404,
          "sha512": "31c6a5ff1f0b2ff274d3413b89e59a025afbde87ef338744a0578c719262d3fd18a0577d76ab70690d26855ed8f03a2a1ee3735f1b7e10fea3e7cff0cc9e064c",
          "sha256": "9fdb5412a517d9e3ab0b7413ad7165e402592d986bd8f1b5f5e9ff3f91cd82d2",
          "sha1": "9ab713597853ff3c2a89862fd2119d382879244e",
          "md5": "0ef22a5d64e793606b86b06a9f7a3b39"
        }
      ]
    }
  ]
}
