{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.annotation",
    "module": "annotation-experimental",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13423379"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotation-experimental-1.5.0-sources.jar",
          "url": "annotation-experimental-1.5.0-sources.jar",
          "size": 9581,
          "sha512": "7f43c5dc58dd54b4f874e5cf1148b41200467671d1ba6dd326151f3a728cdbcee7ba3449922378fcceabe91f46c8f2dc9b7e49ba3f0eecd1a07c865e31651ca2",
          "sha256": "14ceae6e5b3c418bb7c295fbff215d20fd177e980a43fd56e86df9efe1a754d6",
          "sha1": "84ee6e5c3b789c148b138079635cf74b0f48afc3",
          "md5": "91e524c2694831165a1e9a457f0d07bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-experimental-1.5.0.aar",
          "url": "annotation-experimental-1.5.0.aar",
          "size": 45139,
          "sha512": "3f88540457c8de96d7d1d9464331acba00b5b3e6635b7e1d93c74635d0c893bfe758f8506f9f31d5d56d0e115c2bccf732e3604c0ab81c87b70131071a6abd4a",
          "sha256": "02b0a4256618f85386c92e5cec166dc7f300820888a290227a3c0c65b82cbb36",
          "sha1": "32dbc530366c901bf5638ab2dcea5ba8a009b3d9",
          "md5": "77a71a2ee5b123fec7888fd08760a110"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-experimental-1.5.0.aar",
          "url": "annotation-experimental-1.5.0.aar",
          "size": 45139,
          "sha512": "3f88540457c8de96d7d1d9464331acba00b5b3e6635b7e1d93c74635d0c893bfe758f8506f9f31d5d56d0e115c2bccf732e3604c0ab81c87b70131071a6abd4a",
          "sha256": "02b0a4256618f85386c92e5cec166dc7f300820888a290227a3c0c65b82cbb36",
          "sha1": "32dbc530366c901bf5638ab2dcea5ba8a009b3d9",
          "md5": "77a71a2ee5b123fec7888fd08760a110"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "annotation-experimental-1.5.0-versionMetadata.json",
          "url": "annotation-experimental-1.5.0-versionMetadata.json",
          "size": 1282,
          "sha512": "b93bdba05211656464b018f50a4415f8a2204c963cb4897af08648bf3510d49a9665377a8b2e3ca968c682a75a25cb4ba01536858ecb249efa6e3d4d046c00a0",
          "sha256": "1ea05aa696512a10f8c76f977094c5aa2c4f78ad4d8d39bfcf386deb0906e2af",
          "sha1": "cb984081b26882846108c6270ea8778f0f951999",
          "md5": "105e4179a7dd102af002b9b77f4bbc52"
        }
      ]
    }
  ]
}