{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "manifest-merger",
    "version": "31.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "manifest-merger-31.8.2.jar",
          "url": "manifest-merger-31.8.2.jar",
          "size": 256815,
          "sha512": "03d2c63fb4c0c85e7ad51a2aa494751b43f020a0a09892496650fab031cdb25e288e370f5a8350d42d85791d7f2c984b6dc380da24e0320bfe6c4a6c85d61ae9",
          "sha256": "5f46751193f5c5af795376b0e6e992fe9e9b9f8216d9caafda6f010bb6f3862f",
          "sha1": "ea72292817e9063dbaea339864d2e7bba9d9d20f",
          "md5": "285a843498f37176298746b06acb301e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.8.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.8.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.8.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "manifest-merger-31.8.2.jar",
          "url": "manifest-merger-31.8.2.jar",
          "size": 256815,
          "sha512": "03d2c63fb4c0c85e7ad51a2aa494751b43f020a0a09892496650fab031cdb25e288e370f5a8350d42d85791d7f2c984b6dc380da24e0320bfe6c4a6c85d61ae9",
          "sha256": "5f46751193f5c5af795376b0e6e992fe9e9b9f8216d9caafda6f010bb6f3862f",
          "sha1": "ea72292817e9063dbaea339864d2e7bba9d9d20f",
          "md5": "285a843498f37176298746b06acb301e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.8.2-javadoc.jar",
          "url": "manifest-merger-31.8.2-javadoc.jar",
          "size": 275781,
          "sha512": "cbb6da936ded0d8584c63bbcd5d48ad86c9c48affd7386fbe4702c63d3576e9af617694ff5737cdb35c6d52fc34068f317f1db4af9354b1df92fa2476d1e9c00",
          "sha256": "e7d521c17385a9f609084bb88f23ad9e41836dd5d0b21fc9b52320e9a815347d",
          "sha1": "fb4f3ff5fa002ba896d98d1f0069b6390ac74fa4",
          "md5": "ad5e825d07f6edb4be4d7608a45a8111"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.8.2-sources.jar",
          "url": "manifest-merger-31.8.2-sources.jar",
          "size": 235313,
          "sha512": "208f5fcd1157073e4f3931bddd707ec184c558af791ba2aa3b34627a5d349e6d7486e453f8a3c849a4be17f28532934a1bf73ffd59d033f812a7ec04348b20ef",
          "sha256": "a3b5bcfa395c7b995529ee145793b7324334a78eab981535d6c7358f62699e20",
          "sha1": "da3ed9dc54a633bd59dd7f19e2c19368bb38c2fc",
          "md5": "8a8a8a4414325624815d676f857c7154"
        }
      ]
    }
  ]
}
