{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-1.5.1.aar",
          "url": "fragment-1.5.1.aar",
          "size": 336881,
          "sha512": "b233cc18bb4ecf2fe1d6e7481de261ed4de822e917e387d73fce846076f61771f8d19a902699ecf71558ab39349c1826d492d3facd75ff93c017d95c42ef8b2d",
          "sha256": "82b04780eda21b0a5eea02475415887a1cadfb368b371221aeb40703c067f338",
          "sha1": "39660bdcb1ed2c71e181ec3ac7dbfa65fc0f701f",
          "md5": "e2abd4e3fbbeda21dcde05b1a92c57e3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-1.5.1.aar",
          "url": "fragment-1.5.1.aar",
          "size": 336881,
          "sha512": "b233cc18bb4ecf2fe1d6e7481de261ed4de822e917e387d73fce846076f61771f8d19a902699ecf71558ab39349c1826d492d3facd75ff93c017d95c42ef8b2d",
          "sha256": "82b04780eda21b0a5eea02475415887a1cadfb368b371221aeb40703c067f338",
          "sha1": "39660bdcb1ed2c71e181ec3ac7dbfa65fc0f701f",
          "md5": "e2abd4e3fbbeda21dcde05b1a92c57e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fragment-1.5.1-sources.jar",
          "url": "fragment-1.5.1-sources.jar",
          "size": 190050,
          "sha512": "1d9c8f280d83105e5b3dca485e46f915eec5165860e839e8ed913aeaa42b8e1f168a252563217a2dc1740fa8b03391f0e5fc50a5fea2078a45a5938d2e8d9a0a",
          "sha256": "316473b62392d2153f9c16da952ff89024d489556daa9d49a63dc437e3a9fec5",
          "sha1": "78111ea263bdb82bc11951a10b6af4d25d944167",
          "md5": "5e59f30ef56d9baca274da1b6b894ff5"
        }
      ]
    }
  ]
}