{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aaptcompiler",
    "version": "8.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aaptcompiler-8.12.2.jar",
          "url": "aaptcompiler-8.12.2.jar",
          "size": 496115,
          "sha512": "87f4f4a4eb01c2f5ba47077b0455431a3e699e3a79105eb1d6dc1ba9421f7831085497d53ba4b5bc73d87809bc3741f92c7970d5104c27101f89390f16597edd",
          "sha256": "245380cbd09296004a59138f2b9d3b73f456ff6111cc12bf9820b67e529b05a8",
          "sha1": "eb948055e23cdf62fd5ae80e821c91aee2934e1e",
          "md5": "637ac1491ab8904eeb961af74d7eb1cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "8.12.2-13700139"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.12.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.12.2"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "aaptcompiler-8.12.2.jar",
          "url": "aaptcompiler-8.12.2.jar",
          "size": 496115,
          "sha512": "87f4f4a4eb01c2f5ba47077b0455431a3e699e3a79105eb1d6dc1ba9421f7831085497d53ba4b5bc73d87809bc3741f92c7970d5104c27101f89390f16597edd",
          "sha256": "245380cbd09296004a59138f2b9d3b73f456ff6111cc12bf9820b67e529b05a8",
          "sha1": "eb948055e23cdf62fd5ae80e821c91aee2934e1e",
          "md5": "637ac1491ab8904eeb961af74d7eb1cf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.12.2-javadoc.jar",
          "url": "aaptcompiler-8.12.2-javadoc.jar",
          "size": 81065,
          "sha512": "6472da77e77a367c7247535fcc1d112806d66a941a67ca3191232f99a086c262bbb92b4b3522e155ef4a3472ad700dd3bd435914c751601b592a2e42075c8051",
          "sha256": "8741afd4e67144bd8031807c72e82ce709a59263d3c216d4d8f38c4bae968834",
          "sha1": "aff1a6b1b16c91f6cc2bbef085924337c58a6dd3",
          "md5": "39fb238fadd45fed02868bfda353aa6a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.12.2-sources.jar",
          "url": "aaptcompiler-8.12.2-sources.jar",
          "size": 152981,
          "sha512": "45148c7b3420b2fbcff40d25fa6dd1a24d3cbd6015d03f7e2f9e1bbaddc888fe5f724f091d8694d81198f642daffa04e2152742ad9b62334144b71b54f5b31d2",
          "sha256": "60d4ddae1d711a71ac09ca375565e345806e6ae3d5896425f9dcab36f5ca401b",
          "sha1": "96dedf36502bce74c25d5cd686899bbfa83f4eac",
          "md5": "2274e4fb50104dbd324ade0a9f46ee8b"
        }
      ]
    }
  ]
}
