{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-common-deps",
    "version": "2.1.10-1.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-common-deps-2.1.10-1.0.29.jar",
          "url": "symbol-processing-common-deps-2.1.10-1.0.29.jar",
          "size": 109757,
          "sha512": "fc41d9662fddd2143a65917c3a0dba11254cac66232bb2e85fdd885b7044a52b7647095fd4d73ece953cd6afe5c479e57f97c0811f901833910a2f4721dea19a",
          "sha256": "279548f7753d61c6db1cbb543ef8761ba6064436b25e6c3677f837b836966578",
          "sha1": "b8d560959201beb9448a007918f3d178d9448d2a",
          "md5": "6cbe14c803360d6b6ec4e6e3d5941983"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-common-deps-2.1.10-1.0.29.jar",
          "url": "symbol-processing-common-deps-2.1.10-1.0.29.jar",
          "size": 109757,
          "sha512": "fc41d9662fddd2143a65917c3a0dba11254cac66232bb2e85fdd885b7044a52b7647095fd4d73ece953cd6afe5c479e57f97c0811f901833910a2f4721dea19a",
          "sha256": "279548f7753d61c6db1cbb543ef8761ba6064436b25e6c3677f837b836966578",
          "sha1": "b8d560959201beb9448a007918f3d178d9448d2a",
          "md5": "6cbe14c803360d6b6ec4e6e3d5941983"
        }
      ]
    }
  ]
}
