{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-paging",
    "version": "2.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13652230"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-paging-2.7.2-multiplatform-sources.jar",
          "url": "room-paging-2.7.2-multiplatform-sources.jar",
          "size": 18484,
          "sha512": "f5889d32954f6bc1b9a8a6a3cc6e1205d11b3276db35ff6c0311e44f77ca8031146b6fb38794dfdfe3608f75b921ca63a8bc3579d64d182b3fd24bb4d8a8b9c2",
          "sha256": "486790e0ddd3eae90c4b6d64e48b9ee24ad302cb87696eeb256c60cabdd62a88",
          "sha1": "7a1a18d4b3df9f15f262f72624bbfe63e4acb656",
          "md5": "8a8f7b3e6fa5d0f19f53137d166a5a19"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "room-paging-2.7.2-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-paging-metadata-2.7.2.jar",
          "url": "room-paging-2.7.2.jar",
          "size": 10318,
          "sha512": "395287b74556f56daa535904ff6e24fde9df88675538404da6c26a67896ecdb72ccd91640dd13945b0b1f954c2f9dbfa800c12a2aafda8732c8237679843d4f3",
          "sha256": "6f292a2e63b35cb2eb1a72c1ebc8a0f63053e733d84980b5bcde10b29ac2eb95",
          "sha1": "b7b37ead007a27d94722d202c30c944a4f1a94ad",
          "md5": "ca3163105137fe5bc1845f0351838c28"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-paging is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-paging-kotlin-2.7.2-sources.jar",
          "url": "room-paging-2.7.2-sources.jar",
          "size": 12040,
          "sha512": "86ba7b97d4df0959510398c60ee43326238303c99f5ac7f1351fe723bfaf15c02969a481de47aa83f2e0d54ece52b73a18668cebb9d0d9c73b1eaff17391408c",
          "sha256": "031b70d39d967405db2872d3f1b00d7f37bfcfd912e5a21fae046449d246d68b",
          "sha1": "2613d96e70467c651ec6e7b6094d2460518cc748",
          "md5": "8054a9a1309701a62f089f07e515ae6f"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../room-paging-android/2.7.2/room-paging-android-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-android",
        "version": "2.7.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../room-paging-android/2.7.2/room-paging-android-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-android",
        "version": "2.7.2"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../room-paging-android/2.7.2/room-paging-android-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-android",
        "version": "2.7.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-iosarm64/2.7.2/room-paging-iosarm64-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-iosarm64",
        "version": "2.7.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-iosarm64/2.7.2/room-paging-iosarm64-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-iosarm64",
        "version": "2.7.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-iosarm64/2.7.2/room-paging-iosarm64-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-iosarm64",
        "version": "2.7.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-iossimulatorarm64/2.7.2/room-paging-iossimulatorarm64-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-iossimulatorarm64",
        "version": "2.7.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-iossimulatorarm64/2.7.2/room-paging-iossimulatorarm64-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-iossimulatorarm64",
        "version": "2.7.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-iossimulatorarm64/2.7.2/room-paging-iossimulatorarm64-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-iossimulatorarm64",
        "version": "2.7.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-iosx64/2.7.2/room-paging-iosx64-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-iosx64",
        "version": "2.7.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-iosx64/2.7.2/room-paging-iosx64-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-iosx64",
        "version": "2.7.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-iosx64/2.7.2/room-paging-iosx64-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-iosx64",
        "version": "2.7.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../room-paging-jvm/2.7.2/room-paging-jvm-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-jvm",
        "version": "2.7.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../room-paging-jvm/2.7.2/room-paging-jvm-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-jvm",
        "version": "2.7.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../room-paging-jvm/2.7.2/room-paging-jvm-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-jvm",
        "version": "2.7.2"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-linuxarm64/2.7.2/room-paging-linuxarm64-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-linuxarm64",
        "version": "2.7.2"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-linuxarm64/2.7.2/room-paging-linuxarm64-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-linuxarm64",
        "version": "2.7.2"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-linuxx64/2.7.2/room-paging-linuxx64-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-linuxx64",
        "version": "2.7.2"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-linuxx64/2.7.2/room-paging-linuxx64-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-linuxx64",
        "version": "2.7.2"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-macosarm64/2.7.2/room-paging-macosarm64-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-macosarm64",
        "version": "2.7.2"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-macosarm64/2.7.2/room-paging-macosarm64-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-macosarm64",
        "version": "2.7.2"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-macosarm64/2.7.2/room-paging-macosarm64-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-macosarm64",
        "version": "2.7.2"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-macosx64/2.7.2/room-paging-macosx64-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-macosx64",
        "version": "2.7.2"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-macosx64/2.7.2/room-paging-macosx64-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-macosx64",
        "version": "2.7.2"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-paging-macosx64/2.7.2/room-paging-macosx64-2.7.2.module",
        "group": "androidx.room",
        "module": "room-paging-macosx64",
        "version": "2.7.2"
      }
    }
  ]
}