{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-test-api",
    "version": "8.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "builder-test-api-8.11.0.jar",
          "url": "builder-test-api-8.11.0.jar",
          "size": 15329,
          "sha512": "a33eb6d088d762fcc60470d50f866e0cd3dfaacf5e79870fbee55f4b7b6edcf8e957b2ab6852ab491d565cfdaf6c9a43a13b377821ba2173c42070de6707ca80",
          "sha256": "528f7c41391876a0913d943672fd6a94f8da837464a19da10484585abead8264",
          "sha1": "e3cf05404fc33d8f485b12d293c03282ffed916e",
          "md5": "3c74674b87194d043b9ef92b41d0364c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.11.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "31.11.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.11.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "builder-test-api-8.11.0.jar",
          "url": "builder-test-api-8.11.0.jar",
          "size": 15329,
          "sha512": "a33eb6d088d762fcc60470d50f866e0cd3dfaacf5e79870fbee55f4b7b6edcf8e957b2ab6852ab491d565cfdaf6c9a43a13b377821ba2173c42070de6707ca80",
          "sha256": "528f7c41391876a0913d943672fd6a94f8da837464a19da10484585abead8264",
          "sha1": "e3cf05404fc33d8f485b12d293c03282ffed916e",
          "md5": "3c74674b87194d043b9ef92b41d0364c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-8.11.0-javadoc.jar",
          "url": "builder-test-api-8.11.0-javadoc.jar",
          "size": 117194,
          "sha512": "9bf310020b4ebe6efa6d8f9c358c7b8a754325f62f2f8de8b2d13aec23c0357f22194f4e3bd5edf12f99c68f3bc2f887567b640ea88c56e93df608d8af9745ca",
          "sha256": "d688a9d88817b709fc4bc8a5ca4b6f9f36aa3cee39c7c9e71de0fdb20610da57",
          "sha1": "4eeb020f8e783fea393871adb20543f41c6e6529",
          "md5": "9bfe5738a36c48586e13a5d37985502f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-8.11.0-sources.jar",
          "url": "builder-test-api-8.11.0-sources.jar",
          "size": 13848,
          "sha512": "b6e208864eb65c3fc0c42f314d40f8c00e9fb90080bb7fa0c2a53eb2d312c40e21326d3c893ea02a5613804a249b3041eb541d6c8f55dc247527229ca11e5b30",
          "sha256": "c7ac555dedcb67333afa018b2443b88c44517a9fd639167646ebd93b14712ee6",
          "sha1": "73400bafa47ccb032899842bf4f453f1471e844f",
          "md5": "c2a58899874e9b3e46591f3899e98859"
        }
      ]
    }
  ]
}
