{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-model",
    "version": "8.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "builder-model-8.11.0.jar",
          "url": "builder-model-8.11.0.jar",
          "size": 126332,
          "sha512": "8126686b19b31371cdf22c23878413ca4ea7f0a2c4daeb2dcbc912df4d8348ac09d3595701981021a1dd03b9160691ea3e7d3675b80ec6a69df78dc90ebcf2ff",
          "sha256": "9221899b78f71868a4b9189b175c06614cea3b35cda93b90d213409f3bd391b8",
          "sha1": "3e82cf5177d51a82538a9b4048d0f8e12e544de6",
          "md5": "c16614775af28c6551442fac820e4905"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "31.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "builder-model-8.11.0.jar",
          "url": "builder-model-8.11.0.jar",
          "size": 126332,
          "sha512": "8126686b19b31371cdf22c23878413ca4ea7f0a2c4daeb2dcbc912df4d8348ac09d3595701981021a1dd03b9160691ea3e7d3675b80ec6a69df78dc90ebcf2ff",
          "sha256": "9221899b78f71868a4b9189b175c06614cea3b35cda93b90d213409f3bd391b8",
          "sha1": "3e82cf5177d51a82538a9b4048d0f8e12e544de6",
          "md5": "c16614775af28c6551442fac820e4905"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.11.0-javadoc.jar",
          "url": "builder-model-8.11.0-javadoc.jar",
          "size": 291422,
          "sha512": "914f7494a5a6f9125eaa824735d5826eefc6f1cab2e89458cda9708c5e77e4f80afa46ea46c6ee9831a32d357529c2d4b08e8f17c0d755012fea8f778ae8b909",
          "sha256": "de9471d832e0107328953f7410342f49893c747993b88a99249ef4445e8e9925",
          "sha1": "9edb970427ba0f0b512f9afad187f3200df3573f",
          "md5": "c972c754ceff884f952cd419625f2746"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.11.0-sources.jar",
          "url": "builder-model-8.11.0-sources.jar",
          "size": 145971,
          "sha512": "a328a76f8266660996c61d4f3de84eeb48f2c924c2b43ebc1faae015ace784dcf5ce7a4f4b9f63996cddb4f602030ef3b3d18871e967e10918500952f4b05f9c",
          "sha256": "dce3fbf413a2ca1d9782be544c317ae95aa1a27a44cdd31302a7af8adb334aa9",
          "sha1": "474369ee6f76ae1808bcafc4d23529d8ea914653",
          "md5": "e935460e97164789371c644359c96893"
        }
      ]
    }
  ]
}
