{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sqlite/2.6.1/sqlite-2.6.1.module",
    "group": "androidx.sqlite",
    "module": "sqlite",
    "version": "2.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "14087977"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite.aar",
          "url": "sqlite-android-2.6.1.aar",
          "size": 38190,
          "sha512": "005cb48cce00bbb5f61499b944083c132dc965f9ab0fb0de216d7d57268ae21b4c2ac6bc874e57030e1fd4a37d8309a84f8850d1eefccd33efafe3b3fae0bffe",
          "sha256": "fdc440f8269801772a09049fdc67c7dd820b69f8d21cf93cf174cdb84b89e2e7",
          "sha1": "0cd3e67d588172a3580ae1b35a6ecee5129fb84f",
          "md5": "839f09f229430495d4dc9d71db663637"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite.aar",
          "url": "sqlite-android-2.6.1.aar",
          "size": 38190,
          "sha512": "005cb48cce00bbb5f61499b944083c132dc965f9ab0fb0de216d7d57268ae21b4c2ac6bc874e57030e1fd4a37d8309a84f8850d1eefccd33efafe3b3fae0bffe",
          "sha256": "fdc440f8269801772a09049fdc67c7dd820b69f8d21cf93cf174cdb84b89e2e7",
          "sha1": "0cd3e67d588172a3580ae1b35a6ecee5129fb84f",
          "md5": "839f09f229430495d4dc9d71db663637"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-android-2.6.1-sources.jar",
          "url": "sqlite-android-2.6.1-sources.jar",
          "size": 31477,
          "sha512": "049bd969396a9f6c60b411ea209a559b88971f39ef9091e23cda5f7780b83cfe6f0e18c563538106887fd30fb5c4992724852cfff3ad64d11e282e726e11197a",
          "sha256": "b030b10f695d8f3d89aa5058ca8d3207e23502b39bb2a174e4a14fb66282c033",
          "sha1": "46067165b680232a4d4d4b9aae4aa2a150de36df",
          "md5": "64ea9a5bcabc383b2d7be0824beb81e1"
        }
      ]
    }
  ]
}