{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-device-provider-profile",
    "version": "31.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "android-device-provider-profile-31.8.1.jar",
          "url": "android-device-provider-profile-31.8.1.jar",
          "size": 5952,
          "sha512": "3a5e48deb7c3053e52da734a237f9ddeed4850897b99fbda895d14af180e6510dc27b48017f2d227c33a382816b5cc0eefcf00a446e9246e818fa1353261e31b",
          "sha256": "6453f9867bebab65e73f88b5840596faef5594fe216b979d5b4dcc1170750627",
          "sha1": "bf21fdb7f8b5bcd6dcf5b26adb31513fcb2556ce",
          "md5": "112fc838cec3a97b561911aaf37f29ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-device-provider-profile-proto",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "android-device-provider-profile-31.8.1.jar",
          "url": "android-device-provider-profile-31.8.1.jar",
          "size": 5952,
          "sha512": "3a5e48deb7c3053e52da734a237f9ddeed4850897b99fbda895d14af180e6510dc27b48017f2d227c33a382816b5cc0eefcf00a446e9246e818fa1353261e31b",
          "sha256": "6453f9867bebab65e73f88b5840596faef5594fe216b979d5b4dcc1170750627",
          "sha1": "bf21fdb7f8b5bcd6dcf5b26adb31513fcb2556ce",
          "md5": "112fc838cec3a97b561911aaf37f29ba"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-device-provider-profile-31.8.1-javadoc.jar",
          "url": "android-device-provider-profile-31.8.1-javadoc.jar",
          "size": 261,
          "sha512": "71953db7b5d403ded60dfe04c3861670f44fd9bc5ffd8b2612bfa3a80a01daff753c4c62c87a7e3922ab3db3d0588bf51283cde2e772c7f6d5cfab10d2022c0c",
          "sha256": "562973801cd3121d3b54b0e03f99e19f52b8e8b7b89314e251a4291aa5d1abad",
          "sha1": "592cc9934bf06b6b73c595afc52684d27105073e",
          "md5": "b3e9f157a6e63de793dd8839ea3c46b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-device-provider-profile-31.8.1-sources.jar",
          "url": "android-device-provider-profile-31.8.1-sources.jar",
          "size": 2793,
          "sha512": "f28208f5086dd98c91ec81969aa8c9ab219e329b5258581f58116fff1ed1a20fd66531b86008a89d828cb8b2cbda2abb467bd08589962eb47c704ae3356c1867",
          "sha256": "4da24fd3cbd2e8a11757003f37cf920e928c04c5cd19a485bd995fed77a1806a",
          "sha1": "f39fcc123b5d5d90d9c87b13c876c7f6f96150d2",
          "md5": "390390d9602eb16acc9df7f290fe401d"
        }
      ]
    }
  ]
}
