{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "manifest-merger",
    "version": "31.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "manifest-merger-31.11.0.jar",
          "url": "manifest-merger-31.11.0.jar",
          "size": 257902,
          "sha512": "aa76adc3efbd71affdf29508261c5116d48cdd422c028831d3030bc57dd9315b2223b301449a3919b8658cbabf32b1f59efad72bbd269398e37060dd91d5d54f",
          "sha256": "9858af69c77bab6a93db2ece3e44e08f3f4222119f1450e3f682f8a6eeb15aeb",
          "sha1": "f8d20ff1ae626978b95983b046ad15b73018d3e1",
          "md5": "c6f63f74a67808125eb16fe627e09417"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.11.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.11.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "manifest-merger-31.11.0.jar",
          "url": "manifest-merger-31.11.0.jar",
          "size": 257902,
          "sha512": "aa76adc3efbd71affdf29508261c5116d48cdd422c028831d3030bc57dd9315b2223b301449a3919b8658cbabf32b1f59efad72bbd269398e37060dd91d5d54f",
          "sha256": "9858af69c77bab6a93db2ece3e44e08f3f4222119f1450e3f682f8a6eeb15aeb",
          "sha1": "f8d20ff1ae626978b95983b046ad15b73018d3e1",
          "md5": "c6f63f74a67808125eb16fe627e09417"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.11.0-javadoc.jar",
          "url": "manifest-merger-31.11.0-javadoc.jar",
          "size": 275772,
          "sha512": "6aeac4bc7961061157e46a36a801e45aa494d112eb87f16c10c2fd3d69105b83f13c9918ecc95e48f6c8c655d9aeabd08d0d9b9fdfcbadbe15ebb0d9427f639a",
          "sha256": "0c27ee2e86efb2aef9c8ce012f2406cb998a201c4f626f8c330488eb7645e6cd",
          "sha1": "945bf51cb3d407bfd59c77f944e1bf48bf5e9e29",
          "md5": "e5a904173a2f257e9eddea68db2090d7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.11.0-sources.jar",
          "url": "manifest-merger-31.11.0-sources.jar",
          "size": 236565,
          "sha512": "9625d9f54c32a6311095c11265b3ba391a7a9dc02c3b825a75a65d013b16639a469dbac231526ebdbc7adaae9de55d02d8a6aa2e9520bde10f509467b0758ef8",
          "sha256": "526ff34f9d250e74e0fa73661611ec44002432e5c67031dea8ab3cbc4d448294",
          "sha1": "53b8481b9fe5827af249a8808ee51e6299537102",
          "md5": "1b72b3f9d538e55f1c5183b27e5fbd8f"
        }
      ]
    }
  ]
}
