{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-test-api",
    "version": "8.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "builder-test-api-8.9.1.jar",
          "url": "builder-test-api-8.9.1.jar",
          "size": 15329,
          "sha512": "a55278ef4d5cd4c6c894119760f34e3357fd8c8dc61150d15fe46b9b6adba827c1c72ef8b0cb50ddb49ea51337c52993c0bc344f7886be84a23d46ba73c280ca",
          "sha256": "3cd8bb666b56ba6021c7e3e8a12af9348df2e109a42ec4a6d6e87578a46936c3",
          "sha1": "a8b165aaca91a3b1d7b861123887e87e078c9511",
          "md5": "2146c3f99059da9e783c1878d6006040"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.9.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "31.9.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.9.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "builder-test-api-8.9.1.jar",
          "url": "builder-test-api-8.9.1.jar",
          "size": 15329,
          "sha512": "a55278ef4d5cd4c6c894119760f34e3357fd8c8dc61150d15fe46b9b6adba827c1c72ef8b0cb50ddb49ea51337c52993c0bc344f7886be84a23d46ba73c280ca",
          "sha256": "3cd8bb666b56ba6021c7e3e8a12af9348df2e109a42ec4a6d6e87578a46936c3",
          "sha1": "a8b165aaca91a3b1d7b861123887e87e078c9511",
          "md5": "2146c3f99059da9e783c1878d6006040"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-8.9.1-javadoc.jar",
          "url": "builder-test-api-8.9.1-javadoc.jar",
          "size": 117194,
          "sha512": "a2446d609b54f2209814b06937169f04b7ec45dcf42b169e8009a5cd31602988541dd7dfd5b781319edf7c3fe32be76352bdad2255918d26827e06ac0abd4a9e",
          "sha256": "8b3a6998e263355874affd59129c4b4b99cde0a813c9cdc05c5999d9fba9e8ee",
          "sha1": "bfb5a2104e59de847149b75fd798cee090e50188",
          "md5": "eb54ca7048dff3eb33abdbc2542410c5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-8.9.1-sources.jar",
          "url": "builder-test-api-8.9.1-sources.jar",
          "size": 13848,
          "sha512": "6ab7863c3c551d66a9bdb3c338ce4c0f7076d0908db2f49f64f566ef16adebb0340ae3060fc3cc4376fb7dbd1892f790f52b208df15140574504f7ffc20a832f",
          "sha256": "4c24bd3b67f334912d7d0eaef059030a8049c6205e32c9ce37d0a0541d801ae1",
          "sha1": "e5a609db696aa48bc2913cfd1f9a3187494d3d90",
          "md5": "2397f21530f662dc6ce6613a54f9e330"
        }
      ]
    }
  ]
}
