{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-coverage",
    "version": "31.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-31.8.1.jar",
          "url": "android-test-plugin-host-coverage-31.8.1.jar",
          "size": 17154,
          "sha512": "83960363fa7716e7c474656e92ba51065be9f4625c9f5fe70efc2999f487f35ff2d7aecc64949dfacf7b4710725ab7bed7b65c51d2cdaf67494810c2621dc934",
          "sha256": "cb157e5b1cd9df597d774b6dd3d2d47de934376f9cb404574990f9cf37b62278",
          "sha1": "1d5dc641940a5f984fedc7b6fa8e6c529812451e",
          "md5": "ca26e4d053ca17b0adc7b80c3e46c25d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-coverage-proto",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-coverage-31.8.1.jar",
          "url": "android-test-plugin-host-coverage-31.8.1.jar",
          "size": 17154,
          "sha512": "83960363fa7716e7c474656e92ba51065be9f4625c9f5fe70efc2999f487f35ff2d7aecc64949dfacf7b4710725ab7bed7b65c51d2cdaf67494810c2621dc934",
          "sha256": "cb157e5b1cd9df597d774b6dd3d2d47de934376f9cb404574990f9cf37b62278",
          "sha1": "1d5dc641940a5f984fedc7b6fa8e6c529812451e",
          "md5": "ca26e4d053ca17b0adc7b80c3e46c25d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-31.8.1-javadoc.jar",
          "url": "android-test-plugin-host-coverage-31.8.1-javadoc.jar",
          "size": 261,
          "sha512": "71953db7b5d403ded60dfe04c3861670f44fd9bc5ffd8b2612bfa3a80a01daff753c4c62c87a7e3922ab3db3d0588bf51283cde2e772c7f6d5cfab10d2022c0c",
          "sha256": "562973801cd3121d3b54b0e03f99e19f52b8e8b7b89314e251a4291aa5d1abad",
          "sha1": "592cc9934bf06b6b73c595afc52684d27105073e",
          "md5": "b3e9f157a6e63de793dd8839ea3c46b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-31.8.1-sources.jar",
          "url": "android-test-plugin-host-coverage-31.8.1-sources.jar",
          "size": 4834,
          "sha512": "2f590031d7313367bc60f538e366cc314f4726619e3e3a340045a6ff34b233337a0b72137ccae55a5bf7ccba79743c858a1712c71e1b558b18986c506b56be15",
          "sha256": "90b9198a64d82dccf145b7bd9d1a926df2abc7e366ca37f23526418590d8dd29",
          "sha1": "c631420c1acb49553ea0f7f84bc9e2f8b2557aff",
          "md5": "7fd0733391b7a24a23fff535c8d811f5"
        }
      ]
    }
  ]
}
