{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-settings-api",
    "version": "8.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.9.2.jar",
          "url": "gradle-settings-api-8.9.2.jar",
          "size": 9953,
          "sha512": "ad49bbbd4e97070fb102940f3713e328fa12d25d9f212616032dd1b4adfd7a2c718699f5c3cef939f028920db1d06fbeebd467af8ad3ee89739ecaa2b5ccde05",
          "sha256": "a9454b5d1db19e004907a16d26c082b77f577cadc3ca87fd3e43f6834b6782a5",
          "sha1": "481b884e49a4dca881b20e3703a31b29c59475d9",
          "md5": "4e3ced685d9a5aa8f6b7fda050ba59a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-settings-api-8.9.2.jar",
          "url": "gradle-settings-api-8.9.2.jar",
          "size": 9953,
          "sha512": "ad49bbbd4e97070fb102940f3713e328fa12d25d9f212616032dd1b4adfd7a2c718699f5c3cef939f028920db1d06fbeebd467af8ad3ee89739ecaa2b5ccde05",
          "sha256": "a9454b5d1db19e004907a16d26c082b77f577cadc3ca87fd3e43f6834b6782a5",
          "sha1": "481b884e49a4dca881b20e3703a31b29c59475d9",
          "md5": "4e3ced685d9a5aa8f6b7fda050ba59a4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.9.2-javadoc.jar",
          "url": "gradle-settings-api-8.9.2-javadoc.jar",
          "size": 261,
          "sha512": "34cd52bba40a41d9dc24a9bd9d091a5f4e62785e6925c5d3a21f69072b2953a5906478122d217a2cc6afbfad49dd249999659d4d587253a37cf396c63aa35ff0",
          "sha256": "1927f54aed5ba37fa9d6bff215c95262acb5636ca66b0ed10a00803fac99b2f8",
          "sha1": "ce90f8e2d728e7e9f846c5b2f97c3b6b6bb2d226",
          "md5": "70b8eaba1379fcc3ae3076d73c097946"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.9.2-sources.jar",
          "url": "gradle-settings-api-8.9.2-sources.jar",
          "size": 9470,
          "sha512": "60a357f24686a2c7efa3d92d1ae28bd1f94f76a2d9bfc14d4ec0a664c823417db8f2287abc8ecc904cfe6ea46674c550a28747a9c95338a522b09b99caf1f8be",
          "sha256": "095bb68f9de1520c91801d6ceb95f1ab9bde4e7dc2a2036e8ae168a9f3a43e68",
          "sha1": "b1b377e20027b166762b640db9400bcfc377223c",
          "md5": "b2c01262ac7090668f611f75b192db00"
        }
      ]
    }
  ]
}
