{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-common",
    "version": "2.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-common-2.6.1.jar",
          "url": "room-common-2.6.1.jar",
          "size": 61456,
          "sha512": "55dd1ef956e66dc83f478dc0c3263de6f95585d0911faadc2d86616827454eb957d2e052f7085ad548b6d5bd325123da82ec079a261f568731f031bf6c564550",
          "sha256": "99326d3eeca4a64671bc8802f1e45f4e6b348e8c7faba230c3854d316809ffcf",
          "sha1": "ff1b9580850a9b7eef56554e356628d225785265",
          "md5": "3fb8e82756b8b8e10c240f63aa008e97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-common-2.6.1.jar",
          "url": "room-common-2.6.1.jar",
          "size": 61456,
          "sha512": "55dd1ef956e66dc83f478dc0c3263de6f95585d0911faadc2d86616827454eb957d2e052f7085ad548b6d5bd325123da82ec079a261f568731f031bf6c564550",
          "sha256": "99326d3eeca4a64671bc8802f1e45f4e6b348e8c7faba230c3854d316809ffcf",
          "sha1": "ff1b9580850a9b7eef56554e356628d225785265",
          "md5": "3fb8e82756b8b8e10c240f63aa008e97"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-common-2.6.1-sources.jar",
          "url": "room-common-2.6.1-sources.jar",
          "size": 61302,
          "sha512": "5f71a7fcada71067c72651c1dc1a25c5c6c6876454b489827836b890925e498e98119a1bf597e81efc9af1d3d0ecfe71426f817f971f064884bd7883e479754a",
          "sha256": "c25a322bcf9f5740e85d8179796c78b2a85dd5f826b9824fbea6adaa47229dea",
          "sha1": "c04c7202f74aed470c956e50f032ab6d84bff312",
          "md5": "537055792ad857340c1327728d7232bb"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-common is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-common-2.6.1-versionMetadata.json",
          "url": "room-common-2.6.1-versionMetadata.json",
          "size": 12250,
          "sha512": "ea600e61f38ec7b0086bf382d5135f71059b46fda4356670d3a13c4a9b5ca83b3c7351e6f5a92d45cb32351db273440bd631b59d74b1ad5d4cc904adc3e2d002",
          "sha256": "76dc21b2a94c73721771a805ab2b599c252608a20e2e312f07eb232d83acce06",
          "sha1": "8dd479e59c052580eb74a692688712eeb786a1a4",
          "md5": "1727ab40a1365828dbb68d946239a477"
        }
      ]
    }
  ]
}