{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1",
      "buildId:": "12888266"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.0"
          },
          "reason": "activity is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0"
          },
          "reason": "activity is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-1.10.0-sources.jar",
          "url": "activity-1.10.0-sources.jar",
          "size": 62417,
          "sha512": "3c00523e00819523d711ee3cb7f3552daab0788804ebe44ea9f72f1a81ff81ae17738b2b5feafb0c35804b361dde9acaec84a16368bd5cb8d0cb3d17380d0829",
          "sha256": "dbf2175178d9ccfded806ce1349b8abdf3c4254d1f146a0213f78345793bccbe",
          "sha1": "28cb25d6acd9b02b9b87ad1b4e1017ba2ea99c75",
          "md5": "5f3723dfcc5312964dd21fdf91058cec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.0"
          },
          "reason": "activity is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0"
          },
          "reason": "activity is in atomic group androidx.activity"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.10.0.aar",
          "url": "activity-1.10.0.aar",
          "size": 230386,
          "sha512": "b8c805e50d14a7e83fde9b0b0c7560c9bb53bbeb80e924dd02640e93e0c0049e6e9deed6ea8f1c98a5b1f3662ebe3168fb1e92b5703ac6cde83a70d6a81a6349",
          "sha256": "c72301bc7307769cd6c3e0edb8da5837e7dea6fd89a5cdedfcfc87bd581850e1",
          "sha1": "e495f9c2b905131b13875329883b54cff2cc063c",
          "md5": "436267102bd82b7c4469d12c8ca87742"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.0"
          },
          "reason": "activity is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0"
          },
          "reason": "activity is in atomic group androidx.activity"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.10.0.aar",
          "url": "activity-1.10.0.aar",
          "size": 230386,
          "sha512": "b8c805e50d14a7e83fde9b0b0c7560c9bb53bbeb80e924dd02640e93e0c0049e6e9deed6ea8f1c98a5b1f3662ebe3168fb1e92b5703ac6cde83a70d6a81a6349",
          "sha256": "c72301bc7307769cd6c3e0edb8da5837e7dea6fd89a5cdedfcfc87bd581850e1",
          "sha1": "e495f9c2b905131b13875329883b54cff2cc063c",
          "md5": "436267102bd82b7c4469d12c8ca87742"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.0"
          },
          "reason": "activity is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0"
          },
          "reason": "activity is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-1.10.0-versionMetadata.json",
          "url": "activity-1.10.0-versionMetadata.json",
          "size": 31383,
          "sha512": "96429c23280cf779e1208d3d10bf288bb28f24a27c015c7df000dd5dcbe0dfdd4f25c68dca85a541b1e952f4a431ea7b42fce37267397ef4d3ca9871d6ec8ca6",
          "sha256": "99c2b396d4a54712ea6c5dd738ad0f10b8ac58869e51c680492a9bf842a7e91b",
          "sha1": "05742faf1fbed4566b7a6d1cd0a663ee533871fe",
          "md5": "54775666aeebff02eed151bb915f25b8"
        }
      ]
    }
  ]
}