{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.concurrent",
    "module": "concurrent-futures-ktx",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "concurrent-futures-ktx is in atomic group androidx.concurrent"
        }
      ],
      "files": [
        {
          "name": "concurrent-futures-ktx-1.2.0.jar",
          "url": "concurrent-futures-ktx-1.2.0.jar",
          "size": 15903,
          "sha512": "dd1c96cf4d3094deee7d3eee117adb179e2d991eb32df70dfdbd78c2af79440e3ec1d34fce300fc639db3f116a08af1ef627a1a08210aa7f9f3b25e003293c8e",
          "sha256": "e1f3e17bb4358ccd6c77ca45f70635c9aba237261f19eaa4f64a0218c00e2a3e",
          "sha1": "13b49fdb58c74bdfb12eb131b5e22d6d09683e30",
          "md5": "e61240bd54362ae975339560fd496e76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "concurrent-futures-ktx is in atomic group androidx.concurrent"
        }
      ],
      "files": [
        {
          "name": "concurrent-futures-ktx-1.2.0.jar",
          "url": "concurrent-futures-ktx-1.2.0.jar",
          "size": 15903,
          "sha512": "dd1c96cf4d3094deee7d3eee117adb179e2d991eb32df70dfdbd78c2af79440e3ec1d34fce300fc639db3f116a08af1ef627a1a08210aa7f9f3b25e003293c8e",
          "sha256": "e1f3e17bb4358ccd6c77ca45f70635c9aba237261f19eaa4f64a0218c00e2a3e",
          "sha1": "13b49fdb58c74bdfb12eb131b5e22d6d09683e30",
          "md5": "e61240bd54362ae975339560fd496e76"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "concurrent-futures-ktx is in atomic group androidx.concurrent"
        }
      ],
      "files": [
        {
          "name": "concurrent-futures-ktx-1.2.0-sources.jar",
          "url": "concurrent-futures-ktx-1.2.0-sources.jar",
          "size": 9162,
          "sha512": "f86a80c82edc587e211899ff6f656a5b37ca9138da1ad9184b20b525f3ecd8b777cfe681d17bedf2469b7bd261392f40140b6ac0279b433e716baa237b8bc592",
          "sha256": "013580891bea31ace8ba6496bfae09279ef24b10e741ceed6444205fa95454b9",
          "sha1": "034891c54204e087f47c3009c15b688deb81dbdc",
          "md5": "5e5d372156757807fab59353b77e5d60"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "concurrent-futures-ktx is in atomic group androidx.concurrent"
        }
      ],
      "files": [
        {
          "name": "concurrent-futures-ktx-1.2.0-versionMetadata.json",
          "url": "concurrent-futures-ktx-1.2.0-versionMetadata.json",
          "size": 599,
          "sha512": "133628f30933b890917d4506ea122d546a591a1c5c9f0654cc95bff3336ae66fb098ad1dd3973f0a207aed2cecd0e45172cd545884ad34b7189333981620e427",
          "sha256": "2fbefeeba399957115d7e33c9053bbe637fdacbed846bc91580c033b22b840ed",
          "sha1": "bf720bdbfe918cd9f3839c46b8151c1d33e81439",
          "md5": "96d4e75178b963d6bc069ca3005bad85"
        }
      ]
    }
  ]
}