{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-common-deps",
    "version": "2.0.21-1.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-common-deps-2.0.21-1.0.28.jar",
          "url": "symbol-processing-common-deps-2.0.21-1.0.28.jar",
          "size": 109757,
          "sha512": "0abc06e98da1507e472507f44941c2193f68bef5024661c43bcd61adf082674a1677db9443271e7da122bd175c86499ea99602ca8f8167610682b51b31b540eb",
          "sha256": "df5e17b3443f2530c941cb871bc835a897c63699b7b6f20435996bbcc7d76ae9",
          "sha1": "021ab906702cc2c03f00d38b4bb784aed5caa245",
          "md5": "ffde294a8238aff31363b4dfba856c88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-common-deps-2.0.21-1.0.28.jar",
          "url": "symbol-processing-common-deps-2.0.21-1.0.28.jar",
          "size": 109757,
          "sha512": "0abc06e98da1507e472507f44941c2193f68bef5024661c43bcd61adf082674a1677db9443271e7da122bd175c86499ea99602ca8f8167610682b51b31b540eb",
          "sha256": "df5e17b3443f2530c941cb871bc835a897c63699b7b6f20435996bbcc7d76ae9",
          "sha1": "021ab906702cc2c03f00d38b4bb784aed5caa245",
          "md5": "ffde294a8238aff31363b4dfba856c88"
        }
      ]
    }
  ]
}
