{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-coverage",
    "version": "31.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-31.9.0.jar",
          "url": "android-test-plugin-host-coverage-31.9.0.jar",
          "size": 17100,
          "sha512": "4b1057ec4ef92e74ce107860ac008d2e7e26c68e115631f05b8a2fdcd61d7d6aaa4ff0dc30550c04e9a4e6a44b21d9b8aa5cb2ce1bdc7edee9e4fdf88c6b9c71",
          "sha256": "4b28c119db92efd80aedc4762a4ea9d1b3e4880a5ded3036fc92035ed8684253",
          "sha1": "6acc8691f65a4114eafc4c49aec395ed3cfd7be7",
          "md5": "30eea4332312717989c2d65378176f8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-coverage-proto",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-coverage-31.9.0.jar",
          "url": "android-test-plugin-host-coverage-31.9.0.jar",
          "size": 17100,
          "sha512": "4b1057ec4ef92e74ce107860ac008d2e7e26c68e115631f05b8a2fdcd61d7d6aaa4ff0dc30550c04e9a4e6a44b21d9b8aa5cb2ce1bdc7edee9e4fdf88c6b9c71",
          "sha256": "4b28c119db92efd80aedc4762a4ea9d1b3e4880a5ded3036fc92035ed8684253",
          "sha1": "6acc8691f65a4114eafc4c49aec395ed3cfd7be7",
          "md5": "30eea4332312717989c2d65378176f8f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-31.9.0-javadoc.jar",
          "url": "android-test-plugin-host-coverage-31.9.0-javadoc.jar",
          "size": 261,
          "sha512": "f6e135e1f2eeabd4b1063d7a828fc9896e3f39b91a4c4a9e6bc234593ebe05bf7b71099df824ce41d5037e87576959943b8eb0d0cbba280a8bcd4db0129e79ee",
          "sha256": "97e35aebc9c28ffb18c923750524de9d79137adfe50a7a80b39eb239c8060480",
          "sha1": "565871d8402cfa98152503d26d69949f07df4c87",
          "md5": "1fb93cfd2f23b77faf823f3eecbb0271"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-31.9.0-sources.jar",
          "url": "android-test-plugin-host-coverage-31.9.0-sources.jar",
          "size": 4834,
          "sha512": "7b41ef8b100ce4e0ce2f01bf58a6a93400d749f9566ce9b32c44285d02879aada7a950185a73369f31975381c702fd017a2abf4919f45f9dedcdfdeb8dcc0afe",
          "sha256": "d5b8a81f0f9ff26c912d4476d16132b43ab0e8a65251f31cbf10df61cadf4fac",
          "sha1": "827068e671bb54950ffddc0f0796766642642993",
          "md5": "5d8980411e36c125b6e72a800ee84a80"
        }
      ]
    }
  ]
}
