{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.8.2"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.8.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.8.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.8.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.8.2.jar",
          "url": "builder-8.8.2.jar",
          "size": 15225992,
          "sha512": "7541f66a238c29fa3decb2d1211a428436c0db390ef439c14a1cd53148f6ef11c9e5333bba1b1ea26e320ad03ba76e14ce530ae691808584c9541567bc10bf78",
          "sha256": "47c5650d4c02e7101b26f6414703077ca2280cca1be2c4625cefc4a6e71c8b48",
          "sha1": "e5181f901d6a10a9c24b44e48d5c925c79c684b9",
          "md5": "53b11ffd71034c69018e1db83705647d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.8.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.8.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.8.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.8.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.8.2"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.8.2"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.8.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.8.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.8.2"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.8.2"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.8.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.8.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.8.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.8.2.jar",
          "url": "builder-8.8.2.jar",
          "size": 15225992,
          "sha512": "7541f66a238c29fa3decb2d1211a428436c0db390ef439c14a1cd53148f6ef11c9e5333bba1b1ea26e320ad03ba76e14ce530ae691808584c9541567bc10bf78",
          "sha256": "47c5650d4c02e7101b26f6414703077ca2280cca1be2c4625cefc4a6e71c8b48",
          "sha1": "e5181f901d6a10a9c24b44e48d5c925c79c684b9",
          "md5": "53b11ffd71034c69018e1db83705647d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.8.2-javadoc.jar",
          "url": "builder-8.8.2-javadoc.jar",
          "size": 345928,
          "sha512": "60f9c3b41c5abd42203b674d1ea003e2e0dc00e9d9cd063bfe6d8b5e83fcce5919b20cf14f7705054b3ae7a7365121f3c857cee6c0b06ab16d3d769b68952bfd",
          "sha256": "35d1582e9f021cf8476e3e39e9111271f3ce82730e6aca4a14fdc8b170662f09",
          "sha1": "9e227b6b21c736ae3554df2be5bd516f68409771",
          "md5": "523d69f1f04c073f2515c57b2aa16869"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.8.2-sources.jar",
          "url": "builder-8.8.2-sources.jar",
          "size": 284440,
          "sha512": "7e6b881f925aba9dd89ac55b53e4611f5ec63fee187dbca5bbbcf53050ecbd48b74a84c5e24c1106214f5f192ea1d712cf3102a5af5723645795e13031ed1421",
          "sha256": "f1e6bca211c6c11a2f791c4c19d0281f57897e18915d1accc8dff3db70e34894",
          "sha1": "e2c67831c266ae9ea7b9c7a1d918b4bbbc634be5",
          "md5": "3148a059360ad7af774bbaef9d98877c"
        }
      ]
    }
  ]
}
