{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.sqlite",
    "module": "sqlite-framework",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-2.4.0.aar",
          "url": "sqlite-framework-2.4.0.aar",
          "size": 32688,
          "sha512": "159ab302e7d1164429ec89c52ef3e60b07a5ff63722bb66b894aed6bbc99cf1a2d78bbbf6e1a777ceab57e48766140fe4a8c0d764af24d3203316f366c46d8b3",
          "sha256": "ca6e503322b2e60374c2b36c95c50b16709d9388fe36e80fb23de1fbf7a6eb95",
          "sha1": "532d56a4f312d78767534ff1cc2f8084baec6c26",
          "md5": "e1c63283c4e51e1a3bd671106d377545"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-2.4.0.aar",
          "url": "sqlite-framework-2.4.0.aar",
          "size": 32688,
          "sha512": "159ab302e7d1164429ec89c52ef3e60b07a5ff63722bb66b894aed6bbc99cf1a2d78bbbf6e1a777ceab57e48766140fe4a8c0d764af24d3203316f366c46d8b3",
          "sha256": "ca6e503322b2e60374c2b36c95c50b16709d9388fe36e80fb23de1fbf7a6eb95",
          "sha1": "532d56a4f312d78767534ff1cc2f8084baec6c26",
          "md5": "e1c63283c4e51e1a3bd671106d377545"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-2.4.0-sources.jar",
          "url": "sqlite-framework-2.4.0-sources.jar",
          "size": 11350,
          "sha512": "205cb3fef1b6bcb5de3835279b27333adf50ec7320101c6d465854195704d76d78e19e44e25bcdcb1c9704b0aa327f02c3e2566d710cb25757715b208712bf01",
          "sha256": "3614148d2064b62debd45ef7b14297f5d75bd397c4747cb6d63ebab70903117e",
          "sha1": "edd5d14792596229407204bf8e4a68e6f9b6cddc",
          "md5": "96cfb7c73f2bce1894f01d6b60976eb9"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-2.4.0-versionMetadata.json",
          "url": "sqlite-framework-2.4.0-versionMetadata.json",
          "size": 279,
          "sha512": "403ead0a0a52b73859d8bebe0fdf123ee2b527546aaf38a28e00ebbd4456b77adfbba28d8d4a6a76d0f2dc2269b65700d5081a04e5650e30f1f0dcb53588246f",
          "sha256": "21b8efce749eaca777fb1da9c844934589020bdbff3c1f7b1066852a649bc6e8",
          "sha1": "b57ea16d64f2a881eefdf67782a7b52800dbeca3",
          "md5": "c203c328b08420a2ef6639e5e449c86c"
        }
      ]
    }
  ]
}