{
  "formatVersion": "1.1",
  "component": {
    "url": "../../paging-common/3.3.2/paging-common-3.3.2.module",
    "group": "androidx.paging",
    "module": "paging-common",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-common-release.aar",
          "url": "paging-common-android-3.3.2.aar",
          "size": 679056,
          "sha512": "32f0d3904fac47e79a8b213755557fea428481c9fffe7cd5f33c1aee99de94c7c370eae21866da9faf37ca87b110edceb5cb1067e3ad3c321863b80448bdff93",
          "sha256": "8d76f10f6184cb99112e07e5014ede03ac90b9cec366a6e10ef8de1ca984648a",
          "sha1": "09b8c5554597b63c4b6a7bf43514d5f6bda12a71",
          "md5": "0aca69883f742eebcc7a055f1c3f5de1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-common-release.aar",
          "url": "paging-common-android-3.3.2.aar",
          "size": 679056,
          "sha512": "32f0d3904fac47e79a8b213755557fea428481c9fffe7cd5f33c1aee99de94c7c370eae21866da9faf37ca87b110edceb5cb1067e3ad3c321863b80448bdff93",
          "sha256": "8d76f10f6184cb99112e07e5014ede03ac90b9cec366a6e10ef8de1ca984648a",
          "sha1": "09b8c5554597b63c4b6a7bf43514d5f6bda12a71",
          "md5": "0aca69883f742eebcc7a055f1c3f5de1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-common-android-3.3.2-sources.jar",
          "url": "paging-common-android-3.3.2-sources.jar",
          "size": 157137,
          "sha512": "59d0813d6c2c9be8fcb1c2e04a8ebd888e25f9b69dc5f4539f7ca0b487a4d5b16be10dd6fbbc43847e10937b08d6d63ac963a0e59a26576ef5fa4bbb22cf2130",
          "sha256": "9c4eaf6838caf849360b8927da2273136a3da00fad84395e1f993dc43ab6f49c",
          "sha1": "a13a2485c5e31e722be605a817609b3d97c4660c",
          "md5": "b179018aa0f7f476b71d10179acbf1db"
        },
        {
          "name": "paging-common-3.3.2-samples-sources.jar",
          "url": "paging-common-android-3.3.2-samples-sources.jar",
          "size": 40591,
          "sha512": "cbdd887c89003f6b02e6d351773c1559a0dbef7b10cbe911b23cca6356a342b14e594999a9760eee35148e941d87f9005d86db0f299f9a5c4c5201f2e6219625",
          "sha256": "e38a380af1a161410207cb358cb5fcf1ec844432d92a5c9a741524a4767ef970",
          "sha1": "a577b372155d466531746351cd9d1dfb4812d0d5",
          "md5": "6a209d35769c6bb11bbca1bcbcd5b8ad"
        }
      ]
    }
  ]
}