{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-test-api",
    "version": "8.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "builder-test-api-8.9.0.jar",
          "url": "builder-test-api-8.9.0.jar",
          "size": 15329,
          "sha512": "cd7fe42903ad045f4979df7550b782e1196f71117a529f3c2925f4bf735abfa86230aa50610d5fea6244c1370e7d5bb195210c8005a2491313c0737ab4df957a",
          "sha256": "1d517069c6f6621724e4b8a42b3ad9a9eec5c57cc8fe282f3282ffa489065245",
          "sha1": "51097b23fe03a72f748d2497ccce9dfc2ff03a55",
          "md5": "69d78633f30de11d8d3a9239dd3945ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "builder-test-api-8.9.0.jar",
          "url": "builder-test-api-8.9.0.jar",
          "size": 15329,
          "sha512": "cd7fe42903ad045f4979df7550b782e1196f71117a529f3c2925f4bf735abfa86230aa50610d5fea6244c1370e7d5bb195210c8005a2491313c0737ab4df957a",
          "sha256": "1d517069c6f6621724e4b8a42b3ad9a9eec5c57cc8fe282f3282ffa489065245",
          "sha1": "51097b23fe03a72f748d2497ccce9dfc2ff03a55",
          "md5": "69d78633f30de11d8d3a9239dd3945ae"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-8.9.0-javadoc.jar",
          "url": "builder-test-api-8.9.0-javadoc.jar",
          "size": 117194,
          "sha512": "730f1b1b090eca030eeee574c8e8b996abdc3422b89451b11a6f61b7fdb4ce0211debece6090abdc430b998cc11b394e281b2901ff1dd155f8b3de6940e7fed2",
          "sha256": "43dc865408c722f6d5025dc0d9a95c2b7682615ca8df0c9cecb16c8878e19573",
          "sha1": "3acea594305b152866b96e5438a620d78cbc75e0",
          "md5": "2f1afd8e9a2a2842234fa85169c710f0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-8.9.0-sources.jar",
          "url": "builder-test-api-8.9.0-sources.jar",
          "size": 13848,
          "sha512": "28e37c55a25b41361eeda8c5500e19542367950ea1ff398048f098fa6cb9158b5dde494753c86f5c8e57a2ee5b35a7c8fb22db9589b55be13fde7c0615324c0b",
          "sha256": "d227d3536f85ca622f1a5b49f355c35591a70a28d9cd613107a5a018996d4a0e",
          "sha1": "47f81131aa57102547d983fcddc94b4ad7d22def",
          "md5": "8635ab2db2e4c5c95c0654aed7f60bb2"
        }
      ]
    }
  ]
}
