{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-additional-test-output",
    "version": "31.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-additional-test-output-31.8.1.jar",
          "url": "android-test-plugin-host-additional-test-output-31.8.1.jar",
          "size": 29188,
          "sha512": "d48f422b7d5f5fb58d1a5773b675d4f94d8ebd7cd6a1c3cb36fe0028bf42c273bc115319b827b098798df54b61ac05e3430ecff9459e0dad805b69f836c237c1",
          "sha256": "d2820bc5ad291434c14e5758b1f7ba1282c7edbaf047cdee926fd0b08dd58d80",
          "sha1": "5af0bd44cb72f94213d1e137213acf7aeaea2c9e",
          "md5": "5575362b5a83d058685ceef9e331138b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "utp-common",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-additional-test-output-proto",
          "version": {
            "requires": "31.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-additional-test-output-31.8.1.jar",
          "url": "android-test-plugin-host-additional-test-output-31.8.1.jar",
          "size": 29188,
          "sha512": "d48f422b7d5f5fb58d1a5773b675d4f94d8ebd7cd6a1c3cb36fe0028bf42c273bc115319b827b098798df54b61ac05e3430ecff9459e0dad805b69f836c237c1",
          "sha256": "d2820bc5ad291434c14e5758b1f7ba1282c7edbaf047cdee926fd0b08dd58d80",
          "sha1": "5af0bd44cb72f94213d1e137213acf7aeaea2c9e",
          "md5": "5575362b5a83d058685ceef9e331138b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-additional-test-output-31.8.1-javadoc.jar",
          "url": "android-test-plugin-host-additional-test-output-31.8.1-javadoc.jar",
          "size": 261,
          "sha512": "a3824679bfbe91735d7c437f1f928b6bc83d143daf3819cda494b15aed3411da6e0ad5b94c4df22791279ae773c89f03f9d9936ce586a642fa6ed1113291cda8",
          "sha256": "18f93eb0ccdf95313aee24ed168595d755e849a2d0a009c45b17e0bfccbd09e0",
          "sha1": "941d1c4415f068226dc7f18fd0f46775eae15c4b",
          "md5": "039e0715f6c7bdeb7e74a39dd7d824b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-additional-test-output-31.8.1-sources.jar",
          "url": "android-test-plugin-host-additional-test-output-31.8.1-sources.jar",
          "size": 6465,
          "sha512": "7f0778ec79d3cfb4083bf1259a8ffc636df558a6c2e1c4d402c12aec44c27fa66d060d4a2725b8f51b4270e0a53d439dbdf1a3963cc0e24dc1f858d8824f8bf7",
          "sha256": "510d7f69b7a7e3e8f8f2b370d0244bff20eb2ac62ec4a7e6d971af975743293c",
          "sha1": "1501bdb56f1417146ae54913cb4c717394547ea1",
          "md5": "98cf62d99b95fcf4c9339dc211744981"
        }
      ]
    }
  ]
}
