{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup",
    "module": "kotlinpoet",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinpoet-metadata-2.0.0.jar",
          "url": "kotlinpoet-2.0.0.jar",
          "size": 768,
          "sha512": "baa134e11f6170a553d8492487e65ee6feb33733443918354ae5ac464e7f33f8b449af3598d22e0f093b860dc29041cc4e175b4e9e2a76caece59ef702659310",
          "sha256": "48c2f55ee152617269bb71299960ba7ffe03e06e431025b80035e0d8ca18b870",
          "sha1": "82eb81d350ac10af747e9789603e8d51532db516",
          "md5": "b37b37beeb197b99e933df4f85307952"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlinpoet-kotlin-2.0.0-sources.jar",
          "url": "kotlinpoet-2.0.0-sources.jar",
          "size": 308,
          "sha512": "4631a4ec0efaccdf04ad54c3ab1cb34d7d187e56a7da82c30adcd9a9d9b39fbb036238b00283efb6d39c93b31e304a20065c184677277fe22f7ff25d260b185c",
          "sha256": "7c321d53dbff96f00d747464020e29b9caa2a46b291875eea36cc14e5de51324",
          "sha1": "0da7ade0d754e68bbae81bf94d62bdc1a6110967",
          "md5": "0dd5316b2b56e12cf7b736e9307f45ac"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinpoet-js/2.0.0/kotlinpoet-js-2.0.0.module",
        "group": "com.squareup",
        "module": "kotlinpoet-js",
        "version": "2.0.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinpoet-js/2.0.0/kotlinpoet-js-2.0.0.module",
        "group": "com.squareup",
        "module": "kotlinpoet-js",
        "version": "2.0.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinpoet-js/2.0.0/kotlinpoet-js-2.0.0.module",
        "group": "com.squareup",
        "module": "kotlinpoet-js",
        "version": "2.0.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinpoet-jvm/2.0.0/kotlinpoet-jvm-2.0.0.module",
        "group": "com.squareup",
        "module": "kotlinpoet-jvm",
        "version": "2.0.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinpoet-jvm/2.0.0/kotlinpoet-jvm-2.0.0.module",
        "group": "com.squareup",
        "module": "kotlinpoet-jvm",
        "version": "2.0.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinpoet-jvm/2.0.0/kotlinpoet-jvm-2.0.0.module",
        "group": "com.squareup",
        "module": "kotlinpoet-jvm",
        "version": "2.0.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinpoet-wasm-js/2.0.0/kotlinpoet-wasm-js-2.0.0.module",
        "group": "com.squareup",
        "module": "kotlinpoet-wasm-js",
        "version": "2.0.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinpoet-wasm-js/2.0.0/kotlinpoet-wasm-js-2.0.0.module",
        "group": "com.squareup",
        "module": "kotlinpoet-wasm-js",
        "version": "2.0.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinpoet-wasm-js/2.0.0/kotlinpoet-wasm-js-2.0.0.module",
        "group": "com.squareup",
        "module": "kotlinpoet-wasm-js",
        "version": "2.0.0"
      }
    }
  ]
}
