{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.1"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-1.7.1-sources.jar",
          "url": "appcompat-1.7.1-sources.jar",
          "size": 496096,
          "sha512": "2b336d973cc2bf0d24773cf50b766da4194bc4f36991fc591a35483217ab95d4bddb737ac1c0c0b91884935e9a33d784db2f6bf6b94367c37dcd81e6b663dea2",
          "sha256": "d3f8371e7b5b61e36450677af4e911c351c9ec625e9a7fc5b44acbb3fbc3a45d",
          "sha1": "091fc2664fc6ba15f6c431072b24c2133f601383",
          "md5": "8479a20a2cc30476a0594b84b47bfd3e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.1"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-1.7.1.aar",
          "url": "appcompat-1.7.1.aar",
          "size": 1148656,
          "sha512": "27fe0fb4042f9de44261a55eacf9a4da65cc31006db5c4cc9fa3d04ee6c460adb7e146f92a6c318419c4dc0a6bb9be56d119a5ac4c34972c7f294da232ae0067",
          "sha256": "2ad334a323b28046e89b738c77d184cb3dcca32a551ab048851b2fda23a3ba26",
          "sha1": "6c5b56046c7b08e7bf94b6dd14cb616453e6be11",
          "md5": "e60eb556bcaec4b65b67789ff433e070"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.resourceinspection",
          "module": "resourceinspection-annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.1"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-1.7.1.aar",
          "url": "appcompat-1.7.1.aar",
          "size": 1148656,
          "sha512": "27fe0fb4042f9de44261a55eacf9a4da65cc31006db5c4cc9fa3d04ee6c460adb7e146f92a6c318419c4dc0a6bb9be56d119a5ac4c34972c7f294da232ae0067",
          "sha256": "2ad334a323b28046e89b738c77d184cb3dcca32a551ab048851b2fda23a3ba26",
          "sha1": "6c5b56046c7b08e7bf94b6dd14cb616453e6be11",
          "md5": "e60eb556bcaec4b65b67789ff433e070"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.1"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-1.7.1-versionMetadata.json",
          "url": "appcompat-1.7.1-versionMetadata.json",
          "size": 68799,
          "sha512": "f7a2473f6665cddef4d4c6f8961f379e613b70203dd3c0667d8deaa0d404dc3f50a772e8b2b5beb2d879231bf652e4d0f1eba310a6135dcc41b52a817f4ae2d5",
          "sha256": "fa120142562ac47122f1477c46606e7b307da8a0b9d6d0e953e192457d1424c6",
          "sha1": "d9bc137c406f7b7028e6d839267282e7cd2a523a",
          "md5": "95e65f9e5d066ba42c27dc7bf6dcf7f5"
        }
      ]
    }
  ]
}