{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigationevent/1.0.0/navigationevent-1.0.0.module",
    "group": "androidx.navigationevent",
    "module": "navigationevent",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14389689"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent.aar",
          "url": "navigationevent-android-1.0.0.aar",
          "size": 45507,
          "sha512": "faac10c8587cd024aa0d16aeca28d60133f7e2a64855c6a2b506fff61a23c9635eb9ce5e531f2594fd6915029563c564ecbb7c9071fd9ad9cb3e55bbb018fd0e",
          "sha256": "cda4bb83d1c892a208732e99c2d59e4f247ab5c23a1d2524fc004db2e4e9a780",
          "sha1": "8171ee9b6046346e0c0aad9b767a99726a81c6dc",
          "md5": "2ce5b1709160387331b72c3a7da92ff7"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-viewtree",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigationevent.aar",
          "url": "navigationevent-android-1.0.0.aar",
          "size": 45507,
          "sha512": "faac10c8587cd024aa0d16aeca28d60133f7e2a64855c6a2b506fff61a23c9635eb9ce5e531f2594fd6915029563c564ecbb7c9071fd9ad9cb3e55bbb018fd0e",
          "sha256": "cda4bb83d1c892a208732e99c2d59e4f247ab5c23a1d2524fc004db2e4e9a780",
          "sha1": "8171ee9b6046346e0c0aad9b767a99726a81c6dc",
          "md5": "2ce5b1709160387331b72c3a7da92ff7"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent-android-1.0.0-sources.jar",
          "url": "navigationevent-android-1.0.0-sources.jar",
          "size": 40676,
          "sha512": "c1b0d5d643c6ca8df80f67607b973ec4277f7b9984b35f33e1fdf1802125bed2d4d93435e2fd6821374bb80ccb8728b6d71b2f69544768666faba3d01e55d0fb",
          "sha256": "1771b427dc8974d4dc07975ddb52b611cd0d5bd8115de6e49a6fa8762e0f13a1",
          "sha1": "ee726d4cca3c439f0a4a71d7d68310222818ee26",
          "md5": "961ff0b56c22f2f4a3c3d151d278745e"
        },
        {
          "name": "navigationevent-1.0.0-samples-sources.jar",
          "url": "navigationevent-android-1.0.0-samples-sources.jar",
          "size": 5859,
          "sha512": "ade557bee51aab3e41cde6381162fb98e8053ab0a9349fad48367d34bd5cebab5a76cb5081ad0f933e4a3f27ffb56f4ada3f1c5b2563acde1cad98d44d2fc1ac",
          "sha256": "df63ae9684f469f4538795438481b802b394d365566b5af25487e0eef2f4ac6f",
          "sha1": "b7d83bf2bf811c87eec0c4133cf342e08043060e",
          "md5": "3dc3a37e0a809197bcd92e7bf8e9c888"
        }
      ]
    }
  ]
}