{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-runtime",
    "version": "8.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.8.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-runtime-8.8.2.aar",
          "url": "databinding-runtime-8.8.2.aar",
          "size": 60930,
          "sha512": "43003d9f3eaa97913af3664677976a01584633c48f75e0abd9a0013da0534a3438ca6c161ddf5c22ce376f685454a836c1e536a465c4fe7efea022baf9d80940",
          "sha256": "ebfbe5c20163310434833158b0b74293e032cc8a4e059bdd5eabb0a515b866b3",
          "sha1": "43f2396077d1993c9ffda847a18c607cb4ebdcdc",
          "md5": "1cef591490ec1a7a129b1cf623912925"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.8.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-runtime-8.8.2.aar",
          "url": "databinding-runtime-8.8.2.aar",
          "size": 60930,
          "sha512": "43003d9f3eaa97913af3664677976a01584633c48f75e0abd9a0013da0534a3438ca6c161ddf5c22ce376f685454a836c1e536a465c4fe7efea022baf9d80940",
          "sha256": "ebfbe5c20163310434833158b0b74293e032cc8a4e059bdd5eabb0a515b866b3",
          "sha1": "43f2396077d1993c9ffda847a18c607cb4ebdcdc",
          "md5": "1cef591490ec1a7a129b1cf623912925"
        }
      ]
    }
  ]
}
