{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler-processing",
    "version": "2.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "14169401"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.0.10-1.0.24"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-javapoet",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.8.2.jar",
          "url": "room-compiler-processing-2.8.2.jar",
          "size": 938450,
          "sha512": "60f410e72b25115718e2638375a87a7598315964e118e1529a9baff08f74c3b81ea5e67c183630c2ea6a75a9695b8fd3ceeefb44877f9398eb82fa01a0585af4",
          "sha256": "13f771217b751cf266135566d57e8b14867ba6ec0f648c50dfa8a3e57317eeea",
          "sha1": "f790f5c4e7a3df4589c2abafbe1f8ffe5862c573",
          "md5": "8e105a10d0a2d75ed13b3796c02ef799"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.0.10-1.0.24"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.2.1-jre"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-javapoet",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.8.2.jar",
          "url": "room-compiler-processing-2.8.2.jar",
          "size": 938450,
          "sha512": "60f410e72b25115718e2638375a87a7598315964e118e1529a9baff08f74c3b81ea5e67c183630c2ea6a75a9695b8fd3ceeefb44877f9398eb82fa01a0585af4",
          "sha256": "13f771217b751cf266135566d57e8b14867ba6ec0f648c50dfa8a3e57317eeea",
          "sha1": "f790f5c4e7a3df4589c2abafbe1f8ffe5862c573",
          "md5": "8e105a10d0a2d75ed13b3796c02ef799"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.8.2-sources.jar",
          "url": "room-compiler-processing-2.8.2-sources.jar",
          "size": 280825,
          "sha512": "9596693b6255ece6d145f1bef0650c6a09737ad96f1dc022309e40a21004fdab7f4c7fbc00b29cba116a2532e348d0eb6767ca9c5cf8cab53cb5a21ec82a3306",
          "sha256": "9c8835bb1ad840e89f4fded874bd2b7c3f9503b9eb90876cffddf8a2ae1d2b79",
          "sha1": "f6cc130feab5c743718747062dea6ccbd3102138",
          "md5": "25dd5a7d5d5cfa39b5d70cdb12044fe4"
        }
      ]
    }
  ]
}