{
  "formatVersion": "1.1",
  "component": {
    "url": "../../collection/1.5.0/collection-1.5.0.module",
    "group": "androidx.collection",
    "module": "collection",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13113338"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "collection is in atomic group androidx.collection"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "collection-jvm-1.5.0.jar",
          "url": "collection-jvm-1.5.0.jar",
          "size": 877998,
          "sha512": "f880e01f84c789dcf00b01a485f4f7035a146626423975414a6d39396b08d181db20c0113efb22749beafcf54981febcb0532962acb9d57481d4fae5b66e14ce",
          "sha256": "70b35924e4babcdffa37d0e575ee039c56a2d97123342624c48b603233704341",
          "sha1": "7ba2c69414d46ebc2dd76598bdd0a75c54281a57",
          "md5": "4421442c114a4f8c8fe587cf2d668237"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "collection is in atomic group androidx.collection"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "collection-jvm-1.5.0.jar",
          "url": "collection-jvm-1.5.0.jar",
          "size": 877998,
          "sha512": "f880e01f84c789dcf00b01a485f4f7035a146626423975414a6d39396b08d181db20c0113efb22749beafcf54981febcb0532962acb9d57481d4fae5b66e14ce",
          "sha256": "70b35924e4babcdffa37d0e575ee039c56a2d97123342624c48b603233704341",
          "sha1": "7ba2c69414d46ebc2dd76598bdd0a75c54281a57",
          "md5": "4421442c114a4f8c8fe587cf2d668237"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-jvm-1.5.0-sources.jar",
          "url": "collection-jvm-1.5.0-sources.jar",
          "size": 288386,
          "sha512": "4bb82d4fc911421e2c34bcf824a92d1f68207592f44d30933de81cc79db55799c74100f83fe09d5309202ef76e818f28368cdcaaa999db06b75abc8615fe9363",
          "sha256": "bcc6197ec5fb349e86ae3ba6c94b164d3a9ac5a03d9f9c235d7c4eb24e5878b3",
          "sha1": "cce267e9a52246430f814d9eca61bb4248c9b4bb",
          "md5": "f29c1350fe11ceb12ec8c87440377bfd"
        }
      ]
    }
  ]
}