{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "8.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.8.0.jar",
          "url": "gradle-api-8.8.0.jar",
          "size": 364495,
          "sha512": "d718cdda1f2f4a3c55aa42dc5ea38ab67b06e552f0a36bcd5f233da8ce6e1550f501dc78c4eb8fb45e3bbbe2540e896399bd4dc1c8068a3d224e6eb86c094686",
          "sha256": "efec89fd2051b195b68ff75150d2cd1a7a817c22acf64c605abf9e27a40590f3",
          "sha1": "43cd33dd49ca4811206f8e98e06c8f0d05590a33",
          "md5": "e21033d81842396a94bb55dbe0e81560"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.8.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.8.0.jar",
          "url": "gradle-api-8.8.0.jar",
          "size": 364495,
          "sha512": "d718cdda1f2f4a3c55aa42dc5ea38ab67b06e552f0a36bcd5f233da8ce6e1550f501dc78c4eb8fb45e3bbbe2540e896399bd4dc1c8068a3d224e6eb86c094686",
          "sha256": "efec89fd2051b195b68ff75150d2cd1a7a817c22acf64c605abf9e27a40590f3",
          "sha1": "43cd33dd49ca4811206f8e98e06c8f0d05590a33",
          "md5": "e21033d81842396a94bb55dbe0e81560"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.8.0-javadoc.jar",
          "url": "gradle-api-8.8.0-javadoc.jar",
          "size": 151115,
          "sha512": "4632a88aa0970425fb24f0680b55b66f37a86356a6a56e81084b84bb82a069cd2566f727355907f737702765bd3d52c5e5da213482d5b153652d7a611d5c705a",
          "sha256": "89f979007ca4e217e2fae5e9504d3ce562cb1a301bb10819c190d86ef75877c5",
          "sha1": "11c6f4603acf7f2f0fef924dbffe52e3bb87faa6",
          "md5": "fdf5a39b37f491ca34c026a85029861d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.8.0-sources.jar",
          "url": "gradle-api-8.8.0-sources.jar",
          "size": 357728,
          "sha512": "245c7a1693f3c4ac7b02e6e92a93ae3a36260dbf21774eed01e8ccc11f3e154fc2fe006d51f70d4e7186c1593780292b561a65aa9cbee1083db931370e04df8e",
          "sha256": "5604197f1c6f569b60117f23226b4e8f5fe5f28e75b2f189e5f8e689b80ca7f9",
          "sha1": "b5533d868e166e6c22f31173ef9892cde6127c65",
          "md5": "139c0bc0e4529a0769aa5b93fe6345c2"
        }
      ]
    }
  ]
}
