{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-logcat",
    "version": "31.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-logcat-31.9.0.jar",
          "url": "android-test-plugin-host-logcat-31.9.0.jar",
          "size": 17584,
          "sha512": "f2ffe5e3616c2e0a59ab30ade6b201aa921d6945941a23ec3033e2884595020980572ab6e98ba1424e50af6e8760a0a8c66ce5f6edacfa88864a344b7bce44e4",
          "sha256": "836d7f28f94e78faaebf0cb505c7e3565d1ecb0591d4c30b9c5423176ee22b3c",
          "sha1": "39eb51be41a8e98dbe2386539dc80a92d9dc81b2",
          "md5": "d5314e689fee9ca08ce2704e6f3a89d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "utp-common",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-logcat-proto",
          "version": {
            "requires": "31.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-logcat-31.9.0.jar",
          "url": "android-test-plugin-host-logcat-31.9.0.jar",
          "size": 17584,
          "sha512": "f2ffe5e3616c2e0a59ab30ade6b201aa921d6945941a23ec3033e2884595020980572ab6e98ba1424e50af6e8760a0a8c66ce5f6edacfa88864a344b7bce44e4",
          "sha256": "836d7f28f94e78faaebf0cb505c7e3565d1ecb0591d4c30b9c5423176ee22b3c",
          "sha1": "39eb51be41a8e98dbe2386539dc80a92d9dc81b2",
          "md5": "d5314e689fee9ca08ce2704e6f3a89d9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-logcat-31.9.0-javadoc.jar",
          "url": "android-test-plugin-host-logcat-31.9.0-javadoc.jar",
          "size": 261,
          "sha512": "313b4875b115d5e48e183c3cbf304aeb750507865b9b90c3fee46b8a92b38f5b9f4e2350afd4bf119b1f5bc34d546c9fef066d28e54775767bca0059716ce770",
          "sha256": "01ce15dca6f58853243559820dd86f71138a38a91bef1daf0d8382fc7e58914b",
          "sha1": "4879254de867209ff8a57115c08c7c9270444c74",
          "md5": "66a7290c590aa43fbf5be72d0618afe7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-logcat-31.9.0-sources.jar",
          "url": "android-test-plugin-host-logcat-31.9.0-sources.jar",
          "size": 5348,
          "sha512": "bc6d0a141de99c903093c8f716d1b7496e609a8a74db1e0182029e1a8717a25fff5e0422dc4cf319464fe16750057fd30947c284e33966c5e3a8e5039c2750be",
          "sha256": "604def840ebf963a8ad7bd13825bfa417f2079f3a1148bcca02be26a53d98a6e",
          "sha1": "4b2340d68f94417567f909005b92119ff90a16bf",
          "md5": "69e42dcbed95fd558e0afdee2937d638"
        }
      ]
    }
  ]
}
