{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ltgt.gradle.incap",
    "module": "incap",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "incap-1.0.0.jar",
          "url": "incap-1.0.0.jar",
          "size": 2267,
          "sha512": "b41c4bda39f37c0c3242703154d026b155b47b97f3d9143dc52415a5129313d9599cafbeb1d58dcab1dbc3b84aa64b60fa894e5ea02e39c3f1f0642b920a317e",
          "sha256": "cd140bf025c109b8e24e9d8a432714362b8e973bea1bec6ee0c6f43045d10110",
          "sha1": "4d765e5b0e3ee542b57ccffbb9c147c280290207",
          "md5": "bf738be7d7d44f51324ecb80018db60c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "incap-1.0.0.jar",
          "url": "incap-1.0.0.jar",
          "size": 2267,
          "sha512": "b41c4bda39f37c0c3242703154d026b155b47b97f3d9143dc52415a5129313d9599cafbeb1d58dcab1dbc3b84aa64b60fa894e5ea02e39c3f1f0642b920a317e",
          "sha256": "cd140bf025c109b8e24e9d8a432714362b8e973bea1bec6ee0c6f43045d10110",
          "sha1": "4d765e5b0e3ee542b57ccffbb9c147c280290207",
          "md5": "bf738be7d7d44f51324ecb80018db60c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "incap-1.0.0-javadoc.jar",
          "url": "incap-1.0.0-javadoc.jar",
          "size": 285647,
          "sha512": "382819529c048d95e3b18f11000fad2915a7779b98920b5cb5c2f7f6d1192265536d0c84bdd57e4bdeaa6481552e1ad62c390c60b3302e70c8b2cf3c40fe19a3",
          "sha256": "7ca11c43ea5cfcaf28f841963db1c71af8d31f62fdc017e85ab36ec3f4dec5b4",
          "sha1": "3722731e75a74302ffd910a419e5a33222ef5f68",
          "md5": "28a7e08ea6f1511efda9b878768228f6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "incap-1.0.0-sources.jar",
          "url": "incap-1.0.0-sources.jar",
          "size": 2764,
          "sha512": "a600341af28fc71ad300b6446f191a4a593b0753d0ecf6a7b1af6e7403302ae93715957186d225092881a5b16cf7b18ed671f7170d225203d83da776fd98fa58",
          "sha256": "f33d15499c6adbdd189447320310869e2509effc6bb3be485c0e53c3d1157f77",
          "sha1": "755d6db40b7ca7710a0fb739728f55c6aa991225",
          "md5": "fc2b55a9b9b7746dfa13dcad992a3419"
        }
      ]
    }
  ]
}
