{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup",
    "module": "kotlinpoet-javapoet",
    "version": "1.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinpoet-javapoet-1.17.0.jar",
          "url": "kotlinpoet-javapoet-1.17.0.jar",
          "size": 13901,
          "sha512": "05ae8f4f74f81a014861a52ed05e2f105470a64ea15d3f57165fed4d1c17f9062c18b7f1b630db406290b070e06494873a87dfc8f7bb90a7f6acf26fee4836b1",
          "sha256": "0eecc28eb9e28530f25095ea8b31895e7d36bac1d02ce5b1ec43c6f458ae752a",
          "sha1": "30536a5286f1d7f205637a71eaf149fa51128f01",
          "md5": "a8e04ffdc4b46084d703bd4fe3d716c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinpoet-javapoet-1.17.0.jar",
          "url": "kotlinpoet-javapoet-1.17.0.jar",
          "size": 13901,
          "sha512": "05ae8f4f74f81a014861a52ed05e2f105470a64ea15d3f57165fed4d1c17f9062c18b7f1b630db406290b070e06494873a87dfc8f7bb90a7f6acf26fee4836b1",
          "sha256": "0eecc28eb9e28530f25095ea8b31895e7d36bac1d02ce5b1ec43c6f458ae752a",
          "sha1": "30536a5286f1d7f205637a71eaf149fa51128f01",
          "md5": "a8e04ffdc4b46084d703bd4fe3d716c4"
        }
      ]
    }
  ]
}
