{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-adapters",
    "version": "8.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.9.2"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-adapters-8.9.2.aar",
          "url": "databinding-adapters-8.9.2.aar",
          "size": 70402,
          "sha512": "db82caa5180078589edd205e434ac7d5375f814562e5e0fee5dc20d0a0310191d2aee855e4da051c0a76b7a52875789f0d361fe58cffc9b26183c40668d907fc",
          "sha256": "d83b522b9c572953355d191df474f5b096898ec1ff24217bf4c624d27c6e9f48",
          "sha1": "f0fb7fa61cf9430f858ae8f836b66d51a75563f2",
          "md5": "8bde4ef42d41026a9356508f41b7c200"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.9.2"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-adapters-8.9.2.aar",
          "url": "databinding-adapters-8.9.2.aar",
          "size": 70402,
          "sha512": "db82caa5180078589edd205e434ac7d5375f814562e5e0fee5dc20d0a0310191d2aee855e4da051c0a76b7a52875789f0d361fe58cffc9b26183c40668d907fc",
          "sha256": "d83b522b9c572953355d191df474f5b096898ec1ff24217bf4c624d27c6e9f48",
          "sha1": "f0fb7fa61cf9430f858ae8f836b66d51a75563f2",
          "md5": "8bde4ef42d41026a9356508f41b7c200"
        }
      ]
    }
  ]
}
