{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sqlite/2.5.0/sqlite-2.5.0.module",
    "group": "androidx.sqlite",
    "module": "sqlite",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13287481"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-release.aar",
          "url": "sqlite-android-2.5.0.aar",
          "size": 39449,
          "sha512": "aac0f4a7d43b09b80f8c7d35d98d655e0f3bb328ee9323450af1694ab9eb5a14f43f1469cbb44c4b4c1a971b2f8d9df6d4167b1646c1946cdd38590976fcfbf6",
          "sha256": "2b02be3aed8d2994021afe072185af94e29422ffe8066df88868efaca1161ef0",
          "sha1": "16de8f99d346d314af5d9f36d5af2bd4e5ec849b",
          "md5": "a8985ca6e577a5ea398f1debc569c2ea"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-release.aar",
          "url": "sqlite-android-2.5.0.aar",
          "size": 39449,
          "sha512": "aac0f4a7d43b09b80f8c7d35d98d655e0f3bb328ee9323450af1694ab9eb5a14f43f1469cbb44c4b4c1a971b2f8d9df6d4167b1646c1946cdd38590976fcfbf6",
          "sha256": "2b02be3aed8d2994021afe072185af94e29422ffe8066df88868efaca1161ef0",
          "sha1": "16de8f99d346d314af5d9f36d5af2bd4e5ec849b",
          "md5": "a8985ca6e577a5ea398f1debc569c2ea"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-android-2.5.0-sources.jar",
          "url": "sqlite-android-2.5.0-sources.jar",
          "size": 30929,
          "sha512": "2c9c84963bf14734d9afe60c62884cd6dd7fe242f10eb8585b2eae1b33836a51e4a816d3437c3a85eaabfe2161516c9b696a52cb029d7123c9667fa4a525e647",
          "sha256": "4c16014ac7f20b390ec2705b505521e270198bf86109582abb31552396a8dda1",
          "sha1": "8c7d5473ac321276f82817f2c3725d9a4209015b",
          "md5": "bb333fd5be4ebb99b75fc15a8e32f28b"
        }
      ]
    }
  ]
}