{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core",
    "version": "1.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.13.0.aar",
          "url": "core-1.13.0.aar",
          "size": 1270405,
          "sha512": "30db86896440879d19aa5ac98d90ed2aaa922194085c552de21c33f8d1ddb0d4dad062422a99a3943c5cdad52d0f7cee881fc9ef11e96c2a0e65116202ec7803",
          "sha256": "1b96c8eb10c4b40283fdd6e9aa74ffff05fae4f15d54f61ba69d517fcd144695",
          "sha1": "ec9d4e1da0dc84ff6a644624447a99ad136de21d",
          "md5": "e21121960076d6099c871010d3a404b0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-testing",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.13.0.aar",
          "url": "core-1.13.0.aar",
          "size": 1270405,
          "sha512": "30db86896440879d19aa5ac98d90ed2aaa922194085c552de21c33f8d1ddb0d4dad062422a99a3943c5cdad52d0f7cee881fc9ef11e96c2a0e65116202ec7803",
          "sha256": "1b96c8eb10c4b40283fdd6e9aa74ffff05fae4f15d54f61ba69d517fcd144695",
          "sha1": "ec9d4e1da0dc84ff6a644624447a99ad136de21d",
          "md5": "e21121960076d6099c871010d3a404b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.13.0-sources.jar",
          "url": "core-1.13.0-sources.jar",
          "size": 931982,
          "sha512": "54fdae21feadc05275632c6c7268519a020e44c81e57e4427fd887aff258f94fdd8b793c9a434fc93f8e61c538afec029eadf388d148d833b3e277d6a7348cac",
          "sha256": "ac5d17c3dc9744346ca5a2687cb259606787fb10972d5716f49e4c226f092c71",
          "sha1": "9ae580505557c829bed91310494b3ccd0a386dfd",
          "md5": "b69794e1b76b37842f5fe953fffc79b4"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-1.13.0-versionMetadata.json",
          "url": "core-1.13.0-versionMetadata.json",
          "size": 260636,
          "sha512": "3092a4f934c0534778a6c2943066bf395f3b69be56ea198f102bc88ecefa4a2fda9f5f62d4b61c93eb5a20e2060fbaf142e19ecd97f58d6d6cbec6eb6e2a468a",
          "sha256": "eeba5e23e974b0cb5559d56089a22f5f5e81a6d98cebc19acf75281c146953e6",
          "sha1": "3f64a477d9c3b298a55573bf1795baa38203c310",
          "md5": "1b3319ee25a495a2db0b366ac9512462"
        }
      ]
    }
  ]
}