{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aapt2-proto",
    "version": "8.8.1-12006047",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aapt2-proto-8.8.1-12006047.jar",
          "url": "aapt2-proto-8.8.1-12006047.jar",
          "size": 711278,
          "sha512": "b9754d92f6fc2e3443cfcec194b7a01c47e69098ec4054faadb1ff28c60162b679ec28f0a5088322f59bea5870acd7455fed9ccfec44068610a6198167ab0227",
          "sha256": "f1492834728c95300ad8d4ebb0e5f033f3139173b95b862e76302bd1a22adf17",
          "sha1": "e3e1af81be213b2c540386e1c775dfe56c33cfe3",
          "md5": "bb425eddd9d6d3d4a485cbbed34c6268"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        }
      ],
      "files": [
        {
          "name": "aapt2-proto-8.8.1-12006047.jar",
          "url": "aapt2-proto-8.8.1-12006047.jar",
          "size": 711278,
          "sha512": "b9754d92f6fc2e3443cfcec194b7a01c47e69098ec4054faadb1ff28c60162b679ec28f0a5088322f59bea5870acd7455fed9ccfec44068610a6198167ab0227",
          "sha256": "f1492834728c95300ad8d4ebb0e5f033f3139173b95b862e76302bd1a22adf17",
          "sha1": "e3e1af81be213b2c540386e1c775dfe56c33cfe3",
          "md5": "bb425eddd9d6d3d4a485cbbed34c6268"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aapt2-proto-8.8.1-12006047-javadoc.jar",
          "url": "aapt2-proto-8.8.1-12006047-javadoc.jar",
          "size": 1063738,
          "sha512": "3f77c14f4386ca263e228d42bd99ad827efdb5bd7d66fee7d3ce9a7a81587ab47ae4a74c85099f333674a2974709764c303ec8bf6c44d69a5cb69677449a1f6c",
          "sha256": "44e8ea102b7ae1af41e93d7c0a529cb7229ee58a6d3a507add6ca80d842a3d92",
          "sha1": "ebb0a0e30d690e3ef76bb4a72543ba8929d09056",
          "md5": "a8e6ce42711fc76b702c095692cf0c40"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aapt2-proto-8.8.1-12006047-sources.jar",
          "url": "aapt2-proto-8.8.1-12006047-sources.jar",
          "size": 394856,
          "sha512": "182e57ddb441c2fa37fedde4a35b83cc798f650d38a8069851a129ec81ffb65f0c3e04f7ee3fbe2e4ed0d88ee14f079507889dcc5298eea4597d1fd49f5dd5f3",
          "sha256": "6e6e17a22555ccc81f944be7de337ec203775719f2541b30655ee427d6df7787",
          "sha1": "62aec54879edd199046d3cb1e32160d29cca7fe4",
          "md5": "2c514e5eb64f849abae604b4472548ac"
        }
      ]
    }
  ]
}
