{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7201951"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.3.1.aar",
          "url": "lifecycle-livedata-core-2.3.1.aar",
          "size": 8868,
          "sha512": "e9718c199541f38a98a6e5106893fcc6fa0a88db668989989812f198260eafa5f462ac81c4994b5bbc0f82198bd0efb1abd63666dee40539102cef0319d1d65a",
          "sha256": "e55d38c372460f0a03997ddc950c67227511340fd74f8634d99d29653cd81ab1",
          "sha1": "d6d9279495dc234dc37cecf461b3b626825086ef",
          "md5": "c7ccb4a419a95d1cc4dd6cfb1b85b5b7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.3.1.aar",
          "url": "lifecycle-livedata-core-2.3.1.aar",
          "size": 8868,
          "sha512": "e9718c199541f38a98a6e5106893fcc6fa0a88db668989989812f198260eafa5f462ac81c4994b5bbc0f82198bd0efb1abd63666dee40539102cef0319d1d65a",
          "sha256": "e55d38c372460f0a03997ddc950c67227511340fd74f8634d99d29653cd81ab1",
          "sha1": "d6d9279495dc234dc37cecf461b3b626825086ef",
          "md5": "c7ccb4a419a95d1cc4dd6cfb1b85b5b7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-2.3.1-sources.jar",
          "url": "lifecycle-livedata-core-2.3.1-sources.jar",
          "size": 6814,
          "sha512": "e41cbf39485d124f79536b444e5d0ee38d52e993422c7882b4a55bf7bbf573d2fb39eb52ebeeab71222f577bf71c5c1967ce7ac7b6f78108ef6b46d5fb55cfb5",
          "sha256": "a7260859d2991284ae553251a4ff9730f3b57c35d14128f9b079dd5db28958f1",
          "sha1": "38ecd5651d87b6db994df01f93fc72d6e59b846a",
          "md5": "1c8d3854faf03cbaa6d83d2f57345fa6"
        }
      ]
    }
  ]
}
