{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-annotation/1.9.0/runtime-annotation-1.9.0.module",
    "group": "androidx.compose.runtime",
    "module": "runtime-annotation",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13900193"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-annotation.aar",
          "url": "runtime-annotation-android-1.9.0.aar",
          "size": 9072,
          "sha512": "44a154bc99b07358ba1ff47fc9fd46a50188b73d9544229583133efbf172b0c36dfbb96c4ba8198f33086611168307eef382d267d4496ed177834e49f45ab449",
          "sha256": "3fba9d6be5307d998403038f6dfaa3fedd924c5618cb45a49f56a5bf6282509d",
          "sha1": "5e40e47a89961866acb3847692ac479f885d70de",
          "md5": "51775a62892c3a66670bd93ac053c6f4"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-annotation.aar",
          "url": "runtime-annotation-android-1.9.0.aar",
          "size": 9072,
          "sha512": "44a154bc99b07358ba1ff47fc9fd46a50188b73d9544229583133efbf172b0c36dfbb96c4ba8198f33086611168307eef382d267d4496ed177834e49f45ab449",
          "sha256": "3fba9d6be5307d998403038f6dfaa3fedd924c5618cb45a49f56a5bf6282509d",
          "sha1": "5e40e47a89961866acb3847692ac479f885d70de",
          "md5": "51775a62892c3a66670bd93ac053c6f4"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-annotation-android-1.9.0-sources.jar",
          "url": "runtime-annotation-android-1.9.0-sources.jar",
          "size": 11556,
          "sha512": "1c729f1a9b9d418b316828c154ac787aea25610290c0f523a3926b7a08f38ead06d0796444ce415aab960f433ed0ec34378e41f8cbead99df5eb5e995da7db3c",
          "sha256": "7295f7ea24a5d238eca4cfa6e5aa009436870b1607cd554d39e4981de976c374",
          "sha1": "93909912f3419b0d21e3f17c8be94a15885d59c2",
          "md5": "e399429188d9e762a2163568360d2bcc"
        },
        {
          "name": "runtime-annotation-1.9.0-samples-sources.jar",
          "url": "runtime-annotation-android-1.9.0-samples-sources.jar",
          "size": 6132,
          "sha512": "e91df26f47eae05520743a16fcbfeb1d206772dea180805eb6a8087ff486a331ee732dc964f00b54b49bbad86d85befb51a642a0826dfdad054db9f4bd3095c3",
          "sha256": "728e5ed27524324dc79b771f67891f711058041ef3d6b805edbe0e4c0fea3fd4",
          "sha1": "7f2edc491e066e09b04bcb56725b8eacb21ed045",
          "md5": "87b2c17252a543f8eb8c4573978f8d77"
        }
      ]
    }
  ]
}