{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-emulator-control",
    "version": "31.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-emulator-control-31.13.0.jar",
          "url": "android-test-plugin-host-emulator-control-31.13.0.jar",
          "size": 22477,
          "sha512": "da64222e351af4d4d24e2424abed8dd689cc405dea7cc8b53a08bb055c7d8abf185d3674820e5236a6e0cf0c26fddf45cf8a49da3a0b315a39b02048c3b406bc",
          "sha256": "43f5a73b559758c1d3a119277a109ea552a3e4f75368842fb79af7308ad22465",
          "sha1": "ec3e5fb919f93d13ca9076d5e9798547292291e3",
          "md5": "74fb06047de10a0b3943f761da7f2ad5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-emulator-control-proto",
          "version": {
            "requires": "31.13.0"
          }
        },
        {
          "group": "com.android.tools.emulator",
          "module": "proto",
          "version": {
            "requires": "31.13.0"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha03"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-driver-instrumentation",
          "version": {
            "requires": "0.0.9-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-emulator-control-31.13.0.jar",
          "url": "android-test-plugin-host-emulator-control-31.13.0.jar",
          "size": 22477,
          "sha512": "da64222e351af4d4d24e2424abed8dd689cc405dea7cc8b53a08bb055c7d8abf185d3674820e5236a6e0cf0c26fddf45cf8a49da3a0b315a39b02048c3b406bc",
          "sha256": "43f5a73b559758c1d3a119277a109ea552a3e4f75368842fb79af7308ad22465",
          "sha1": "ec3e5fb919f93d13ca9076d5e9798547292291e3",
          "md5": "74fb06047de10a0b3943f761da7f2ad5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-emulator-control-31.13.0-javadoc.jar",
          "url": "android-test-plugin-host-emulator-control-31.13.0-javadoc.jar",
          "size": 261,
          "sha512": "45dada7d95416045ad218ad364f66aacc64bd07ea6ed95539dc652bf3c0977040e88a4a9b44c8653ba929ce4fbd11be1e6a21ac01dd937c8c6e797b2e824179f",
          "sha256": "cebceba5b60e48f34a1a416b857f8eaba5eaa30c3c0d69794f7f0c9356b2fea9",
          "sha1": "dcac025ba8756b080643bfa3fb7003ae0ac151dd",
          "md5": "817c65f00575dcab61f3a1e140c862b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-emulator-control-31.13.0-sources.jar",
          "url": "android-test-plugin-host-emulator-control-31.13.0-sources.jar",
          "size": 8383,
          "sha512": "25bad314e926a35d7dcc500cfa5fbd382d5904d33ea95da7a0171ea9a4f385a77f30c7ee841c2ed3cf4954a301d2c7d762f63de042587be86b579485b0d04bec",
          "sha256": "9ee9a880058db686d6eb47e515120a63341d1fc05cc3784b236ab17b2e7b621e",
          "sha1": "d4e4b39022711b34b7972174c3c49ee82fb570dd",
          "md5": "adf2247f6d3527de8fbc11b64bfede86"
        }
      ]
    }
  ]
}
