{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-paging",
    "version": "2.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-paging-2.6.1.aar",
          "url": "room-paging-2.6.1.aar",
          "size": 17558,
          "sha512": "b0c5c21fc33b3610c77b7e8697d2031f935312eeef635eb283533cc4d5c2924e09e262f527dd7ecfb9c1e1fd985227efde9ddf0889a5ff8363bf48c6838723f6",
          "sha256": "ab1b21ff01eedf513255e1feb9de1858b69faf2000ec0ed13570e42f7f250489",
          "sha1": "4647807ac886d906d384a4f04fa04ff9c5e27015",
          "md5": "5dedef4d64710c949e95a42f56e83601"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-paging-2.6.1.aar",
          "url": "room-paging-2.6.1.aar",
          "size": 17558,
          "sha512": "b0c5c21fc33b3610c77b7e8697d2031f935312eeef635eb283533cc4d5c2924e09e262f527dd7ecfb9c1e1fd985227efde9ddf0889a5ff8363bf48c6838723f6",
          "sha256": "ab1b21ff01eedf513255e1feb9de1858b69faf2000ec0ed13570e42f7f250489",
          "sha1": "4647807ac886d906d384a4f04fa04ff9c5e27015",
          "md5": "5dedef4d64710c949e95a42f56e83601"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-paging-2.6.1-sources.jar",
          "url": "room-paging-2.6.1-sources.jar",
          "size": 6461,
          "sha512": "d00774e8a6e3037b85da20c454e48bc53b1b6d8bb2ee067b1fbb31fb013be9f3fefa435de598a4d1741ad0306e42233bb00681a3d65f6285be729e6d71bd95a8",
          "sha256": "ae3b8198a108a5ee791412b649db773eaf60d88c0acc4a2a7a6fde1cf723e571",
          "sha1": "ea26e308515a71326d421b61b7f521b036563975",
          "md5": "92213334c5cbcfdfe8f846522bd9da89"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-paging is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-paging-2.6.1-versionMetadata.json",
          "url": "room-paging-2.6.1-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}