{
  "formatVersion": "1.1",
  "component": {
    "group": "io.objectbox",
    "module": "objectbox-android",
    "version": "5.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "dbOnlyReleaseVariantDbOnlyReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "objectbox-android-5.0.1.aar",
          "url": "objectbox-android-5.0.1.aar",
          "size": 3450917,
          "sha512": "b347a1b5204d92d89abc4ee6bd91ba97f12c3cceceb3a55f0d719dad50841e6d07cadc926450d90a5a0a40269213c106095b348a8ec71b395a5fa10363c1e2e3",
          "sha256": "8acf2485f914f0bc02f3df06339f7418f1ac0df81e385523c0a839de1edbddf4",
          "sha1": "65396bf1e42d91823973366dca179183c1cfafd4",
          "md5": "f75fb2c06727aa4595da898554312170"
        }
      ]
    },
    {
      "name": "dbOnlyReleaseVariantDbOnlyReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.objectbox",
          "module": "objectbox-java",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "objectbox-android-5.0.1.aar",
          "url": "objectbox-android-5.0.1.aar",
          "size": 3450917,
          "sha512": "b347a1b5204d92d89abc4ee6bd91ba97f12c3cceceb3a55f0d719dad50841e6d07cadc926450d90a5a0a40269213c106095b348a8ec71b395a5fa10363c1e2e3",
          "sha256": "8acf2485f914f0bc02f3df06339f7418f1ac0df81e385523c0a839de1edbddf4",
          "sha1": "65396bf1e42d91823973366dca179183c1cfafd4",
          "md5": "f75fb2c06727aa4595da898554312170"
        }
      ]
    },
    {
      "name": "dbOnlyReleaseVariantDbOnlyReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "objectbox-android-5.0.1-sources.jar",
          "url": "objectbox-android-5.0.1-sources.jar",
          "size": 6704,
          "sha512": "f0133c8b478c05d2c798bd551c1c4eedee67ed14f8bb0010046763cc4d3b1085a5735c52aa3743c413e49536b80daf5fde4b2423091afb7d0ba221d65e2e0bf9",
          "sha256": "6b4f7a4ef0a93b1614f7738f7436763ad914e9e8c2226881ba42523d879d42fc",
          "sha1": "131c306884209718648380f31cf3b8731df0ab5d",
          "md5": "ef492bb0b22916e9535a74900e5054cb"
        }
      ]
    },
    {
      "name": "dbOnlyReleaseVariantDbOnlyReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "objectbox-android-5.0.1-javadoc.jar",
          "url": "objectbox-android-5.0.1-javadoc.jar",
          "size": 299127,
          "sha512": "fb42e7384a91316e353bfdf720272047573e91d7eeeb77763f4062fc5f3babb05363148ae1ce9ed3c8d809e50638c82f958b58de39cf442e057c6794069c8b31",
          "sha256": "dc99006709fa5fc9dfb1b97f9191898ce59fad4dd526e707d9f4c30f8d85f993",
          "sha1": "53a4e76bdcdddbc33586d76e87a5e3858b1c3ae6",
          "md5": "f8eb62ec2025a0f0a6f87b225b2e3d94"
        }
      ]
    }
  ]
}
