{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.9.2"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.9.2.jar",
          "url": "builder-8.9.2.jar",
          "size": 15419729,
          "sha512": "0e7aa2d1db4c5308fd9c8be8e24b881795170e1bf6b9f3a6d9cd76b78ecf7c663aa07c2aa049e44ffbea9371fb5600cafd9a2b0ee54fc1f1bc457c9aa1d35b33",
          "sha256": "7dc1d36d12ee81300c5b1672aaae336d1c3cfe90a7b26b2b551389604150e53b",
          "sha1": "0f5879953ae9f284e5c6289f62e9960bf532fdb6",
          "md5": "f25c1b56107bca6621382247c77c62cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.9.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.9.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.9.2"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.9.2"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.9.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.9.2"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.79"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.79"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.9.2"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.9.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.9.2.jar",
          "url": "builder-8.9.2.jar",
          "size": 15419729,
          "sha512": "0e7aa2d1db4c5308fd9c8be8e24b881795170e1bf6b9f3a6d9cd76b78ecf7c663aa07c2aa049e44ffbea9371fb5600cafd9a2b0ee54fc1f1bc457c9aa1d35b33",
          "sha256": "7dc1d36d12ee81300c5b1672aaae336d1c3cfe90a7b26b2b551389604150e53b",
          "sha1": "0f5879953ae9f284e5c6289f62e9960bf532fdb6",
          "md5": "f25c1b56107bca6621382247c77c62cb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.9.2-javadoc.jar",
          "url": "builder-8.9.2-javadoc.jar",
          "size": 345928,
          "sha512": "48d4b1407b05c3d140b6d11caadc7fe59d0f8efa8fde7e7e0e4bd65dab03c5167a340e690c45fe91478234fecb344ddf90c6e40ab93a83fd75f1b779fe9d1bd4",
          "sha256": "5bc6c76e02684ab4030aabd6e6a500f9524c3c311dc7224be3c1291b4e3c2f75",
          "sha1": "beb9cf31b8c6b1fdd114e5aa9874d11821fad0a8",
          "md5": "76abc6acfad8317d7cd186a5c032fd0f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.9.2-sources.jar",
          "url": "builder-8.9.2-sources.jar",
          "size": 284717,
          "sha512": "8b3f50efabc96931946f97b669d60312f1bc852d452e4fb8ad5fddd7969f1dec3f7906f74c1cdbc0067940f6dc1cb2ef8a0abdaa74769c893742a8e0c1e91529",
          "sha256": "fccca32868bb1f888b651f3abb7b857f4d0e8f44b28df75fff36e725b65157de",
          "sha1": "9ee79c9d7ff1c20105d871342b70e5ad8cfe6fdb",
          "md5": "3939060ffcd7b9e3ed8012575a5ecd99"
        }
      ]
    }
  ]
}
