{
  "formatVersion": "1.1",
  "component": {
    "group": "io.objectbox",
    "module": "objectbox-java-api",
    "version": "5.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "objectbox-java-api-5.0.1.jar",
          "url": "objectbox-java-api-5.0.1.jar",
          "size": 16315,
          "sha512": "441bcfef11c7927fbcd8dc03264d90267d13e6263e33c04ced5c5dfe9d2f8e458c91edf6ae9b7257d7b0b25dd6953b2cf433d017527d356000cf0948114a8537",
          "sha256": "19926d16931dc16219f1b5112ecc0617e3c6488e39faf5cb14218d7f34d5c8a7",
          "sha1": "3212e517bdb7cc85cba427117620f92fec97d553",
          "md5": "3ceb8e10aa1fd363a5b9ede081159e94"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "objectbox-java-api-5.0.1.jar",
          "url": "objectbox-java-api-5.0.1.jar",
          "size": 16315,
          "sha512": "441bcfef11c7927fbcd8dc03264d90267d13e6263e33c04ced5c5dfe9d2f8e458c91edf6ae9b7257d7b0b25dd6953b2cf433d017527d356000cf0948114a8537",
          "sha256": "19926d16931dc16219f1b5112ecc0617e3c6488e39faf5cb14218d7f34d5c8a7",
          "sha1": "3212e517bdb7cc85cba427117620f92fec97d553",
          "md5": "3ceb8e10aa1fd363a5b9ede081159e94"
        }
      ]
    }
  ]
}
