{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.9.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.9.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.9.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.9.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.9.1.jar",
          "url": "builder-8.9.1.jar",
          "size": 15432585,
          "sha512": "70a5133840fccce9cfc911f72a79cf9eaca9e25ab475e6e3521f86313c72bbf34e4ce4874961c4f80732646e52243339eb9c075886c79a67cf30dc70772ecb54",
          "sha256": "066763c90b14fb82e9b18dd8cadd432981fdd2fcff927393d5230c44ad4ee252",
          "sha1": "5dfef4d0bb66f0f2df305d0dbfe1dc014c2ceca4",
          "md5": "6983f8673b0d158483a4c165a745ffac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.9.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.9.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.9.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.9.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.9.1"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.9.1"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.9.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.9.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.9.1"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.79"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.79"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.9.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.9.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.9.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.9.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.9.1.jar",
          "url": "builder-8.9.1.jar",
          "size": 15432585,
          "sha512": "70a5133840fccce9cfc911f72a79cf9eaca9e25ab475e6e3521f86313c72bbf34e4ce4874961c4f80732646e52243339eb9c075886c79a67cf30dc70772ecb54",
          "sha256": "066763c90b14fb82e9b18dd8cadd432981fdd2fcff927393d5230c44ad4ee252",
          "sha1": "5dfef4d0bb66f0f2df305d0dbfe1dc014c2ceca4",
          "md5": "6983f8673b0d158483a4c165a745ffac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.9.1-javadoc.jar",
          "url": "builder-8.9.1-javadoc.jar",
          "size": 345928,
          "sha512": "6dca0bdcb32eb5df8e0ae54806340c70e8571ab9ddd3e2e54f522c43290ad0a6c2656872744e0ffa185e1428eb55dabba270031c7ae8635c73fd6158bad8b06d",
          "sha256": "d1e6a1565c76540e27fb79effa19ce67b87027b639e96f806949fc414f841e2b",
          "sha1": "404dd92ede779fe0c286484eb79e587115be5214",
          "md5": "26c8e3d075d026e94947c40b8cf1d0bb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.9.1-sources.jar",
          "url": "builder-8.9.1-sources.jar",
          "size": 284717,
          "sha512": "8e654d9d749e8ba85c11ae2c508c90fa6308984e7e94edb4908611b1471d2b405e315532e6e34476198129e2961cfc89696afb5c5ce1b65395cd047d2c658097",
          "sha256": "1927c1e86f625d829ee212976fe13efdb7a0724f0dc9c524ff7525f33b396200",
          "sha1": "e26251802c2de2e6972f82b539b6bfcbcf645152",
          "md5": "efe98f2ed7b0417a6e635130a5b2aea3"
        }
      ]
    }
  ]
}
