{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-test-api",
    "version": "8.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "builder-test-api-8.12.2.jar",
          "url": "builder-test-api-8.12.2.jar",
          "size": 15329,
          "sha512": "3afc6b7fb6a679dc4fa57f23a2887e8570d29d5924656d767f0f9b74c43fc139b62c8b03245ca8449599738798d21270729092e525a4fcbf45fd71d8ee327afa",
          "sha256": "b5dddd6500d82a7f3a47af086959e507289efb3f7c01ea32ed3d2019c9b14b1c",
          "sha1": "5d6e7596b064690e538182de35733460630d3729",
          "md5": "56faed3f4ea340034a7704da8846f860"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.12.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "31.12.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.12.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "builder-test-api-8.12.2.jar",
          "url": "builder-test-api-8.12.2.jar",
          "size": 15329,
          "sha512": "3afc6b7fb6a679dc4fa57f23a2887e8570d29d5924656d767f0f9b74c43fc139b62c8b03245ca8449599738798d21270729092e525a4fcbf45fd71d8ee327afa",
          "sha256": "b5dddd6500d82a7f3a47af086959e507289efb3f7c01ea32ed3d2019c9b14b1c",
          "sha1": "5d6e7596b064690e538182de35733460630d3729",
          "md5": "56faed3f4ea340034a7704da8846f860"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-8.12.2-javadoc.jar",
          "url": "builder-test-api-8.12.2-javadoc.jar",
          "size": 117194,
          "sha512": "a39e6055db1dc65a330c969c580af980a2fd250bc2a6e4b77ba964d308c28849de0b8ce309026512b7e96f369cbbc09ee5cde0f0f4c72daedafa010a0fb81151",
          "sha256": "5d070ba65d8d3568882812e51ff621d6718bdb2e89759f0a941ae1a24ddd85e8",
          "sha1": "99e6ddbc0629a3174a095b119e4c905ebe455cc6",
          "md5": "08ee2d1688ba6e8f5c01e0d4575964fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-8.12.2-sources.jar",
          "url": "builder-test-api-8.12.2-sources.jar",
          "size": 13848,
          "sha512": "631e8fe413afd9ae97d34a6ca242c98c961adffaed8a9ce6693c8ee343ae8d498c28d57d5313ee51d5ee03fa3366066c4c31d7c0ee34ed43c54fd98f642f3c3c",
          "sha256": "434638cff42fb0a1c2e0c02bd499f3a8715effc3f4478a479206aebf4934d8c2",
          "sha1": "82101df6eb5ff7c1c1fb39c4bfdf5547f0eff4b2",
          "md5": "20102d47aa7347ee7eb1580628d94e4c"
        }
      ]
    }
  ]
}
