{
  "formatVersion": "1.1",
  "component": {
    "url": "../../room-migration/2.7.1/room-migration-2.7.1.module",
    "group": "androidx.room",
    "module": "room-migration",
    "version": "2.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13368038"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "room-migration-jvm-2.7.1.jar",
          "url": "room-migration-jvm-2.7.1.jar",
          "size": 90647,
          "sha512": "60c5ab7c6ddda064b8385a4fe07a97a9fee5a3211e372f90a0c45ca7c75781fc5719eadd7119807079f4674a5b3852351341bd562f64aa6347c2ecc4840b9d3f",
          "sha256": "8c5cec8f2d5da1cb9fde960fdd2253bbfc6be74f9a4a03ecdb82da17662231ac",
          "sha1": "6ea2d9759a174cf3633c585129395617c10541f6",
          "md5": "4c4e7a6a1559c3679e4afdae6fc6a47d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "room-migration-jvm-2.7.1.jar",
          "url": "room-migration-jvm-2.7.1.jar",
          "size": 90647,
          "sha512": "60c5ab7c6ddda064b8385a4fe07a97a9fee5a3211e372f90a0c45ca7c75781fc5719eadd7119807079f4674a5b3852351341bd562f64aa6347c2ecc4840b9d3f",
          "sha256": "8c5cec8f2d5da1cb9fde960fdd2253bbfc6be74f9a4a03ecdb82da17662231ac",
          "sha1": "6ea2d9759a174cf3633c585129395617c10541f6",
          "md5": "4c4e7a6a1559c3679e4afdae6fc6a47d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.1"
          },
          "reason": "room-migration is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-migration-jvm-2.7.1-sources.jar",
          "url": "room-migration-jvm-2.7.1-sources.jar",
          "size": 21941,
          "sha512": "f488be39cdbfb24a779670653f815a420ba73d1abba2c0da8c6dad3b018dd34ecfe07b474a6eea542d941b470029b645f1949a18f458c43032fab6ebfa294c35",
          "sha256": "09d9c005f059cf60d02aeea2597c56fa10b40fdaa03b99993a0a448ffb36f8bb",
          "sha1": "cd7e2c670a2711349ec11e41da464bb92a7caf68",
          "md5": "a1ee86c89856f2c3d05ba146378d8745"
        }
      ]
    }
  ]
}